/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * List all sessions for the current user
 * @summary List sessions
 */
export const listSessionsQueryLimitDefault = 20;
export const listSessionsQueryLimitMax = 100;



export const ListSessionsQueryParams = zod.object({
  "cursor": zod.string().optional().describe('Cursor for pagination (last seen item ID)'),
  "limit": zod.number().min(1).max(listSessionsQueryLimitMax).default(listSessionsQueryLimitDefault).describe('Number of items to return per page')
})

export const ListSessionsResponse = zod.object({
  "data": zod.array(zod.object({
  "user_id": zod.string().describe('User ID.'),
  "id": zod.string().describe('Session token (identifier).'),
  "expires_at": zod.string().datetime({}),
  "ip_address": zod.string().optional(),
  "user_agent": zod.string().optional(),
  "created_at": zod.string().datetime({})
}).describe('User session')).optional(),
  "pagination": zod.object({
  "next_cursor": zod.string().optional(),
  "limit": zod.number().optional(),
  "has_more": zod.boolean().optional()
}).optional()
})

/**
 * Get details of a specific session
 * @summary Get session details
 */
export const GetSessionParams = zod.object({
  "id": zod.string().describe('Session token (used as identifier)')
})

export const GetSessionResponse = zod.object({
  "user_id": zod.string().describe('User ID.'),
  "id": zod.string().describe('Session token (identifier).'),
  "expires_at": zod.string().datetime({}),
  "ip_address": zod.string().optional(),
  "user_agent": zod.string().optional(),
  "created_at": zod.string().datetime({})
}).describe('User session')

/**
 * Delete a session
 * @summary Delete a session
 */
export const DeleteSessionParams = zod.object({
  "id": zod.string().describe('Session token (used as identifier)')
})

