/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonErrorError400,
  CommonErrorError401,
  CommonErrorError404,
  CommonErrorError500,
  FilesCreateRequest,
  FilesCreateResponse,
  FilesResponse
} from '../model';





<<<<<<< HEAD
export type getFilePresignedUrlResponse200 = {
  data: FileGetResponseResponse
  status: 200
=======
/**
 * Upload a new file to the system. The request should include the file's name, size in bytes, MIME type, and the file content itself. The response will include the unique identifier for the newly created file, along with its details and a URL for downloading it.
 */
export type filesServiceCreateFileResponse201 = {
  data: FilesCreateResponse
  status: 201
>>>>>>> main
}

export type filesServiceCreateFileResponse400 = {
  data: CommonErrorError400
  status: 400
}

export type filesServiceCreateFileResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type filesServiceCreateFileResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type filesServiceCreateFileResponseSuccess = (filesServiceCreateFileResponse201) & {
  headers: Headers;
};
export type filesServiceCreateFileResponseError = (filesServiceCreateFileResponse400 | filesServiceCreateFileResponse401 | filesServiceCreateFileResponse500) & {
  headers: Headers;
};

export type filesServiceCreateFileResponse = (filesServiceCreateFileResponseSuccess | filesServiceCreateFileResponseError)

export const getFilesServiceCreateFileUrl = () => {




  return `/api/api/files`
}

<<<<<<< HEAD
/**
 * Returns a time-limited presigned S3 GET URL to download or view the file.
 * @summary Get presigned URL for file download
 */
export const getFilePresignedUrl = async (fileId: string, options?: RequestInit): Promise<getFilePresignedUrlResponse> => {
=======
export const filesServiceCreateFile = async (filesCreateRequest: FilesCreateRequest, options?: RequestInit): Promise<filesServiceCreateFileResponse> => {
>>>>>>> main

  const res = await fetch(getFilesServiceCreateFileUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      filesCreateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesServiceCreateFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as filesServiceCreateFileResponse
}




export const getFilesServiceCreateFileMutationOptions = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesServiceCreateFile>>, TError,{data: FilesCreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filesServiceCreateFile>>, TError,{data: FilesCreateRequest}, TContext> => {

const mutationKey = ['filesServiceCreateFile'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesServiceCreateFile>>, {data: FilesCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  filesServiceCreateFile(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesServiceCreateFileMutationResult = NonNullable<Awaited<ReturnType<typeof filesServiceCreateFile>>>
    export type FilesServiceCreateFileMutationBody = FilesCreateRequest
    export type FilesServiceCreateFileMutationError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500

    export const useFilesServiceCreateFile = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesServiceCreateFile>>, TError,{data: FilesCreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesServiceCreateFile>>,
        TError,
        {data: FilesCreateRequest},
        TContext
      > => {
      return useMutation(getFilesServiceCreateFileMutationOptions(options), queryClient);
    }
    /**
 * Get the details of a specific file by its unique identifier, including its name, size, type, and download URL.
 */
export type filesServiceGetFileResponse200 = {
  data: FilesResponse
  status: 200
}

export type filesServiceGetFileResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type filesServiceGetFileResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type filesServiceGetFileResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type filesServiceGetFileResponseSuccess = (filesServiceGetFileResponse200) & {
  headers: Headers;
};
export type filesServiceGetFileResponseError = (filesServiceGetFileResponse401 | filesServiceGetFileResponse404 | filesServiceGetFileResponse500) & {
  headers: Headers;
};

export type filesServiceGetFileResponse = (filesServiceGetFileResponseSuccess | filesServiceGetFileResponseError)

export const getFilesServiceGetFileUrl = (fileId: string,) => {




  return `/api/api/files/${fileId}`
}

export const filesServiceGetFile = async (fileId: string, options?: RequestInit): Promise<filesServiceGetFileResponse> => {

  const res = await fetch(getFilesServiceGetFileUrl(fileId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesServiceGetFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as filesServiceGetFileResponse
}





export const getFilesServiceGetFileQueryKey = (fileId: string,) => {
    return [
    `/api/api/files/${fileId}`
    ] as const;
    }


export const getFilesServiceGetFileQueryOptions = <TData = Awaited<ReturnType<typeof filesServiceGetFile>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesServiceGetFileQueryKey(fileId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesServiceGetFile>>> = ({ signal }) => filesServiceGetFile(fileId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(fileId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesServiceGetFileQueryResult = NonNullable<Awaited<ReturnType<typeof filesServiceGetFile>>>
export type FilesServiceGetFileQueryError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500


export function useFilesServiceGetFile<TData = Awaited<ReturnType<typeof filesServiceGetFile>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesServiceGetFile>>,
          TError,
          Awaited<ReturnType<typeof filesServiceGetFile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesServiceGetFile<TData = Awaited<ReturnType<typeof filesServiceGetFile>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesServiceGetFile>>,
          TError,
          Awaited<ReturnType<typeof filesServiceGetFile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesServiceGetFile<TData = Awaited<ReturnType<typeof filesServiceGetFile>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesServiceGetFile<TData = Awaited<ReturnType<typeof filesServiceGetFile>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesServiceGetFileQueryOptions(fileId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




<<<<<<< HEAD


export type deleteFileResponse204 = {
=======
/**
 * Delete a specific file from the system using its unique identifier. This operation will permanently remove the file and its associated data. The response will indicate whether the deletion was successful or if the file was not found.
 */
export type filesServiceDeleteFileResponse204 = {
>>>>>>> main
  data: void
  status: 204
}

export type filesServiceDeleteFileResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type filesServiceDeleteFileResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type filesServiceDeleteFileResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type filesServiceDeleteFileResponseSuccess = (filesServiceDeleteFileResponse204) & {
  headers: Headers;
};
export type filesServiceDeleteFileResponseError = (filesServiceDeleteFileResponse401 | filesServiceDeleteFileResponse404 | filesServiceDeleteFileResponse500) & {
  headers: Headers;
};

export type filesServiceDeleteFileResponse = (filesServiceDeleteFileResponseSuccess | filesServiceDeleteFileResponseError)

export const getFilesServiceDeleteFileUrl = (fileId: string,) => {




  return `/api/api/files/${fileId}`
}

<<<<<<< HEAD
/**
 * Deletes the file from storage and removes its metadata from the system.
 * @summary Delete a file
 */
export const deleteFile = async (fileId: string, options?: RequestInit): Promise<deleteFileResponse> => {
=======
export const filesServiceDeleteFile = async (fileId: string, options?: RequestInit): Promise<filesServiceDeleteFileResponse> => {
>>>>>>> main

  const res = await fetch(getFilesServiceDeleteFileUrl(fileId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

<<<<<<< HEAD
  const data: deleteFileResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteFileResponse
=======
  const data: filesServiceDeleteFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as filesServiceDeleteFileResponse
>>>>>>> main
}




export const getFilesServiceDeleteFileMutationOptions = <TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesServiceDeleteFile>>, TError,{fileId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filesServiceDeleteFile>>, TError,{fileId: string}, TContext> => {

const mutationKey = ['filesServiceDeleteFile'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesServiceDeleteFile>>, {fileId: string}> = (props) => {
          const {fileId} = props ?? {};

          return  filesServiceDeleteFile(fileId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesServiceDeleteFileMutationResult = NonNullable<Awaited<ReturnType<typeof filesServiceDeleteFile>>>

    export type FilesServiceDeleteFileMutationError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500

    export const useFilesServiceDeleteFile = <TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesServiceDeleteFile>>, TError,{fileId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesServiceDeleteFile>>,
        TError,
        {fileId: string},
        TContext
      > => {
<<<<<<< HEAD
      return useMutation(getDeleteFileMutationOptions(options), queryClient);
    }
    export type getFileUploadPresignedUrlResponse200 = {
  data: FileUploadResponseResponse
  status: 200
}

export type getFileUploadPresignedUrlResponse400 = {
  data: ErrorResponseResponse
  status: 400
}

export type getFileUploadPresignedUrlResponse500 = {
  data: ErrorResponseResponse
  status: 500
}

export type getFileUploadPresignedUrlResponseSuccess = (getFileUploadPresignedUrlResponse200) & {
  headers: Headers;
};
export type getFileUploadPresignedUrlResponseError = (getFileUploadPresignedUrlResponse400 | getFileUploadPresignedUrlResponse500) & {
  headers: Headers;
};

export type getFileUploadPresignedUrlResponse = (getFileUploadPresignedUrlResponseSuccess | getFileUploadPresignedUrlResponseError)

export const getGetFileUploadPresignedUrlUrl = () => {




  return `/api/files`
}

/**
 * Returns a time-limited presigned S3 PUT URL to upload a file, along with any required fields for the upload
 * @summary Get presigned URL for file upload
 */
export const getFileUploadPresignedUrl = async (fileUpload: FileUpload, options?: RequestInit): Promise<getFileUploadPresignedUrlResponse> => {

  const res = await fetch(getGetFileUploadPresignedUrlUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      fileUpload,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getFileUploadPresignedUrlResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getFileUploadPresignedUrlResponse
}




export const getGetFileUploadPresignedUrlMutationOptions = <TError = ErrorResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getFileUploadPresignedUrl>>, TError,{data: FileUpload}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof getFileUploadPresignedUrl>>, TError,{data: FileUpload}, TContext> => {

const mutationKey = ['getFileUploadPresignedUrl'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getFileUploadPresignedUrl>>, {data: FileUpload}> = (props) => {
          const {data} = props ?? {};

          return  getFileUploadPresignedUrl(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetFileUploadPresignedUrlMutationResult = NonNullable<Awaited<ReturnType<typeof getFileUploadPresignedUrl>>>
    export type GetFileUploadPresignedUrlMutationBody = FileUpload
    export type GetFileUploadPresignedUrlMutationError = ErrorResponseResponse

    /**
 * @summary Get presigned URL for file upload
 */
export const useGetFileUploadPresignedUrl = <TError = ErrorResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getFileUploadPresignedUrl>>, TError,{data: FileUpload}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getFileUploadPresignedUrl>>,
        TError,
        {data: FileUpload},
        TContext
      > => {
      return useMutation(getGetFileUploadPresignedUrlMutationOptions(options), queryClient);
=======
      return useMutation(getFilesServiceDeleteFileMutationOptions(options), queryClient);
>>>>>>> main
    }
