/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Upload a new file to the system. The request should include the file's name, size in bytes, MIME type, and the file content itself. The response will include the unique identifier for the newly created file, along with its details and a URL for downloading it.
 */
export const FilesServiceCreateFileBody = zod.object({
  "size_bytes": zod.number(),
  "mime_type": zod.string()
})

/**
 * Get the details of a specific file by its unique identifier, including its name, size, type, and download URL.
 */
export const FilesServiceGetFileParams = zod.object({
  "fileId": zod.string().describe('The unique identifier of the file to retrieve')
})

export const FilesServiceGetFileResponse = zod.object({
  "id": zod.string(),
  "size_bytes": zod.number(),
  "mime_type": zod.string(),
  "url": zod.string()
})

/**
 * Delete a specific file from the system using its unique identifier. This operation will permanently remove the file and its associated data. The response will indicate whether the deletion was successful or if the file was not found.
 */
export const FilesServiceDeleteFileParams = zod.object({
  "fileId": zod.string().describe('The unique identifier of the file to delete')
})

