/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Returns a time-limited presigned S3 GET URL to download or view the file.
 * @summary Get presigned URL for file download
 */
export const GetFilePresignedUrlParams = zod.object({
  "file_id": zod.string().describe('Unique identifier of the file')
})

export const GetFilePresignedUrlResponse = zod.object({
  "file_id": zod.string().describe('Unique identifier of the file.'),
  "url": zod.string().url().describe('The URL where the file can be uploaded.')
})

/**
 * Deletes the file from storage and removes its metadata from the system.
 * @summary Delete a file
 */
export const DeleteFileParams = zod.object({
  "file_id": zod.string().describe('Unique identifier of the file')
})

/**
 * Returns a time-limited presigned S3 PUT URL to upload a file, along with any required fields for the upload
 * @summary Get presigned URL for file upload
 */
export const getFileUploadPresignedUrlBodySizeMax = 5;



export const GetFileUploadPresignedUrlBody = zod.object({
  "size": zod.number().max(getFileUploadPresignedUrlBodySizeMax).describe('Size of the file in megabytes (MB). Maximum allowed size is 5 MB.'),
  "mime_type": zod.string().describe('The MIME type of the uploaded file.')
})

export const GetFileUploadPresignedUrlResponse = zod.object({
  "file_id": zod.string().describe('Unique identifier of the file.'),
  "url": zod.string().url().describe('The URL where the file can be uploaded.')
})

