/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonErrorError400,
  CommonErrorError401,
  CommonErrorError404,
  CommonErrorError500,
  FilesCreateRequest,
  FilesCreateResponse,
  FilesResponse
} from '../model';





export type filesServiceCreateFileResponse201 = {
  data: FilesCreateResponse
  status: 201
}

export type filesServiceCreateFileResponse400 = {
  data: CommonErrorError400
  status: 400
}

export type filesServiceCreateFileResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type filesServiceCreateFileResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type filesServiceCreateFileResponseSuccess = (filesServiceCreateFileResponse201) & {
  headers: Headers;
};
export type filesServiceCreateFileResponseError = (filesServiceCreateFileResponse400 | filesServiceCreateFileResponse401 | filesServiceCreateFileResponse500) & {
  headers: Headers;
};

export type filesServiceCreateFileResponse = (filesServiceCreateFileResponseSuccess | filesServiceCreateFileResponseError)

export const getFilesServiceCreateFileUrl = () => {




  return `/api/files`
}

/**
 * Upload a new file to the system. The request should include the file's name, size in bytes, MIME type, and the file content itself. The response will include the unique identifier for the newly created file, along with its details and a URL for downloading it.
 */
export const filesServiceCreateFile = async (filesCreateRequest: FilesCreateRequest, options?: RequestInit): Promise<filesServiceCreateFileResponse> => {

  const res = await fetch(getFilesServiceCreateFileUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      filesCreateRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesServiceCreateFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as filesServiceCreateFileResponse
}




export const getFilesServiceCreateFileMutationOptions = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesServiceCreateFile>>, TError,{data: FilesCreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filesServiceCreateFile>>, TError,{data: FilesCreateRequest}, TContext> => {

const mutationKey = ['filesServiceCreateFile'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesServiceCreateFile>>, {data: FilesCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  filesServiceCreateFile(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesServiceCreateFileMutationResult = NonNullable<Awaited<ReturnType<typeof filesServiceCreateFile>>>
    export type FilesServiceCreateFileMutationBody = FilesCreateRequest
    export type FilesServiceCreateFileMutationError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500

    export const useFilesServiceCreateFile = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesServiceCreateFile>>, TError,{data: FilesCreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesServiceCreateFile>>,
        TError,
        {data: FilesCreateRequest},
        TContext
      > => {
      return useMutation(getFilesServiceCreateFileMutationOptions(options), queryClient);
    }
    export type filesServiceGetFileResponse200 = {
  data: FilesResponse
  status: 200
}

export type filesServiceGetFileResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type filesServiceGetFileResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type filesServiceGetFileResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type filesServiceGetFileResponseSuccess = (filesServiceGetFileResponse200) & {
  headers: Headers;
};
export type filesServiceGetFileResponseError = (filesServiceGetFileResponse401 | filesServiceGetFileResponse404 | filesServiceGetFileResponse500) & {
  headers: Headers;
};

export type filesServiceGetFileResponse = (filesServiceGetFileResponseSuccess | filesServiceGetFileResponseError)

export const getFilesServiceGetFileUrl = (fileId: string,) => {




  return `/api/files/${fileId}`
}

/**
 * Get the details of a specific file by its unique identifier, including its name, size, type, and download URL.
 */
export const filesServiceGetFile = async (fileId: string, options?: RequestInit): Promise<filesServiceGetFileResponse> => {

  const res = await fetch(getFilesServiceGetFileUrl(fileId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesServiceGetFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as filesServiceGetFileResponse
}





export const getFilesServiceGetFileQueryKey = (fileId: string,) => {
    return [
    `/api/files/${fileId}`
    ] as const;
    }


export const getFilesServiceGetFileQueryOptions = <TData = Awaited<ReturnType<typeof filesServiceGetFile>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesServiceGetFileQueryKey(fileId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesServiceGetFile>>> = ({ signal }) => filesServiceGetFile(fileId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(fileId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesServiceGetFileQueryResult = NonNullable<Awaited<ReturnType<typeof filesServiceGetFile>>>
export type FilesServiceGetFileQueryError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500


export function useFilesServiceGetFile<TData = Awaited<ReturnType<typeof filesServiceGetFile>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesServiceGetFile>>,
          TError,
          Awaited<ReturnType<typeof filesServiceGetFile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesServiceGetFile<TData = Awaited<ReturnType<typeof filesServiceGetFile>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesServiceGetFile>>,
          TError,
          Awaited<ReturnType<typeof filesServiceGetFile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesServiceGetFile<TData = Awaited<ReturnType<typeof filesServiceGetFile>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesServiceGetFile<TData = Awaited<ReturnType<typeof filesServiceGetFile>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesServiceGetFileQueryOptions(fileId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type filesServiceDeleteFileResponse204 = {
  data: void
  status: 204
}

export type filesServiceDeleteFileResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type filesServiceDeleteFileResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type filesServiceDeleteFileResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type filesServiceDeleteFileResponseSuccess = (filesServiceDeleteFileResponse204) & {
  headers: Headers;
};
export type filesServiceDeleteFileResponseError = (filesServiceDeleteFileResponse401 | filesServiceDeleteFileResponse404 | filesServiceDeleteFileResponse500) & {
  headers: Headers;
};

export type filesServiceDeleteFileResponse = (filesServiceDeleteFileResponseSuccess | filesServiceDeleteFileResponseError)

export const getFilesServiceDeleteFileUrl = (fileId: string,) => {




  return `/api/files/${fileId}`
}

/**
 * Delete a specific file from the system using its unique identifier. This operation will permanently remove the file and its associated data. The response will indicate whether the deletion was successful or if the file was not found.
 */
export const filesServiceDeleteFile = async (fileId: string, options?: RequestInit): Promise<filesServiceDeleteFileResponse> => {

  const res = await fetch(getFilesServiceDeleteFileUrl(fileId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesServiceDeleteFileResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as filesServiceDeleteFileResponse
}




export const getFilesServiceDeleteFileMutationOptions = <TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesServiceDeleteFile>>, TError,{fileId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof filesServiceDeleteFile>>, TError,{fileId: string}, TContext> => {

const mutationKey = ['filesServiceDeleteFile'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesServiceDeleteFile>>, {fileId: string}> = (props) => {
          const {fileId} = props ?? {};

          return  filesServiceDeleteFile(fileId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FilesServiceDeleteFileMutationResult = NonNullable<Awaited<ReturnType<typeof filesServiceDeleteFile>>>

    export type FilesServiceDeleteFileMutationError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500

    export const useFilesServiceDeleteFile = <TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesServiceDeleteFile>>, TError,{fileId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesServiceDeleteFile>>,
        TError,
        {fileId: string},
        TContext
      > => {
      return useMutation(getFilesServiceDeleteFileMutationOptions(options), queryClient);
    }
    export type filesServiceGetFileContentResponse302 = {
  data: void
  status: 302
}

export type filesServiceGetFileContentResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type filesServiceGetFileContentResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type filesServiceGetFileContentResponse500 = {
  data: CommonErrorError500
  status: 500
}

;
export type filesServiceGetFileContentResponseError = (filesServiceGetFileContentResponse302 | filesServiceGetFileContentResponse401 | filesServiceGetFileContentResponse404 | filesServiceGetFileContentResponse500) & {
  headers: Headers;
};

export type filesServiceGetFileContentResponse = (filesServiceGetFileContentResponseError)

export const getFilesServiceGetFileContentUrl = (fileId: string,) => {




  return `/api/files/${fileId}/content`
}

/**
 * Get the content of a specific file by its unique identifier.
 */
export const filesServiceGetFileContent = async (fileId: string, options?: RequestInit): Promise<filesServiceGetFileContentResponse> => {

  const res = await fetch(getFilesServiceGetFileContentUrl(fileId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: filesServiceGetFileContentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as filesServiceGetFileContentResponse
}





export const getFilesServiceGetFileContentQueryKey = (fileId: string,) => {
    return [
    `/api/files/${fileId}/content`
    ] as const;
    }


export const getFilesServiceGetFileContentQueryOptions = <TData = Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError = void | CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesServiceGetFileContentQueryKey(fileId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesServiceGetFileContent>>> = ({ signal }) => filesServiceGetFileContent(fileId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(fileId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesServiceGetFileContentQueryResult = NonNullable<Awaited<ReturnType<typeof filesServiceGetFileContent>>>
export type FilesServiceGetFileContentQueryError = void | CommonErrorError401 | CommonErrorError404 | CommonErrorError500


export function useFilesServiceGetFileContent<TData = Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError = void | CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesServiceGetFileContent>>,
          TError,
          Awaited<ReturnType<typeof filesServiceGetFileContent>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesServiceGetFileContent<TData = Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError = void | CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesServiceGetFileContent>>,
          TError,
          Awaited<ReturnType<typeof filesServiceGetFileContent>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesServiceGetFileContent<TData = Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError = void | CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesServiceGetFileContent<TData = Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError = void | CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 fileId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesServiceGetFileContent>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesServiceGetFileContentQueryOptions(fileId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






