/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Create a new note with the specified details.
 */
export const NotesServiceCreateNoteBody = zod.object({
  "course_id": zod.string(),
  "title": zod.string(),
  "content": zod.string().optional()
})

/**
 * List all notes accessible to the authenticated user.
 */
export const NotesServiceListNotesParams = zod.object({
  "courseId": zod.string().describe('The unique identifier of the course to filter notes')
})

export const NotesServiceListNotesResponseItem = zod.object({
  "id": zod.string(),
  "course_id": zod.string(),
  "title": zod.string(),
  "created_by": zod.string(),
  "created_at": zod.string().datetime({"offset":true}),
  "updated_at": zod.string().datetime({"offset":true})
})
export const NotesServiceListNotesResponse = zod.array(NotesServiceListNotesResponseItem)

/**
 * Establish a WebSocket connection for real-time updates on a specific note.
 */
export const NotesServiceNoteWebSocketParams = zod.object({
  "noteId": zod.string().describe('The unique identifier of the note for WebSocket connection')
})

/**
 * Get details of a specific note by its ID.
 */
export const NotesServiceGetNoteParams = zod.object({
  "noteId": zod.string().describe('The unique identifier of the note')
})

export const NotesServiceGetNoteResponse = zod.object({
  "id": zod.string(),
  "course_id": zod.string(),
  "title": zod.string(),
  "created_by": zod.string(),
  "created_at": zod.string().datetime({"offset":true}),
  "updated_at": zod.string().datetime({"offset":true}),
  "content": zod.string().optional()
})

/**
 * Delete a specific note by its ID.
 */
export const NotesServiceDeleteNoteParams = zod.object({
  "noteId": zod.string().describe('The unique identifier of the note')
})

/**
 * Update details of a specific note by its ID.
 */
export const NotesServiceUpdateNoteParams = zod.object({
  "noteId": zod.string().describe('The unique identifier of the note')
})

export const NotesServiceUpdateNoteBody = zod.object({
  "title": zod.string().optional(),
  "content": zod.string().optional()
}).describe('The template for adding optional properties.')

export const NotesServiceUpdateNoteResponse = zod.object({
  "id": zod.string(),
  "course_id": zod.string(),
  "title": zod.string(),
  "created_by": zod.string(),
  "created_at": zod.string().datetime({"offset":true}),
  "updated_at": zod.string().datetime({"offset":true}),
  "content": zod.string().optional()
})

