/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonErrorError400,
  CommonErrorError401,
  CommonErrorError404,
  CommonErrorError500,
  NotesCreateRequest,
  NotesCreateResponse,
  NotesDetailResponse,
  NotesListResponse,
  NotesUpdateRequest,
  NotesUpdateResponse
} from '../model';





export type notesServiceCreateNoteResponse201 = {
  data: NotesCreateResponse
  status: 201
}

export type notesServiceCreateNoteResponse400 = {
  data: CommonErrorError400
  status: 400
}

export type notesServiceCreateNoteResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type notesServiceCreateNoteResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type notesServiceCreateNoteResponseSuccess = (notesServiceCreateNoteResponse201) & {
  headers: Headers;
};
export type notesServiceCreateNoteResponseError = (notesServiceCreateNoteResponse400 | notesServiceCreateNoteResponse401 | notesServiceCreateNoteResponse500) & {
  headers: Headers;
};

export type notesServiceCreateNoteResponse = (notesServiceCreateNoteResponseSuccess | notesServiceCreateNoteResponseError)

export const getNotesServiceCreateNoteUrl = () => {




  return `/api/notes`
}

/**
 * Create a new note with the specified details.
 */
export const notesServiceCreateNote = async (notesCreateRequest: NotesCreateRequest, options?: RequestInit): Promise<notesServiceCreateNoteResponse> => {

  const res = await fetch(getNotesServiceCreateNoteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      notesCreateRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notesServiceCreateNoteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notesServiceCreateNoteResponse
}




export const getNotesServiceCreateNoteMutationOptions = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesServiceCreateNote>>, TError,{data: NotesCreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof notesServiceCreateNote>>, TError,{data: NotesCreateRequest}, TContext> => {

const mutationKey = ['notesServiceCreateNote'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesServiceCreateNote>>, {data: NotesCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  notesServiceCreateNote(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesServiceCreateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof notesServiceCreateNote>>>
    export type NotesServiceCreateNoteMutationBody = NotesCreateRequest
    export type NotesServiceCreateNoteMutationError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500

    export const useNotesServiceCreateNote = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesServiceCreateNote>>, TError,{data: NotesCreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notesServiceCreateNote>>,
        TError,
        {data: NotesCreateRequest},
        TContext
      > => {
      return useMutation(getNotesServiceCreateNoteMutationOptions(options), queryClient);
    }
    export type notesServiceListNotesResponse200 = {
  data: NotesListResponse
  status: 200
}

export type notesServiceListNotesResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type notesServiceListNotesResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type notesServiceListNotesResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type notesServiceListNotesResponseSuccess = (notesServiceListNotesResponse200) & {
  headers: Headers;
};
export type notesServiceListNotesResponseError = (notesServiceListNotesResponse401 | notesServiceListNotesResponse404 | notesServiceListNotesResponse500) & {
  headers: Headers;
};

export type notesServiceListNotesResponse = (notesServiceListNotesResponseSuccess | notesServiceListNotesResponseError)

export const getNotesServiceListNotesUrl = (courseId: string,) => {




  return `/api/notes/l/${courseId}`
}

/**
 * List all notes accessible to the authenticated user.
 */
export const notesServiceListNotes = async (courseId: string, options?: RequestInit): Promise<notesServiceListNotesResponse> => {

  const res = await fetch(getNotesServiceListNotesUrl(courseId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notesServiceListNotesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notesServiceListNotesResponse
}





export const getNotesServiceListNotesQueryKey = (courseId: string,) => {
    return [
    `/api/notes/l/${courseId}`
    ] as const;
    }


export const getNotesServiceListNotesQueryOptions = <TData = Awaited<ReturnType<typeof notesServiceListNotes>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesServiceListNotes>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotesServiceListNotesQueryKey(courseId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notesServiceListNotes>>> = ({ signal }) => notesServiceListNotes(courseId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(courseId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notesServiceListNotes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotesServiceListNotesQueryResult = NonNullable<Awaited<ReturnType<typeof notesServiceListNotes>>>
export type NotesServiceListNotesQueryError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500


export function useNotesServiceListNotes<TData = Awaited<ReturnType<typeof notesServiceListNotes>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 courseId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesServiceListNotes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notesServiceListNotes>>,
          TError,
          Awaited<ReturnType<typeof notesServiceListNotes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotesServiceListNotes<TData = Awaited<ReturnType<typeof notesServiceListNotes>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesServiceListNotes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notesServiceListNotes>>,
          TError,
          Awaited<ReturnType<typeof notesServiceListNotes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotesServiceListNotes<TData = Awaited<ReturnType<typeof notesServiceListNotes>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesServiceListNotes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotesServiceListNotes<TData = Awaited<ReturnType<typeof notesServiceListNotes>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesServiceListNotes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotesServiceListNotesQueryOptions(courseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type notesServiceNoteWebSocketResponse204 = {
  data: void
  status: 204
}

export type notesServiceNoteWebSocketResponseSuccess = (notesServiceNoteWebSocketResponse204) & {
  headers: Headers;
};
;

export type notesServiceNoteWebSocketResponse = (notesServiceNoteWebSocketResponseSuccess)

export const getNotesServiceNoteWebSocketUrl = (noteId: string,) => {




  return `/api/notes/ws/${noteId}`
}

/**
 * Establish a WebSocket connection for real-time updates on a specific note.
 */
export const notesServiceNoteWebSocket = async (noteId: string, options?: RequestInit): Promise<notesServiceNoteWebSocketResponse> => {

  const res = await fetch(getNotesServiceNoteWebSocketUrl(noteId),
  {
    ...options,
    method: 'HEAD'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notesServiceNoteWebSocketResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as notesServiceNoteWebSocketResponse
}




export const getNotesServiceNoteWebSocketMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesServiceNoteWebSocket>>, TError,{noteId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof notesServiceNoteWebSocket>>, TError,{noteId: string}, TContext> => {

const mutationKey = ['notesServiceNoteWebSocket'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesServiceNoteWebSocket>>, {noteId: string}> = (props) => {
          const {noteId} = props ?? {};

          return  notesServiceNoteWebSocket(noteId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesServiceNoteWebSocketMutationResult = NonNullable<Awaited<ReturnType<typeof notesServiceNoteWebSocket>>>

    export type NotesServiceNoteWebSocketMutationError = unknown

    export const useNotesServiceNoteWebSocket = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesServiceNoteWebSocket>>, TError,{noteId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notesServiceNoteWebSocket>>,
        TError,
        {noteId: string},
        TContext
      > => {
      return useMutation(getNotesServiceNoteWebSocketMutationOptions(options), queryClient);
    }
    export type notesServiceGetNoteResponse200 = {
  data: NotesDetailResponse
  status: 200
}

export type notesServiceGetNoteResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type notesServiceGetNoteResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type notesServiceGetNoteResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type notesServiceGetNoteResponseSuccess = (notesServiceGetNoteResponse200) & {
  headers: Headers;
};
export type notesServiceGetNoteResponseError = (notesServiceGetNoteResponse401 | notesServiceGetNoteResponse404 | notesServiceGetNoteResponse500) & {
  headers: Headers;
};

export type notesServiceGetNoteResponse = (notesServiceGetNoteResponseSuccess | notesServiceGetNoteResponseError)

export const getNotesServiceGetNoteUrl = (noteId: string,) => {




  return `/api/notes/${noteId}`
}

/**
 * Get details of a specific note by its ID.
 */
export const notesServiceGetNote = async (noteId: string, options?: RequestInit): Promise<notesServiceGetNoteResponse> => {

  const res = await fetch(getNotesServiceGetNoteUrl(noteId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notesServiceGetNoteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notesServiceGetNoteResponse
}





export const getNotesServiceGetNoteQueryKey = (noteId: string,) => {
    return [
    `/api/notes/${noteId}`
    ] as const;
    }


export const getNotesServiceGetNoteQueryOptions = <TData = Awaited<ReturnType<typeof notesServiceGetNote>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesServiceGetNote>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotesServiceGetNoteQueryKey(noteId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notesServiceGetNote>>> = ({ signal }) => notesServiceGetNote(noteId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(noteId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notesServiceGetNote>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotesServiceGetNoteQueryResult = NonNullable<Awaited<ReturnType<typeof notesServiceGetNote>>>
export type NotesServiceGetNoteQueryError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500


export function useNotesServiceGetNote<TData = Awaited<ReturnType<typeof notesServiceGetNote>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 noteId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesServiceGetNote>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notesServiceGetNote>>,
          TError,
          Awaited<ReturnType<typeof notesServiceGetNote>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotesServiceGetNote<TData = Awaited<ReturnType<typeof notesServiceGetNote>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesServiceGetNote>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notesServiceGetNote>>,
          TError,
          Awaited<ReturnType<typeof notesServiceGetNote>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotesServiceGetNote<TData = Awaited<ReturnType<typeof notesServiceGetNote>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesServiceGetNote>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotesServiceGetNote<TData = Awaited<ReturnType<typeof notesServiceGetNote>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notesServiceGetNote>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotesServiceGetNoteQueryOptions(noteId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type notesServiceDeleteNoteResponse204 = {
  data: void
  status: 204
}

export type notesServiceDeleteNoteResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type notesServiceDeleteNoteResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type notesServiceDeleteNoteResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type notesServiceDeleteNoteResponseSuccess = (notesServiceDeleteNoteResponse204) & {
  headers: Headers;
};
export type notesServiceDeleteNoteResponseError = (notesServiceDeleteNoteResponse401 | notesServiceDeleteNoteResponse404 | notesServiceDeleteNoteResponse500) & {
  headers: Headers;
};

export type notesServiceDeleteNoteResponse = (notesServiceDeleteNoteResponseSuccess | notesServiceDeleteNoteResponseError)

export const getNotesServiceDeleteNoteUrl = (noteId: string,) => {




  return `/api/notes/${noteId}`
}

/**
 * Delete a specific note by its ID.
 */
export const notesServiceDeleteNote = async (noteId: string, options?: RequestInit): Promise<notesServiceDeleteNoteResponse> => {

  const res = await fetch(getNotesServiceDeleteNoteUrl(noteId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notesServiceDeleteNoteResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as notesServiceDeleteNoteResponse
}




export const getNotesServiceDeleteNoteMutationOptions = <TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesServiceDeleteNote>>, TError,{noteId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof notesServiceDeleteNote>>, TError,{noteId: string}, TContext> => {

const mutationKey = ['notesServiceDeleteNote'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesServiceDeleteNote>>, {noteId: string}> = (props) => {
          const {noteId} = props ?? {};

          return  notesServiceDeleteNote(noteId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesServiceDeleteNoteMutationResult = NonNullable<Awaited<ReturnType<typeof notesServiceDeleteNote>>>

    export type NotesServiceDeleteNoteMutationError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500

    export const useNotesServiceDeleteNote = <TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesServiceDeleteNote>>, TError,{noteId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notesServiceDeleteNote>>,
        TError,
        {noteId: string},
        TContext
      > => {
      return useMutation(getNotesServiceDeleteNoteMutationOptions(options), queryClient);
    }
    export type notesServiceUpdateNoteResponse200 = {
  data: NotesUpdateResponse
  status: 200
}

export type notesServiceUpdateNoteResponse400 = {
  data: CommonErrorError400
  status: 400
}

export type notesServiceUpdateNoteResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type notesServiceUpdateNoteResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type notesServiceUpdateNoteResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type notesServiceUpdateNoteResponseSuccess = (notesServiceUpdateNoteResponse200) & {
  headers: Headers;
};
export type notesServiceUpdateNoteResponseError = (notesServiceUpdateNoteResponse400 | notesServiceUpdateNoteResponse401 | notesServiceUpdateNoteResponse404 | notesServiceUpdateNoteResponse500) & {
  headers: Headers;
};

export type notesServiceUpdateNoteResponse = (notesServiceUpdateNoteResponseSuccess | notesServiceUpdateNoteResponseError)

export const getNotesServiceUpdateNoteUrl = (noteId: string,) => {




  return `/api/notes/${noteId}`
}

/**
 * Update details of a specific note by its ID.
 */
export const notesServiceUpdateNote = async (noteId: string,
    notesUpdateRequest: NotesUpdateRequest, options?: RequestInit): Promise<notesServiceUpdateNoteResponse> => {

  const res = await fetch(getNotesServiceUpdateNoteUrl(noteId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      notesUpdateRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notesServiceUpdateNoteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notesServiceUpdateNoteResponse
}




export const getNotesServiceUpdateNoteMutationOptions = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesServiceUpdateNote>>, TError,{noteId: string;data: NotesUpdateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof notesServiceUpdateNote>>, TError,{noteId: string;data: NotesUpdateRequest}, TContext> => {

const mutationKey = ['notesServiceUpdateNote'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesServiceUpdateNote>>, {noteId: string;data: NotesUpdateRequest}> = (props) => {
          const {noteId,data} = props ?? {};

          return  notesServiceUpdateNote(noteId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesServiceUpdateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof notesServiceUpdateNote>>>
    export type NotesServiceUpdateNoteMutationBody = NotesUpdateRequest
    export type NotesServiceUpdateNoteMutationError = CommonErrorError400 | CommonErrorError401 | CommonErrorError404 | CommonErrorError500

    export const useNotesServiceUpdateNote = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesServiceUpdateNote>>, TError,{noteId: string;data: NotesUpdateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notesServiceUpdateNote>>,
        TError,
        {noteId: string;data: NotesUpdateRequest},
        TContext
      > => {
      return useMutation(getNotesServiceUpdateNoteMutationOptions(options), queryClient);
    }
