# https://taskfile.dev

version: '3'

includes:
  backend:
    taskfile: ./apps/backend/Taskfile.yml
    dir: ./apps/backend
  frontend:
    taskfile: ./apps/frontend/Taskfile.yml
    dir: ./apps/frontend
  embedder:
    taskfile: ./embedder/Taskfile.yml
    dir: ./embedder
  hocuspocus:
    taskfile: ./hocuspocus/Taskfile.yml
    dir: ./hocuspocus
  proto:
    taskfile: ./proto/Taskfile.yml
    dir: ./proto

tasks:
  buf-gen:
    desc: Generate code from protobuf definitions
    cmds:
      - rm -rf proto-gen
      - buf generate

  migrate-add:*:
    desc: Create a new database migration
    vars:
      MIGRATE_NAME: '{{index .MATCH 0}}'
    env:
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: ./apps/migration
    cmds:
      - goose -s create {{.MIGRATE_NAME}} sql
  
  migrate-up:
    desc: Apply all up database migration
    env:
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: ./apps/migration
    cmds:
      - GOOSE_DBSTRING=$DATABASE_URL goose up

  migrate-down:
    desc: Apply all down database migration
    env:
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: ./apps/migration
    cmds:
      - GOOSE_DBSTRING=$DATABASE_URL goose down

  format-sql:
    desc: Format all SQL files in the project
    cmds:
      - task: format-sql-migration
      - task: format-sql-query
  
  format-sql-migration:
    desc: Format all SQL files in the migration directory
    dir: ./apps/migration
    cmds:
      - for f in *.sql; do pg_format "$f" -o "$f" -t -W 1 --no-space-function; done

  format-sql-query:
    desc: Format all SQL files in the query directory
    dir: ./apps/backend/internal/store/sql
    cmds:
      - for f in *.sql; do pg_format "$f" -o "$f" -t -W 1 --no-space-function; done
  
  format-openapi:
    desc: OpenApi spec
    cmds:
      - npx -y openapi-format apps/openapi.yaml --configFile apps/oaf-config.yaml -o apps/openapi.yaml
      - cd scripts && uv run ./sort-openapi.py ../apps/openapi.yaml ../apps/openapi.yaml