# https://taskfile.dev

version: '3'

includes:
  backend:
    taskfile: ./apps/backend/Taskfile.yml
    dir: ./apps/backend
  frontend:
    taskfile: ./apps/frontend/Taskfile.yml
    dir: ./apps/frontend
  embedder:
    taskfile: ./embedder/Taskfile.yml
    dir: ./embedder
  hocuspocus:
    taskfile: ./hocuspocus/Taskfile.yml
    dir: ./hocuspocus
  proto:
    taskfile: ./proto/Taskfile.yml
    dir: ./proto
  ai:
    taskfile: ./ai/Taskfile.yml
    dir: ./ai
  openapi:
    taskfile: ./apps/openapi/Taskfile.yml
    dir: ./apps/openapi

tasks:
  default:
    desc: Run the default task
    deps:
      - proto:build-typescript
    cmds:
      - zellij --layout dev-layout.kdl

  create-bucket:
    desc: Create S3 bucket
    env:
      AWS_ACCESS_KEY_ID: $S3_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $S3_SECRET_ACCESS_KEY
    cmds:
      - mc alias set local "$S3_ENDPOINT" "$S3_ACCESS_KEY_ID" "$S3_SECRET_ACCESS_KEY"
      - mc mb local/$S3_BUCKET || true

  migrate-add:*:
    desc: Create a new database migration
    vars:
      MIGRATE_NAME: '{{index .MATCH 0}}'
    env:
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: ./apps/migration
    cmds:
      - goose -s create {{.MIGRATE_NAME}} sql
  
  migrate-up:
    desc: Apply all up database migration
    env:
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: ./apps/migration
    cmds:
      - GOOSE_DBSTRING=$DATABASE_URL goose up

  migrate-down:
    desc: Apply all down database migration
    env:
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: ./apps/migration
    cmds:
      - GOOSE_DBSTRING=$DATABASE_URL goose down

  format-sql:
    desc: Format all SQL files in the project
    cmds:
      - task: format-sql-migration
      - task: format-sql-query
  
  format-sql-migration:
    desc: Format all SQL files in the migration directory
    dir: ./apps/migration
    cmds:
      - for f in *.sql; do pg_format "$f" -o "$f" -t -W 1 --no-space-function; done

  format-sql-query:
    desc: Format all SQL files in the query directory
    dir: ./apps/backend/internal/store/sql
    cmds:
      - for f in *.sql; do pg_format "$f" -o "$f" -t -W 1 --no-space-function; done

  gen-all:
    desc: "Generate all code"
    cmds:
      - task: openapi
      - task: backend:gen-api
      - task: backend:gen-sql
      - task: frontend:gen-api