/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseResponse,
  ListWorkspacesParams,
  WorkspaceCreate,
  WorkspaceCreateResponseResponse,
  WorkspaceDetailResponseResponse,
  WorkspaceListResponseResponse,
  WorkspaceUpdate,
  WorkspaceUpdateResponseResponse
} from '../model';





/**
 * List all workspaces for the current user
 * @summary List workspaces
 */
export type listWorkspacesResponse200 = {
  data: WorkspaceListResponseResponse
  status: 200
}

export type listWorkspacesResponse400 = {
  data: ErrorResponseResponse
  status: 400
}

export type listWorkspacesResponse500 = {
  data: ErrorResponseResponse
  status: 500
}

export type listWorkspacesResponseSuccess = (listWorkspacesResponse200) & {
  headers: Headers;
};
export type listWorkspacesResponseError = (listWorkspacesResponse400 | listWorkspacesResponse500) & {
  headers: Headers;
};

export type listWorkspacesResponse = (listWorkspacesResponseSuccess | listWorkspacesResponseError)

export const getListWorkspacesUrl = (params?: ListWorkspacesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/workspaces?${stringifiedParams}` : `/workspaces`
}

export const listWorkspaces = async (params?: ListWorkspacesParams, options?: RequestInit): Promise<listWorkspacesResponse> => {
  
  const res = await fetch(getListWorkspacesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listWorkspacesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listWorkspacesResponse
}
  




export const getListWorkspacesQueryKey = (params?: ListWorkspacesParams,) => {
    return [
    `/workspaces`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListWorkspacesQueryOptions = <TData = Awaited<ReturnType<typeof listWorkspaces>>, TError = ErrorResponseResponse>(params?: ListWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWorkspacesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkspaces>>> = ({ signal }) => listWorkspaces(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListWorkspacesQueryResult = NonNullable<Awaited<ReturnType<typeof listWorkspaces>>>
export type ListWorkspacesQueryError = ErrorResponseResponse


export function useListWorkspaces<TData = Awaited<ReturnType<typeof listWorkspaces>>, TError = ErrorResponseResponse>(
 params: undefined |  ListWorkspacesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkspaces>>,
          TError,
          Awaited<ReturnType<typeof listWorkspaces>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWorkspaces<TData = Awaited<ReturnType<typeof listWorkspaces>>, TError = ErrorResponseResponse>(
 params?: ListWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkspaces>>,
          TError,
          Awaited<ReturnType<typeof listWorkspaces>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWorkspaces<TData = Awaited<ReturnType<typeof listWorkspaces>>, TError = ErrorResponseResponse>(
 params?: ListWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List workspaces
 */

export function useListWorkspaces<TData = Awaited<ReturnType<typeof listWorkspaces>>, TError = ErrorResponseResponse>(
 params?: ListWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkspaces>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListWorkspacesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new workspace
 * @summary Create a workspace
 */
export type createWorkspaceResponse201 = {
  data: WorkspaceCreateResponseResponse
  status: 201
}

export type createWorkspaceResponse400 = {
  data: ErrorResponseResponse
  status: 400
}

export type createWorkspaceResponse500 = {
  data: ErrorResponseResponse
  status: 500
}

export type createWorkspaceResponseSuccess = (createWorkspaceResponse201) & {
  headers: Headers;
};
export type createWorkspaceResponseError = (createWorkspaceResponse400 | createWorkspaceResponse500) & {
  headers: Headers;
};

export type createWorkspaceResponse = (createWorkspaceResponseSuccess | createWorkspaceResponseError)

export const getCreateWorkspaceUrl = () => {


  

  return `/workspaces`
}

export const createWorkspace = async (workspaceCreate: WorkspaceCreate, options?: RequestInit): Promise<createWorkspaceResponse> => {
  
  const res = await fetch(getCreateWorkspaceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      workspaceCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createWorkspaceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createWorkspaceResponse
}
  



export const getCreateWorkspaceMutationOptions = <TError = ErrorResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkspace>>, TError,{data: WorkspaceCreate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createWorkspace>>, TError,{data: WorkspaceCreate}, TContext> => {

const mutationKey = ['createWorkspace'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorkspace>>, {data: WorkspaceCreate}> = (props) => {
          const {data} = props ?? {};

          return  createWorkspace(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkspace>>>
    export type CreateWorkspaceMutationBody = WorkspaceCreate
    export type CreateWorkspaceMutationError = ErrorResponseResponse

    /**
 * @summary Create a workspace
 */
export const useCreateWorkspace = <TError = ErrorResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkspace>>, TError,{data: WorkspaceCreate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createWorkspace>>,
        TError,
        {data: WorkspaceCreate},
        TContext
      > => {
      return useMutation(getCreateWorkspaceMutationOptions(options), queryClient);
    }
    /**
 * Get details of a specific workspace
 * @summary Get workspace details
 */
export type getWorkspaceResponse200 = {
  data: WorkspaceDetailResponseResponse
  status: 200
}

export type getWorkspaceResponse404 = {
  data: ErrorResponseResponse
  status: 404
}

export type getWorkspaceResponse500 = {
  data: ErrorResponseResponse
  status: 500
}

export type getWorkspaceResponseSuccess = (getWorkspaceResponse200) & {
  headers: Headers;
};
export type getWorkspaceResponseError = (getWorkspaceResponse404 | getWorkspaceResponse500) & {
  headers: Headers;
};

export type getWorkspaceResponse = (getWorkspaceResponseSuccess | getWorkspaceResponseError)

export const getGetWorkspaceUrl = (id: string,) => {


  

  return `/workspaces/${id}`
}

export const getWorkspace = async (id: string, options?: RequestInit): Promise<getWorkspaceResponse> => {
  
  const res = await fetch(getGetWorkspaceUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getWorkspaceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWorkspaceResponse
}
  




export const getGetWorkspaceQueryKey = (id: string,) => {
    return [
    `/workspaces/${id}`
    ] as const;
    }

    
export const getGetWorkspaceQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspace>>, TError = ErrorResponseResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspaceQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspace>>> = ({ signal }) => getWorkspace(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkspaceQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspace>>>
export type GetWorkspaceQueryError = ErrorResponseResponse


export function useGetWorkspace<TData = Awaited<ReturnType<typeof getWorkspace>>, TError = ErrorResponseResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspace>>,
          TError,
          Awaited<ReturnType<typeof getWorkspace>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkspace<TData = Awaited<ReturnType<typeof getWorkspace>>, TError = ErrorResponseResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspace>>,
          TError,
          Awaited<ReturnType<typeof getWorkspace>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkspace<TData = Awaited<ReturnType<typeof getWorkspace>>, TError = ErrorResponseResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get workspace details
 */

export function useGetWorkspace<TData = Awaited<ReturnType<typeof getWorkspace>>, TError = ErrorResponseResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspace>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkspaceQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update an existing workspace
 * @summary Update workspace
 */
export type updateWorkspaceResponse200 = {
  data: WorkspaceUpdateResponseResponse
  status: 200
}

export type updateWorkspaceResponse400 = {
  data: ErrorResponseResponse
  status: 400
}

export type updateWorkspaceResponse404 = {
  data: ErrorResponseResponse
  status: 404
}

export type updateWorkspaceResponse500 = {
  data: ErrorResponseResponse
  status: 500
}

export type updateWorkspaceResponseSuccess = (updateWorkspaceResponse200) & {
  headers: Headers;
};
export type updateWorkspaceResponseError = (updateWorkspaceResponse400 | updateWorkspaceResponse404 | updateWorkspaceResponse500) & {
  headers: Headers;
};

export type updateWorkspaceResponse = (updateWorkspaceResponseSuccess | updateWorkspaceResponseError)

export const getUpdateWorkspaceUrl = (id: string,) => {


  

  return `/workspaces/${id}`
}

export const updateWorkspace = async (id: string,
    workspaceUpdate: WorkspaceUpdate, options?: RequestInit): Promise<updateWorkspaceResponse> => {
  
  const res = await fetch(getUpdateWorkspaceUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      workspaceUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateWorkspaceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateWorkspaceResponse
}
  



export const getUpdateWorkspaceMutationOptions = <TError = ErrorResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkspace>>, TError,{id: string;data: WorkspaceUpdate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateWorkspace>>, TError,{id: string;data: WorkspaceUpdate}, TContext> => {

const mutationKey = ['updateWorkspace'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateWorkspace>>, {id: string;data: WorkspaceUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updateWorkspace(id,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof updateWorkspace>>>
    export type UpdateWorkspaceMutationBody = WorkspaceUpdate
    export type UpdateWorkspaceMutationError = ErrorResponseResponse

    /**
 * @summary Update workspace
 */
export const useUpdateWorkspace = <TError = ErrorResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateWorkspace>>, TError,{id: string;data: WorkspaceUpdate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateWorkspace>>,
        TError,
        {id: string;data: WorkspaceUpdate},
        TContext
      > => {
      return useMutation(getUpdateWorkspaceMutationOptions(options), queryClient);
    }
    /**
 * Delete a workspace
 * @summary Delete workspace
 */
export type deleteWorkspaceResponse204 = {
  data: void
  status: 204
}

export type deleteWorkspaceResponseSuccess = (deleteWorkspaceResponse204) & {
  headers: Headers;
};
;

export type deleteWorkspaceResponse = (deleteWorkspaceResponseSuccess)

export const getDeleteWorkspaceUrl = (id: string,) => {


  

  return `/workspaces/${id}`
}

export const deleteWorkspace = async (id: string, options?: RequestInit): Promise<deleteWorkspaceResponse> => {
  
  const res = await fetch(getDeleteWorkspaceUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteWorkspaceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteWorkspaceResponse
}
  



export const getDeleteWorkspaceMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspace>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspace>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteWorkspace'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkspace>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteWorkspace(id,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspace>>>
    
    export type DeleteWorkspaceMutationError = unknown

    /**
 * @summary Delete workspace
 */
export const useDeleteWorkspace = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspace>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkspace>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteWorkspaceMutationOptions(options), queryClient);
    }
    