/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List workspaces
 */
export const getWorkspacesQueryPageDefault = 1;

export const getWorkspacesQueryLimitDefault = 20;
export const getWorkspacesQueryLimitMax = 100;

export const getWorkspacesQuerySortDefault = `id`;
export const getWorkspacesQueryOrderDefault = `asc`;

export const GetWorkspacesQueryParams = zod.object({
  "page": zod.number().min(1).default(getWorkspacesQueryPageDefault).describe('Page number (1-based)'),
  "limit": zod.number().min(1).max(getWorkspacesQueryLimitMax).default(getWorkspacesQueryLimitDefault).describe('Number of items per page'),
  "sort": zod.enum(['id', 'name', 'created_at']).default(getWorkspacesQuerySortDefault),
  "order": zod.enum(['asc', 'desc']).default(getWorkspacesQueryOrderDefault),
  "name": zod.string().optional().describe('Filter by workspace name (partial match)'),
  "owner_id": zod.number().optional().describe('Filter by owner user ID')
})

export const GetWorkspacesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "owner_id": zod.number().describe('ID of the owning user'),
  "owner": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded owner (present when expanded)'),
  "created_at": zod.string().datetime({})
})),
  "meta": zod.object({
  "page": zod.number(),
  "limit": zod.number(),
  "total": zod.number(),
  "total_pages": zod.number()
})
})

/**
 * @summary Create a workspace
 */
export const postWorkspacesBodyNameMax = 255;



export const PostWorkspacesBody = zod.object({
  "name": zod.string().min(1).max(postWorkspacesBodyNameMax),
  "owner_id": zod.number()
})

/**
 * @summary Get a workspace by ID
 */
export const GetWorkspacesWorkspaceIdParams = zod.object({
  "workspaceId": zod.string()
})

export const GetWorkspacesWorkspaceIdResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "owner_id": zod.number().describe('ID of the owning user'),
  "owner": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded owner (present when expanded)'),
  "created_at": zod.string().datetime({})
})

/**
 * @summary Update a workspace
 */
export const PatchWorkspacesWorkspaceIdParams = zod.object({
  "workspaceId": zod.string()
})

export const patchWorkspacesWorkspaceIdBodyNameMax = 255;



export const PatchWorkspacesWorkspaceIdBody = zod.object({
  "name": zod.string().min(1).max(patchWorkspacesWorkspaceIdBodyNameMax).optional()
})

export const PatchWorkspacesWorkspaceIdResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "owner_id": zod.number().describe('ID of the owning user'),
  "owner": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded owner (present when expanded)'),
  "created_at": zod.string().datetime({})
})

/**
 * @summary Delete a workspace
 */
export const DeleteWorkspacesWorkspaceIdParams = zod.object({
  "workspaceId": zod.string()
})

