/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CommonErrorError400,
  CommonErrorError401,
  CommonErrorError404,
  CommonErrorError500,
  WorkspacesCreateRequest,
  WorkspacesCreateResponse,
  WorkspacesListResponse,
  WorkspacesResponse,
  WorkspacesUpdateRequest
} from '../model';





export type workspacesServiceCreateWorkspaceResponse201 = {
  data: WorkspacesCreateResponse
  status: 201
}

export type workspacesServiceCreateWorkspaceResponse400 = {
  data: CommonErrorError400
  status: 400
}

export type workspacesServiceCreateWorkspaceResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type workspacesServiceCreateWorkspaceResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type workspacesServiceCreateWorkspaceResponseSuccess = (workspacesServiceCreateWorkspaceResponse201) & {
  headers: Headers;
};
export type workspacesServiceCreateWorkspaceResponseError = (workspacesServiceCreateWorkspaceResponse400 | workspacesServiceCreateWorkspaceResponse401 | workspacesServiceCreateWorkspaceResponse500) & {
  headers: Headers;
};

export type workspacesServiceCreateWorkspaceResponse = (workspacesServiceCreateWorkspaceResponseSuccess | workspacesServiceCreateWorkspaceResponseError)

export const getWorkspacesServiceCreateWorkspaceUrl = () => {




  return `/api/workspaces`
}

/**
 * Create a new workspace with the specified name.
 */
export const workspacesServiceCreateWorkspace = async (workspacesCreateRequest: WorkspacesCreateRequest, options?: RequestInit): Promise<workspacesServiceCreateWorkspaceResponse> => {

  const res = await fetch(getWorkspacesServiceCreateWorkspaceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      workspacesCreateRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: workspacesServiceCreateWorkspaceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as workspacesServiceCreateWorkspaceResponse
}




export const getWorkspacesServiceCreateWorkspaceMutationOptions = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesServiceCreateWorkspace>>, TError,{data: WorkspacesCreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof workspacesServiceCreateWorkspace>>, TError,{data: WorkspacesCreateRequest}, TContext> => {

const mutationKey = ['workspacesServiceCreateWorkspace'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspacesServiceCreateWorkspace>>, {data: WorkspacesCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  workspacesServiceCreateWorkspace(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspacesServiceCreateWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof workspacesServiceCreateWorkspace>>>
    export type WorkspacesServiceCreateWorkspaceMutationBody = WorkspacesCreateRequest
    export type WorkspacesServiceCreateWorkspaceMutationError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500

    export const useWorkspacesServiceCreateWorkspace = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesServiceCreateWorkspace>>, TError,{data: WorkspacesCreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspacesServiceCreateWorkspace>>,
        TError,
        {data: WorkspacesCreateRequest},
        TContext
      > => {
      return useMutation(getWorkspacesServiceCreateWorkspaceMutationOptions(options), queryClient);
    }
    export type workspacesServiceListWorkspacesResponse200 = {
  data: WorkspacesListResponse
  status: 200
}

export type workspacesServiceListWorkspacesResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type workspacesServiceListWorkspacesResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type workspacesServiceListWorkspacesResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type workspacesServiceListWorkspacesResponseSuccess = (workspacesServiceListWorkspacesResponse200) & {
  headers: Headers;
};
export type workspacesServiceListWorkspacesResponseError = (workspacesServiceListWorkspacesResponse401 | workspacesServiceListWorkspacesResponse404 | workspacesServiceListWorkspacesResponse500) & {
  headers: Headers;
};

export type workspacesServiceListWorkspacesResponse = (workspacesServiceListWorkspacesResponseSuccess | workspacesServiceListWorkspacesResponseError)

export const getWorkspacesServiceListWorkspacesUrl = () => {




  return `/api/workspaces`
}

/**
 * List all workspaces accessible to the authenticated user.
 */
export const workspacesServiceListWorkspaces = async ( options?: RequestInit): Promise<workspacesServiceListWorkspacesResponse> => {

  const res = await fetch(getWorkspacesServiceListWorkspacesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: workspacesServiceListWorkspacesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as workspacesServiceListWorkspacesResponse
}





export const getWorkspacesServiceListWorkspacesQueryKey = () => {
    return [
    `/api/workspaces`
    ] as const;
    }


export const getWorkspacesServiceListWorkspacesQueryOptions = <TData = Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorkspacesServiceListWorkspacesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>> = ({ signal }) => workspacesServiceListWorkspaces({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorkspacesServiceListWorkspacesQueryResult = NonNullable<Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>>
export type WorkspacesServiceListWorkspacesQueryError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500


export function useWorkspacesServiceListWorkspaces<TData = Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>,
          TError,
          Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspacesServiceListWorkspaces<TData = Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>,
          TError,
          Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspacesServiceListWorkspaces<TData = Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWorkspacesServiceListWorkspaces<TData = Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceListWorkspaces>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorkspacesServiceListWorkspacesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type workspacesServiceGetWorkspaceResponse200 = {
  data: WorkspacesResponse
  status: 200
}

export type workspacesServiceGetWorkspaceResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type workspacesServiceGetWorkspaceResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type workspacesServiceGetWorkspaceResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type workspacesServiceGetWorkspaceResponseSuccess = (workspacesServiceGetWorkspaceResponse200) & {
  headers: Headers;
};
export type workspacesServiceGetWorkspaceResponseError = (workspacesServiceGetWorkspaceResponse401 | workspacesServiceGetWorkspaceResponse404 | workspacesServiceGetWorkspaceResponse500) & {
  headers: Headers;
};

export type workspacesServiceGetWorkspaceResponse = (workspacesServiceGetWorkspaceResponseSuccess | workspacesServiceGetWorkspaceResponseError)

export const getWorkspacesServiceGetWorkspaceUrl = (workspaceId: string,) => {




  return `/api/workspaces/${workspaceId}`
}

/**
 * Get details of a specific workspace by its ID.
 */
export const workspacesServiceGetWorkspace = async (workspaceId: string, options?: RequestInit): Promise<workspacesServiceGetWorkspaceResponse> => {

  const res = await fetch(getWorkspacesServiceGetWorkspaceUrl(workspaceId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: workspacesServiceGetWorkspaceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as workspacesServiceGetWorkspaceResponse
}





export const getWorkspacesServiceGetWorkspaceQueryKey = (workspaceId: string,) => {
    return [
    `/api/workspaces/${workspaceId}`
    ] as const;
    }


export const getWorkspacesServiceGetWorkspaceQueryOptions = <TData = Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorkspacesServiceGetWorkspaceQueryKey(workspaceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>> = ({ signal }) => workspacesServiceGetWorkspace(workspaceId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorkspacesServiceGetWorkspaceQueryResult = NonNullable<Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>>
export type WorkspacesServiceGetWorkspaceQueryError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500


export function useWorkspacesServiceGetWorkspace<TData = Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 workspaceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>,
          TError,
          Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspacesServiceGetWorkspace<TData = Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>,
          TError,
          Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspacesServiceGetWorkspace<TData = Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWorkspacesServiceGetWorkspace<TData = Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspacesServiceGetWorkspace>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorkspacesServiceGetWorkspaceQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type workspacesServiceDeleteWorkspaceResponse204 = {
  data: void
  status: 204
}

export type workspacesServiceDeleteWorkspaceResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type workspacesServiceDeleteWorkspaceResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type workspacesServiceDeleteWorkspaceResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type workspacesServiceDeleteWorkspaceResponseSuccess = (workspacesServiceDeleteWorkspaceResponse204) & {
  headers: Headers;
};
export type workspacesServiceDeleteWorkspaceResponseError = (workspacesServiceDeleteWorkspaceResponse401 | workspacesServiceDeleteWorkspaceResponse404 | workspacesServiceDeleteWorkspaceResponse500) & {
  headers: Headers;
};

export type workspacesServiceDeleteWorkspaceResponse = (workspacesServiceDeleteWorkspaceResponseSuccess | workspacesServiceDeleteWorkspaceResponseError)

export const getWorkspacesServiceDeleteWorkspaceUrl = (workspaceId: string,) => {




  return `/api/workspaces/${workspaceId}`
}

/**
 * Delete a specific workspace by its ID.
 */
export const workspacesServiceDeleteWorkspace = async (workspaceId: string, options?: RequestInit): Promise<workspacesServiceDeleteWorkspaceResponse> => {

  const res = await fetch(getWorkspacesServiceDeleteWorkspaceUrl(workspaceId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: workspacesServiceDeleteWorkspaceResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as workspacesServiceDeleteWorkspaceResponse
}




export const getWorkspacesServiceDeleteWorkspaceMutationOptions = <TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesServiceDeleteWorkspace>>, TError,{workspaceId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof workspacesServiceDeleteWorkspace>>, TError,{workspaceId: string}, TContext> => {

const mutationKey = ['workspacesServiceDeleteWorkspace'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspacesServiceDeleteWorkspace>>, {workspaceId: string}> = (props) => {
          const {workspaceId} = props ?? {};

          return  workspacesServiceDeleteWorkspace(workspaceId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspacesServiceDeleteWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof workspacesServiceDeleteWorkspace>>>

    export type WorkspacesServiceDeleteWorkspaceMutationError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500

    export const useWorkspacesServiceDeleteWorkspace = <TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesServiceDeleteWorkspace>>, TError,{workspaceId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspacesServiceDeleteWorkspace>>,
        TError,
        {workspaceId: string},
        TContext
      > => {
      return useMutation(getWorkspacesServiceDeleteWorkspaceMutationOptions(options), queryClient);
    }
    export type workspacesServiceUpdateWorkspaceResponse200 = {
  data: WorkspacesResponse
  status: 200
}

export type workspacesServiceUpdateWorkspaceResponse400 = {
  data: CommonErrorError400
  status: 400
}

export type workspacesServiceUpdateWorkspaceResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type workspacesServiceUpdateWorkspaceResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type workspacesServiceUpdateWorkspaceResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type workspacesServiceUpdateWorkspaceResponseSuccess = (workspacesServiceUpdateWorkspaceResponse200) & {
  headers: Headers;
};
export type workspacesServiceUpdateWorkspaceResponseError = (workspacesServiceUpdateWorkspaceResponse400 | workspacesServiceUpdateWorkspaceResponse401 | workspacesServiceUpdateWorkspaceResponse404 | workspacesServiceUpdateWorkspaceResponse500) & {
  headers: Headers;
};

export type workspacesServiceUpdateWorkspaceResponse = (workspacesServiceUpdateWorkspaceResponseSuccess | workspacesServiceUpdateWorkspaceResponseError)

export const getWorkspacesServiceUpdateWorkspaceUrl = (workspaceId: string,) => {




  return `/api/workspaces/${workspaceId}`
}

/**
 * Update the name of a specific workspace by its ID.
 */
export const workspacesServiceUpdateWorkspace = async (workspaceId: string,
    workspacesUpdateRequest: WorkspacesUpdateRequest, options?: RequestInit): Promise<workspacesServiceUpdateWorkspaceResponse> => {

  const res = await fetch(getWorkspacesServiceUpdateWorkspaceUrl(workspaceId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      workspacesUpdateRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: workspacesServiceUpdateWorkspaceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as workspacesServiceUpdateWorkspaceResponse
}




export const getWorkspacesServiceUpdateWorkspaceMutationOptions = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesServiceUpdateWorkspace>>, TError,{workspaceId: string;data: WorkspacesUpdateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof workspacesServiceUpdateWorkspace>>, TError,{workspaceId: string;data: WorkspacesUpdateRequest}, TContext> => {

const mutationKey = ['workspacesServiceUpdateWorkspace'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspacesServiceUpdateWorkspace>>, {workspaceId: string;data: WorkspacesUpdateRequest}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  workspacesServiceUpdateWorkspace(workspaceId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspacesServiceUpdateWorkspaceMutationResult = NonNullable<Awaited<ReturnType<typeof workspacesServiceUpdateWorkspace>>>
    export type WorkspacesServiceUpdateWorkspaceMutationBody = WorkspacesUpdateRequest
    export type WorkspacesServiceUpdateWorkspaceMutationError = CommonErrorError400 | CommonErrorError401 | CommonErrorError404 | CommonErrorError500

    export const useWorkspacesServiceUpdateWorkspace = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspacesServiceUpdateWorkspace>>, TError,{workspaceId: string;data: WorkspacesUpdateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspacesServiceUpdateWorkspace>>,
        TError,
        {workspaceId: string;data: WorkspacesUpdateRequest},
        TContext
      > => {
      return useMutation(getWorkspacesServiceUpdateWorkspaceMutationOptions(options), queryClient);
    }
