/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Create a new workspace with the specified name.
 */
export const WorkspacesServiceCreateWorkspaceBody = zod.object({
  "name": zod.string()
})

/**
 * List all workspaces accessible to the authenticated user.
 */
export const WorkspacesServiceListWorkspacesResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "owner_id": zod.string(),
  "created_at": zod.string()
})
export const WorkspacesServiceListWorkspacesResponse = zod.array(WorkspacesServiceListWorkspacesResponseItem)

/**
 * Get details of a specific workspace by its ID.
 */
export const WorkspacesServiceGetWorkspaceParams = zod.object({
  "workspaceId": zod.string().describe('The unique identifier of the workspace')
})

export const WorkspacesServiceGetWorkspaceResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "owner_id": zod.string(),
  "created_at": zod.string()
})

/**
 * Delete a specific workspace by its ID.
 */
export const WorkspacesServiceDeleteWorkspaceParams = zod.object({
  "workspaceId": zod.string().describe('The unique identifier of the workspace')
})

/**
 * Update the name of a specific workspace by its ID.
 */
export const WorkspacesServiceUpdateWorkspaceParams = zod.object({
  "workspaceId": zod.string().describe('The unique identifier of the workspace')
})

export const WorkspacesServiceUpdateWorkspaceBody = zod.object({
  "name": zod.string()
})

export const WorkspacesServiceUpdateWorkspaceResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "owner_id": zod.string(),
  "created_at": zod.string()
})

