/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  GetWorkspacesParams,
  WorkspaceCreateRequest,
  WorkspaceListResponse,
  WorkspaceResponse,
  WorkspaceUpdateRequest
} from '../model';





/**
 * @summary List workspaces
 */
export type getWorkspacesResponse200 = {
  data: WorkspaceListResponse
  status: 200
}

export type getWorkspacesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getWorkspacesResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getWorkspacesResponseSuccess = (getWorkspacesResponse200) & {
  headers: Headers;
};
export type getWorkspacesResponseError = (getWorkspacesResponse401 | getWorkspacesResponse500) & {
  headers: Headers;
};

export type getWorkspacesResponse = (getWorkspacesResponseSuccess | getWorkspacesResponseError)

export const getGetWorkspacesUrl = (params?: GetWorkspacesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/workspaces?${stringifiedParams}` : `/workspaces`
}

export const getWorkspaces = async (params?: GetWorkspacesParams, options?: RequestInit): Promise<getWorkspacesResponse> => {
  
  const res = await fetch(getGetWorkspacesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getWorkspacesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWorkspacesResponse
}
  




export const getGetWorkspacesQueryKey = (params?: GetWorkspacesParams,) => {
    return [
    `/workspaces`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetWorkspacesQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspaces>>, TError = ErrorResponse>(params?: GetWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaces>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspacesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspaces>>> = ({ signal }) => getWorkspaces(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspaces>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkspacesQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaces>>>
export type GetWorkspacesQueryError = ErrorResponse


export function useGetWorkspaces<TData = Awaited<ReturnType<typeof getWorkspaces>>, TError = ErrorResponse>(
 params: undefined |  GetWorkspacesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaces>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaces>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaces>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkspaces<TData = Awaited<ReturnType<typeof getWorkspaces>>, TError = ErrorResponse>(
 params?: GetWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaces>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaces>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaces>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkspaces<TData = Awaited<ReturnType<typeof getWorkspaces>>, TError = ErrorResponse>(
 params?: GetWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaces>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List workspaces
 */

export function useGetWorkspaces<TData = Awaited<ReturnType<typeof getWorkspaces>>, TError = ErrorResponse>(
 params?: GetWorkspacesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaces>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkspacesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a workspace
 */
export type postWorkspacesResponse201 = {
  data: WorkspaceResponse
  status: 201
}

export type postWorkspacesResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postWorkspacesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type postWorkspacesResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postWorkspacesResponseSuccess = (postWorkspacesResponse201) & {
  headers: Headers;
};
export type postWorkspacesResponseError = (postWorkspacesResponse400 | postWorkspacesResponse401 | postWorkspacesResponse500) & {
  headers: Headers;
};

export type postWorkspacesResponse = (postWorkspacesResponseSuccess | postWorkspacesResponseError)

export const getPostWorkspacesUrl = () => {


  

  return `/workspaces`
}

export const postWorkspaces = async (workspaceCreateRequest: WorkspaceCreateRequest, options?: RequestInit): Promise<postWorkspacesResponse> => {
  
  const res = await fetch(getPostWorkspacesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      workspaceCreateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postWorkspacesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postWorkspacesResponse
}
  



export const getPostWorkspacesMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaces>>, TError,{data: WorkspaceCreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspaces>>, TError,{data: WorkspaceCreateRequest}, TContext> => {

const mutationKey = ['postWorkspaces'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspaces>>, {data: WorkspaceCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postWorkspaces(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspacesMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspaces>>>
    export type PostWorkspacesMutationBody = WorkspaceCreateRequest
    export type PostWorkspacesMutationError = ErrorResponse

    /**
 * @summary Create a workspace
 */
export const usePostWorkspaces = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaces>>, TError,{data: WorkspaceCreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspaces>>,
        TError,
        {data: WorkspaceCreateRequest},
        TContext
      > => {
      return useMutation(getPostWorkspacesMutationOptions(options), queryClient);
    }
    /**
 * @summary Get a workspace by ID
 */
export type getWorkspacesWorkspaceIdResponse200 = {
  data: WorkspaceResponse
  status: 200
}

export type getWorkspacesWorkspaceIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getWorkspacesWorkspaceIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getWorkspacesWorkspaceIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getWorkspacesWorkspaceIdResponseSuccess = (getWorkspacesWorkspaceIdResponse200) & {
  headers: Headers;
};
export type getWorkspacesWorkspaceIdResponseError = (getWorkspacesWorkspaceIdResponse401 | getWorkspacesWorkspaceIdResponse404 | getWorkspacesWorkspaceIdResponse500) & {
  headers: Headers;
};

export type getWorkspacesWorkspaceIdResponse = (getWorkspacesWorkspaceIdResponseSuccess | getWorkspacesWorkspaceIdResponseError)

export const getGetWorkspacesWorkspaceIdUrl = (workspaceId: string,) => {


  

  return `/workspaces/${workspaceId}`
}

export const getWorkspacesWorkspaceId = async (workspaceId: string, options?: RequestInit): Promise<getWorkspacesWorkspaceIdResponse> => {
  
  const res = await fetch(getGetWorkspacesWorkspaceIdUrl(workspaceId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getWorkspacesWorkspaceIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWorkspacesWorkspaceIdResponse
}
  




export const getGetWorkspacesWorkspaceIdQueryKey = (workspaceId: string,) => {
    return [
    `/workspaces/${workspaceId}`
    ] as const;
    }

    
export const getGetWorkspacesWorkspaceIdQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError = ErrorResponse>(workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspacesWorkspaceIdQueryKey(workspaceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>> = ({ signal }) => getWorkspacesWorkspaceId(workspaceId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkspacesWorkspaceIdQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>>
export type GetWorkspacesWorkspaceIdQueryError = ErrorResponse


export function useGetWorkspacesWorkspaceId<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError = ErrorResponse>(
 workspaceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>,
          TError,
          Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkspacesWorkspaceId<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError = ErrorResponse>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>,
          TError,
          Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkspacesWorkspaceId<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError = ErrorResponse>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a workspace by ID
 */

export function useGetWorkspacesWorkspaceId<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError = ErrorResponse>(
 workspaceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkspacesWorkspaceIdQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update a workspace
 */
export type patchWorkspacesWorkspaceIdResponse200 = {
  data: WorkspaceResponse
  status: 200
}

export type patchWorkspacesWorkspaceIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type patchWorkspacesWorkspaceIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type patchWorkspacesWorkspaceIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type patchWorkspacesWorkspaceIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type patchWorkspacesWorkspaceIdResponseSuccess = (patchWorkspacesWorkspaceIdResponse200) & {
  headers: Headers;
};
export type patchWorkspacesWorkspaceIdResponseError = (patchWorkspacesWorkspaceIdResponse400 | patchWorkspacesWorkspaceIdResponse401 | patchWorkspacesWorkspaceIdResponse404 | patchWorkspacesWorkspaceIdResponse500) & {
  headers: Headers;
};

export type patchWorkspacesWorkspaceIdResponse = (patchWorkspacesWorkspaceIdResponseSuccess | patchWorkspacesWorkspaceIdResponseError)

export const getPatchWorkspacesWorkspaceIdUrl = (workspaceId: string,) => {


  

  return `/workspaces/${workspaceId}`
}

export const patchWorkspacesWorkspaceId = async (workspaceId: string,
    workspaceUpdateRequest: WorkspaceUpdateRequest, options?: RequestInit): Promise<patchWorkspacesWorkspaceIdResponse> => {
  
  const res = await fetch(getPatchWorkspacesWorkspaceIdUrl(workspaceId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      workspaceUpdateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchWorkspacesWorkspaceIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchWorkspacesWorkspaceIdResponse
}
  



export const getPatchWorkspacesWorkspaceIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchWorkspacesWorkspaceId>>, TError,{workspaceId: string;data: WorkspaceUpdateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchWorkspacesWorkspaceId>>, TError,{workspaceId: string;data: WorkspaceUpdateRequest}, TContext> => {

const mutationKey = ['patchWorkspacesWorkspaceId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchWorkspacesWorkspaceId>>, {workspaceId: string;data: WorkspaceUpdateRequest}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  patchWorkspacesWorkspaceId(workspaceId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchWorkspacesWorkspaceIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchWorkspacesWorkspaceId>>>
    export type PatchWorkspacesWorkspaceIdMutationBody = WorkspaceUpdateRequest
    export type PatchWorkspacesWorkspaceIdMutationError = ErrorResponse

    /**
 * @summary Update a workspace
 */
export const usePatchWorkspacesWorkspaceId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchWorkspacesWorkspaceId>>, TError,{workspaceId: string;data: WorkspaceUpdateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchWorkspacesWorkspaceId>>,
        TError,
        {workspaceId: string;data: WorkspaceUpdateRequest},
        TContext
      > => {
      return useMutation(getPatchWorkspacesWorkspaceIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a workspace
 */
export type deleteWorkspacesWorkspaceIdResponse204 = {
  data: void
  status: 204
}

export type deleteWorkspacesWorkspaceIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteWorkspacesWorkspaceIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteWorkspacesWorkspaceIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type deleteWorkspacesWorkspaceIdResponseSuccess = (deleteWorkspacesWorkspaceIdResponse204) & {
  headers: Headers;
};
export type deleteWorkspacesWorkspaceIdResponseError = (deleteWorkspacesWorkspaceIdResponse401 | deleteWorkspacesWorkspaceIdResponse404 | deleteWorkspacesWorkspaceIdResponse500) & {
  headers: Headers;
};

export type deleteWorkspacesWorkspaceIdResponse = (deleteWorkspacesWorkspaceIdResponseSuccess | deleteWorkspacesWorkspaceIdResponseError)

export const getDeleteWorkspacesWorkspaceIdUrl = (workspaceId: string,) => {


  

  return `/workspaces/${workspaceId}`
}

export const deleteWorkspacesWorkspaceId = async (workspaceId: string, options?: RequestInit): Promise<deleteWorkspacesWorkspaceIdResponse> => {
  
  const res = await fetch(getDeleteWorkspacesWorkspaceIdUrl(workspaceId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteWorkspacesWorkspaceIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteWorkspacesWorkspaceIdResponse
}
  



export const getDeleteWorkspacesWorkspaceIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspacesWorkspaceId>>, TError,{workspaceId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspacesWorkspaceId>>, TError,{workspaceId: string}, TContext> => {

const mutationKey = ['deleteWorkspacesWorkspaceId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkspacesWorkspaceId>>, {workspaceId: string}> = (props) => {
          const {workspaceId} = props ?? {};

          return  deleteWorkspacesWorkspaceId(workspaceId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkspacesWorkspaceIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspacesWorkspaceId>>>
    
    export type DeleteWorkspacesWorkspaceIdMutationError = ErrorResponse

    /**
 * @summary Delete a workspace
 */
export const useDeleteWorkspacesWorkspaceId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspacesWorkspaceId>>, TError,{workspaceId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkspacesWorkspaceId>>,
        TError,
        {workspaceId: string},
        TContext
      > => {
      return useMutation(getDeleteWorkspacesWorkspaceIdMutationOptions(options), queryClient);
    }
    