/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * List all workspaces for the current user
 * @summary List workspaces
 */
export const listWorkspacesQueryLimitDefault = 20;
export const listWorkspacesQueryLimitMax = 100;



export const ListWorkspacesQueryParams = zod.object({
  "cursor": zod.string().optional().describe('Cursor for pagination (last seen item ID)'),
  "limit": zod.number().min(1).max(listWorkspacesQueryLimitMax).default(listWorkspacesQueryLimitDefault).describe('Number of items to return per page'),
  "owner_id": zod.string().optional().describe('Filter by owner ID')
})

export const ListWorkspacesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('Unique identifier.'),
  "name": zod.string().describe('Name of the workspace.'),
  "owner_id": zod.string().describe('ID of the user who owns the workspace authenticated session.'),
  "created_at": zod.string().datetime({})
})).optional(),
  "pagination": zod.object({
  "next_cursor": zod.string().optional(),
  "limit": zod.number().optional(),
  "has_more": zod.boolean().optional()
}).optional()
})

/**
 * Create a new workspace
 * @summary Create a workspace
 */
export const CreateWorkspaceBody = zod.object({
  "name": zod.string()
})

/**
 * Get details of a specific workspace
 * @summary Get workspace details
 */
export const GetWorkspaceParams = zod.object({
  "id": zod.string().describe('Unique identifier of the resource.')
})

export const GetWorkspaceResponse = zod.object({
  "id": zod.string().describe('Unique identifier.'),
  "name": zod.string().describe('Name of the workspace.'),
  "owner_id": zod.string().describe('ID of the user who owns the workspace authenticated session.'),
  "created_at": zod.string().datetime({})
})

/**
 * Update an existing workspace
 * @summary Update workspace
 */
export const UpdateWorkspaceParams = zod.object({
  "id": zod.string().describe('Unique identifier of the resource.')
})

export const UpdateWorkspaceBody = zod.object({
  "name": zod.string().optional()
})

export const UpdateWorkspaceResponse = zod.object({
  "id": zod.string().describe('Unique identifier.'),
  "name": zod.string().describe('Name of the workspace.'),
  "owner_id": zod.string().describe('ID of the user who owns the workspace authenticated session.'),
  "created_at": zod.string().datetime({})
})

/**
 * Delete a workspace
 * @summary Delete workspace
 */
export const DeleteWorkspaceParams = zod.object({
  "id": zod.string().describe('Unique identifier of the resource.')
})

