/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List all users
 */
export const getUsersQueryPageDefault = 1;

export const getUsersQueryLimitDefault = 20;
export const getUsersQueryLimitMax = 100;

export const getUsersQuerySortDefault = `id`;
export const getUsersQueryOrderDefault = `asc`;

export const GetUsersQueryParams = zod.object({
  "page": zod.number().min(1).default(getUsersQueryPageDefault).describe('Page number (1-based)'),
  "limit": zod.number().min(1).max(getUsersQueryLimitMax).default(getUsersQueryLimitDefault).describe('Number of items per page'),
  "sort": zod.enum(['id', 'username', 'email', 'created_at']).default(getUsersQuerySortDefault),
  "order": zod.enum(['asc', 'desc']).default(getUsersQueryOrderDefault),
  "username": zod.string().optional().describe('Filter by username (partial match)'),
  "email": zod.string().optional().describe('Filter by email (partial match)')
})

export const GetUsersResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
})),
  "meta": zod.object({
  "page": zod.number(),
  "limit": zod.number(),
  "total": zod.number(),
  "total_pages": zod.number()
})
})

/**
 * @summary Get a user by ID
 */
export const GetUsersUserIdParams = zod.object({
  "userId": zod.string()
})

export const GetUsersUserIdResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
})

/**
 * @summary Update a user
 */
export const PatchUsersUserIdParams = zod.object({
  "userId": zod.string()
})

export const patchUsersUserIdBodyUsernameMin = 3;
export const patchUsersUserIdBodyUsernameMax = 50;

export const patchUsersUserIdBodyPasswordMin = 8;



export const PatchUsersUserIdBody = zod.object({
  "username": zod.string().min(patchUsersUserIdBodyUsernameMin).max(patchUsersUserIdBodyUsernameMax).optional(),
  "email": zod.string().email().optional(),
  "password": zod.string().min(patchUsersUserIdBodyPasswordMin).optional()
})

export const PatchUsersUserIdResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
})

/**
 * @summary Delete a user
 */
export const DeleteUsersUserIdParams = zod.object({
  "userId": zod.string()
})

