# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  MIGRATION_DIR: ../migration

tasks:
  default:
    desc: Run 
    cmds:
      - go run cmd/main.go serve
      
  migrate-up:
    desc: Run database migrations
    cmds:
      - go run cmd/main.go migrate up {{.MIGRATION_DIR}}
  
  migrate-up-to:*:
    desc: Run database migrations up to a specific version
    vars:
      VERSION: '{{index .MATCH 0}}'
    cmds:
      - go run cmd/main.go migrate up-to {{.MIGRATION_DIR}} {{.VERSION}}

  migrate-down:
    desc: Rollback database migrations
    cmds:
      - go run cmd/main.go migrate down {{.MIGRATION_DIR}}
  
  migrate-down-to:*:
    desc: Rollback database migrations down to a specific version
    vars:
      VERSION: '{{index .MATCH 0}}'
    cmds:
      - go run cmd/main.go migrate down-to {{.MIGRATION_DIR}} {{.VERSION}}
  
  migrate-status:
    desc: Show database migration status
    cmds:
      - go run cmd/main.go migrate status {{.MIGRATION_DIR}}

  gen-api:
    desc: Generate API code using oapi-codegen
    vars:
      SCRIPT: https://gist.githubusercontent.com/hilmoo/e11a3076a6abfdb695f4ed6cb6b5e2a1/raw/b78831761b659f483a4f12241ff5eba54dc2fa72/transform_openapi.py
      OPENAPI_JSON: ../openapi.out.json
    cmds:
      - yq -o=json ../openapi.yaml > {{.OPENAPI_JSON}}
      - uv run {{.SCRIPT}} {{.OPENAPI_JSON}} {{.OPENAPI_JSON}}
      - go tool oapi-codegen -config=oapi-codegen.models.yml {{.OPENAPI_JSON}}
      - go tool oapi-codegen -config=oapi-codegen.server.yml {{.OPENAPI_JSON}}
      - sed -i 's/form:/query:/g' internal/gen/models/models.go
  
  gen-sql:
    desc: Generate SQL code using sqlc
    cmds:
      - rm -rf internal/gen/sqlc
      - sqlc generate -f sqlc.yaml
  
  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...