/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';





export type chatStreamMessagesResponse204 = {
  data: void
  status: 204
}

export type chatStreamMessagesResponseSuccess = (chatStreamMessagesResponse204) & {
  headers: Headers;
};
;

export type chatStreamMessagesResponse = (chatStreamMessagesResponseSuccess)

export const getChatStreamMessagesUrl = (chatId: string,) => {




  return `/api/chat/${chatId}/stream`
}

/**
 * Stream chat messages in real-time for the specified chat session.
 */
export const chatStreamMessages = async (chatId: string, options?: RequestInit): Promise<chatStreamMessagesResponse> => {

  const res = await fetch(getChatStreamMessagesUrl(chatId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: chatStreamMessagesResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as chatStreamMessagesResponse
}





export const getChatStreamMessagesQueryKey = (chatId: string,) => {
    return [
    `/api/chat/${chatId}/stream`
    ] as const;
    }


export const getChatStreamMessagesQueryOptions = <TData = Awaited<ReturnType<typeof chatStreamMessages>>, TError = unknown>(chatId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatStreamMessages>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChatStreamMessagesQueryKey(chatId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof chatStreamMessages>>> = ({ signal }) => chatStreamMessages(chatId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(chatId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof chatStreamMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ChatStreamMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof chatStreamMessages>>>
export type ChatStreamMessagesQueryError = unknown


export function useChatStreamMessages<TData = Awaited<ReturnType<typeof chatStreamMessages>>, TError = unknown>(
 chatId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatStreamMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatStreamMessages>>,
          TError,
          Awaited<ReturnType<typeof chatStreamMessages>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatStreamMessages<TData = Awaited<ReturnType<typeof chatStreamMessages>>, TError = unknown>(
 chatId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatStreamMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatStreamMessages>>,
          TError,
          Awaited<ReturnType<typeof chatStreamMessages>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatStreamMessages<TData = Awaited<ReturnType<typeof chatStreamMessages>>, TError = unknown>(
 chatId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatStreamMessages>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useChatStreamMessages<TData = Awaited<ReturnType<typeof chatStreamMessages>>, TError = unknown>(
 chatId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatStreamMessages>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getChatStreamMessagesQueryOptions(chatId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type chatSendMessageResponse204 = {
  data: void
  status: 204
}

export type chatSendMessageResponseSuccess = (chatSendMessageResponse204) & {
  headers: Headers;
};
;

export type chatSendMessageResponse = (chatSendMessageResponseSuccess)

export const getChatSendMessageUrl = (workspaceId: string,) => {




  return `/api/chat/${workspaceId}`
}

/**
 * Send a message to the chat associated with the specified workspace.
 */
export const chatSendMessage = async (workspaceId: string, options?: RequestInit): Promise<chatSendMessageResponse> => {

  const res = await fetch(getChatSendMessageUrl(workspaceId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: chatSendMessageResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as chatSendMessageResponse
}




export const getChatSendMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatSendMessage>>, TError,{workspaceId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof chatSendMessage>>, TError,{workspaceId: string}, TContext> => {

const mutationKey = ['chatSendMessage'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chatSendMessage>>, {workspaceId: string}> = (props) => {
          const {workspaceId} = props ?? {};

          return  chatSendMessage(workspaceId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChatSendMessageMutationResult = NonNullable<Awaited<ReturnType<typeof chatSendMessage>>>

    export type ChatSendMessageMutationError = unknown

    export const useChatSendMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatSendMessage>>, TError,{workspaceId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chatSendMessage>>,
        TError,
        {workspaceId: string},
        TContext
      > => {
      return useMutation(getChatSendMessageMutationOptions(options), queryClient);
    }
