/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * List all chats in a workspace.
 */
export const ChatListChatsParams = zod.object({
  "workspaceId": zod.string()
})

export const ChatListChatsResponseItem = zod.object({
  "id": zod.string(),
  "title": zod.string(),
  "created_at": zod.string()
})
export const ChatListChatsResponse = zod.array(ChatListChatsResponseItem)

/**
 * Get chat history for a specific s
 */
export const ChatGetChatHistoryParams = zod.object({
  "chatId": zod.string()
})

export const ChatGetChatHistoryResponseItem = zod.object({
  "id": zod.string(),
  "role": zod.string(),
  "text": zod.string(),
  "created_at": zod.string()
})
export const ChatGetChatHistoryResponse = zod.array(ChatGetChatHistoryResponseItem)

/**
 * Stream chat messages in real-time for the specified chat session.
 */
export const ChatStreamMessagesParams = zod.object({
  "chatId": zod.string().describe('The unique identifier of the chat session')
})

/**
 * Update the title of a chat session.
 */
export const ChatUpdateChatTitleParams = zod.object({
  "chatId": zod.string()
})

export const ChatUpdateChatTitleBody = zod.object({
  "title": zod.string()
})

export const ChatUpdateChatTitleResponse = zod.object({
  "title": zod.string()
})

/**
 * Send a message to the chat associated with the specified workspace.
 */
export const ChatSendMessageParams = zod.object({
  "workspaceId": zod.string().describe('The unique identifier of the workspace')
})

