/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Stream chat messages in real-time for the specified chat session.
 */
export const ChatStreamMessagesParams = zod.object({
  "chatId": zod.string().describe('The unique identifier of the chat session')
})

/**
 * Send a message to the chat associated with the specified workspace.
 */
export const ChatSendMessageParams = zod.object({
  "workspaceId": zod.string().describe('The unique identifier of the workspace')
})

