/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List courses in a workspace
 */
export const GetWorkspacesWorkspaceIdCoursesParams = zod.object({
  "workspaceId": zod.string()
})

export const getWorkspacesWorkspaceIdCoursesQueryPageDefault = 1;

export const getWorkspacesWorkspaceIdCoursesQueryLimitDefault = 20;
export const getWorkspacesWorkspaceIdCoursesQueryLimitMax = 100;

export const getWorkspacesWorkspaceIdCoursesQuerySortDefault = `id`;
export const getWorkspacesWorkspaceIdCoursesQueryOrderDefault = `asc`;

export const GetWorkspacesWorkspaceIdCoursesQueryParams = zod.object({
  "page": zod.number().min(1).default(getWorkspacesWorkspaceIdCoursesQueryPageDefault).describe('Page number (1-based)'),
  "limit": zod.number().min(1).max(getWorkspacesWorkspaceIdCoursesQueryLimitMax).default(getWorkspacesWorkspaceIdCoursesQueryLimitDefault).describe('Number of items per page'),
  "sort": zod.enum(['id', 'name', 'day', 'start_time']).default(getWorkspacesWorkspaceIdCoursesQuerySortDefault),
  "order": zod.enum(['asc', 'desc']).default(getWorkspacesWorkspaceIdCoursesQueryOrderDefault),
  "day": zod.enum(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']).optional().describe('Filter by day of week'),
  "name": zod.string().optional().describe('Filter by course name (partial match)'),
  "lecturer_name": zod.string().optional().describe('Filter by lecturer name (partial match)')
})

export const GetWorkspacesWorkspaceIdCoursesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "lecturer_name": zod.string().nullish(),
  "day": zod.enum(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']),
  "start_time": zod.string().time({}),
  "end_time": zod.string().time({}),
  "workspace_id": zod.number(),
  "workspace": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "owner_id": zod.number().describe('ID of the owning user'),
  "owner": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded owner (present when expanded)'),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded workspace (present when expanded)')
})),
  "meta": zod.object({
  "page": zod.number(),
  "limit": zod.number(),
  "total": zod.number(),
  "total_pages": zod.number()
})
})

/**
 * @summary Create a course in a workspace
 */
export const postCoursesBodyNameMax = 255;



export const PostCoursesBody = zod.object({
  "name": zod.string().min(1).max(postCoursesBodyNameMax),
  "lecturer_name": zod.string().nullish(),
  "day": zod.enum(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']),
  "start_time": zod.string().time({}),
  "end_time": zod.string().time({}).describe('Must be after start_time')
})

/**
 * @summary List all courses (across all workspaces)
 */
export const getCoursesQueryPageDefault = 1;

export const getCoursesQueryLimitDefault = 20;
export const getCoursesQueryLimitMax = 100;

export const getCoursesQuerySortDefault = `id`;
export const getCoursesQueryOrderDefault = `asc`;

export const GetCoursesQueryParams = zod.object({
  "page": zod.number().min(1).default(getCoursesQueryPageDefault).describe('Page number (1-based)'),
  "limit": zod.number().min(1).max(getCoursesQueryLimitMax).default(getCoursesQueryLimitDefault).describe('Number of items per page'),
  "workspace_id": zod.number().optional(),
  "day": zod.enum(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']).optional(),
  "sort": zod.enum(['id', 'name', 'day', 'start_time']).default(getCoursesQuerySortDefault),
  "order": zod.enum(['asc', 'desc']).default(getCoursesQueryOrderDefault)
})

export const GetCoursesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "lecturer_name": zod.string().nullish(),
  "day": zod.enum(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']),
  "start_time": zod.string().time({}),
  "end_time": zod.string().time({}),
  "workspace_id": zod.number(),
  "workspace": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "owner_id": zod.number().describe('ID of the owning user'),
  "owner": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded owner (present when expanded)'),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded workspace (present when expanded)')
})),
  "meta": zod.object({
  "page": zod.number(),
  "limit": zod.number(),
  "total": zod.number(),
  "total_pages": zod.number()
})
})

/**
 * @summary Get a course by ID
 */
export const GetCoursesCourseIdParams = zod.object({
  "courseId": zod.string()
})

export const GetCoursesCourseIdResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "lecturer_name": zod.string().nullish(),
  "day": zod.enum(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']),
  "start_time": zod.string().time({}),
  "end_time": zod.string().time({}),
  "workspace_id": zod.number(),
  "workspace": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "owner_id": zod.number().describe('ID of the owning user'),
  "owner": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded owner (present when expanded)'),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded workspace (present when expanded)')
})

/**
 * @summary Update a course
 */
export const PatchCoursesCourseIdParams = zod.object({
  "courseId": zod.string()
})

export const patchCoursesCourseIdBodyNameMax = 255;



export const PatchCoursesCourseIdBody = zod.object({
  "name": zod.string().min(1).max(patchCoursesCourseIdBodyNameMax).optional(),
  "lecturer_name": zod.string().nullish(),
  "day": zod.enum(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']).optional(),
  "start_time": zod.string().time({}).optional(),
  "end_time": zod.string().time({}).optional().describe('Must be after start_time')
})

export const PatchCoursesCourseIdResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "lecturer_name": zod.string().nullish(),
  "day": zod.enum(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']),
  "start_time": zod.string().time({}),
  "end_time": zod.string().time({}),
  "workspace_id": zod.number(),
  "workspace": zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "owner_id": zod.number().describe('ID of the owning user'),
  "owner": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded owner (present when expanded)'),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded workspace (present when expanded)')
})

/**
 * @summary Delete a course
 */
export const DeleteCoursesCourseIdParams = zod.object({
  "courseId": zod.string()
})

