/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Create a new course with the specified details.
 */
export const CoursesServiceCreateCourseBody = zod.object({
  "workspace_id": zod.string(),
  "title": zod.string(),
  "instructor": zod.string(),
  "credits": zod.number()
})

/**
 * List all courses accessible to the authenticated user.
 */
export const CoursesServiceListCoursesResponseItem = zod.object({
  "id": zod.string(),
  "workspace_id": zod.string(),
  "title": zod.string(),
  "instructor": zod.string(),
  "credits": zod.number(),
  "created_by": zod.string(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})
export const CoursesServiceListCoursesResponse = zod.array(CoursesServiceListCoursesResponseItem)

/**
 * Get details of a specific course by its ID.
 */
export const CoursesServiceGetCourseParams = zod.object({
  "courseId": zod.string().describe('The unique identifier of the course')
})

export const CoursesServiceGetCourseResponse = zod.object({
  "id": zod.string(),
  "workspace_id": zod.string(),
  "title": zod.string(),
  "instructor": zod.string(),
  "credits": zod.number(),
  "created_by": zod.string(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * Delete a specific course by its ID.
 */
export const CoursesServiceDeleteCourseParams = zod.object({
  "courseId": zod.string().describe('The unique identifier of the course')
})

/**
 * Update details of a specific course by its ID.
 */
export const CoursesServiceUpdateCourseParams = zod.object({
  "courseId": zod.string().describe('The unique identifier of the course')
})

export const CoursesServiceUpdateCourseBody = zod.object({
  "title": zod.string().optional(),
  "instructor": zod.string().optional(),
  "credits": zod.number().optional()
}).describe('The template for adding optional properties.')

export const CoursesServiceUpdateCourseResponse = zod.object({
  "id": zod.string(),
  "workspace_id": zod.string(),
  "title": zod.string(),
  "instructor": zod.string(),
  "credits": zod.number(),
  "created_by": zod.string(),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

