/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CourseCreateRequest,
  CourseListResponse,
  CourseResponse,
  CourseUpdateRequest,
  ErrorResponse,
  GetCoursesParams,
  GetWorkspacesWorkspaceIdCoursesParams
} from '../model';





/**
 * @summary List courses in a workspace
 */
export type getWorkspacesWorkspaceIdCoursesResponse200 = {
  data: CourseListResponse
  status: 200
}

export type getWorkspacesWorkspaceIdCoursesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getWorkspacesWorkspaceIdCoursesResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getWorkspacesWorkspaceIdCoursesResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getWorkspacesWorkspaceIdCoursesResponseSuccess = (getWorkspacesWorkspaceIdCoursesResponse200) & {
  headers: Headers;
};
export type getWorkspacesWorkspaceIdCoursesResponseError = (getWorkspacesWorkspaceIdCoursesResponse401 | getWorkspacesWorkspaceIdCoursesResponse404 | getWorkspacesWorkspaceIdCoursesResponse500) & {
  headers: Headers;
};

export type getWorkspacesWorkspaceIdCoursesResponse = (getWorkspacesWorkspaceIdCoursesResponseSuccess | getWorkspacesWorkspaceIdCoursesResponseError)

export const getGetWorkspacesWorkspaceIdCoursesUrl = (workspaceId: string,
    params?: GetWorkspacesWorkspaceIdCoursesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/workspaces/${workspaceId}/courses?${stringifiedParams}` : `/workspaces/${workspaceId}/courses`
}

export const getWorkspacesWorkspaceIdCourses = async (workspaceId: string,
    params?: GetWorkspacesWorkspaceIdCoursesParams, options?: RequestInit): Promise<getWorkspacesWorkspaceIdCoursesResponse> => {
  
  const res = await fetch(getGetWorkspacesWorkspaceIdCoursesUrl(workspaceId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getWorkspacesWorkspaceIdCoursesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWorkspacesWorkspaceIdCoursesResponse
}
  




export const getGetWorkspacesWorkspaceIdCoursesQueryKey = (workspaceId: string,
    params?: GetWorkspacesWorkspaceIdCoursesParams,) => {
    return [
    `/workspaces/${workspaceId}/courses`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetWorkspacesWorkspaceIdCoursesQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError = ErrorResponse>(workspaceId: string,
    params?: GetWorkspacesWorkspaceIdCoursesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspacesWorkspaceIdCoursesQueryKey(workspaceId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>> = ({ signal }) => getWorkspacesWorkspaceIdCourses(workspaceId,params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkspacesWorkspaceIdCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>>
export type GetWorkspacesWorkspaceIdCoursesQueryError = ErrorResponse


export function useGetWorkspacesWorkspaceIdCourses<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError = ErrorResponse>(
 workspaceId: string,
    params: undefined |  GetWorkspacesWorkspaceIdCoursesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>,
          TError,
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkspacesWorkspaceIdCourses<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError = ErrorResponse>(
 workspaceId: string,
    params?: GetWorkspacesWorkspaceIdCoursesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>,
          TError,
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkspacesWorkspaceIdCourses<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError = ErrorResponse>(
 workspaceId: string,
    params?: GetWorkspacesWorkspaceIdCoursesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List courses in a workspace
 */

export function useGetWorkspacesWorkspaceIdCourses<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError = ErrorResponse>(
 workspaceId: string,
    params?: GetWorkspacesWorkspaceIdCoursesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdCourses>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkspacesWorkspaceIdCoursesQueryOptions(workspaceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a course in a workspace
 */
export type postCoursesResponse201 = {
  data: CourseResponse
  status: 201
}

export type postCoursesResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postCoursesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type postCoursesResponse404 = {
  data: ErrorResponse
  status: 404
}

export type postCoursesResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postCoursesResponseSuccess = (postCoursesResponse201) & {
  headers: Headers;
};
export type postCoursesResponseError = (postCoursesResponse400 | postCoursesResponse401 | postCoursesResponse404 | postCoursesResponse500) & {
  headers: Headers;
};

export type postCoursesResponse = (postCoursesResponseSuccess | postCoursesResponseError)

export const getPostCoursesUrl = () => {


  

  return `/courses`
}

export const postCourses = async (courseCreateRequest: CourseCreateRequest, options?: RequestInit): Promise<postCoursesResponse> => {
  
  const res = await fetch(getPostCoursesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      courseCreateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postCoursesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postCoursesResponse
}
  



export const getPostCoursesMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCourses>>, TError,{data: CourseCreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postCourses>>, TError,{data: CourseCreateRequest}, TContext> => {

const mutationKey = ['postCourses'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCourses>>, {data: CourseCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postCourses(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostCoursesMutationResult = NonNullable<Awaited<ReturnType<typeof postCourses>>>
    export type PostCoursesMutationBody = CourseCreateRequest
    export type PostCoursesMutationError = ErrorResponse

    /**
 * @summary Create a course in a workspace
 */
export const usePostCourses = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCourses>>, TError,{data: CourseCreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postCourses>>,
        TError,
        {data: CourseCreateRequest},
        TContext
      > => {
      return useMutation(getPostCoursesMutationOptions(options), queryClient);
    }
    /**
 * @summary List all courses (across all workspaces)
 */
export type getCoursesResponse200 = {
  data: CourseListResponse
  status: 200
}

export type getCoursesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCoursesResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getCoursesResponseSuccess = (getCoursesResponse200) & {
  headers: Headers;
};
export type getCoursesResponseError = (getCoursesResponse401 | getCoursesResponse500) & {
  headers: Headers;
};

export type getCoursesResponse = (getCoursesResponseSuccess | getCoursesResponseError)

export const getGetCoursesUrl = (params?: GetCoursesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/courses?${stringifiedParams}` : `/courses`
}

export const getCourses = async (params?: GetCoursesParams, options?: RequestInit): Promise<getCoursesResponse> => {
  
  const res = await fetch(getGetCoursesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCoursesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCoursesResponse
}
  




export const getGetCoursesQueryKey = (params?: GetCoursesParams,) => {
    return [
    `/courses`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetCoursesQueryOptions = <TData = Awaited<ReturnType<typeof getCourses>>, TError = ErrorResponse>(params?: GetCoursesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourses>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCoursesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourses>>> = ({ signal }) => getCourses(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCourses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof getCourses>>>
export type GetCoursesQueryError = ErrorResponse


export function useGetCourses<TData = Awaited<ReturnType<typeof getCourses>>, TError = ErrorResponse>(
 params: undefined |  GetCoursesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCourses>>,
          TError,
          Awaited<ReturnType<typeof getCourses>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCourses<TData = Awaited<ReturnType<typeof getCourses>>, TError = ErrorResponse>(
 params?: GetCoursesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCourses>>,
          TError,
          Awaited<ReturnType<typeof getCourses>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCourses<TData = Awaited<ReturnType<typeof getCourses>>, TError = ErrorResponse>(
 params?: GetCoursesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourses>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all courses (across all workspaces)
 */

export function useGetCourses<TData = Awaited<ReturnType<typeof getCourses>>, TError = ErrorResponse>(
 params?: GetCoursesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourses>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCoursesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get a course by ID
 */
export type getCoursesCourseIdResponse200 = {
  data: CourseResponse
  status: 200
}

export type getCoursesCourseIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCoursesCourseIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getCoursesCourseIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getCoursesCourseIdResponseSuccess = (getCoursesCourseIdResponse200) & {
  headers: Headers;
};
export type getCoursesCourseIdResponseError = (getCoursesCourseIdResponse401 | getCoursesCourseIdResponse404 | getCoursesCourseIdResponse500) & {
  headers: Headers;
};

export type getCoursesCourseIdResponse = (getCoursesCourseIdResponseSuccess | getCoursesCourseIdResponseError)

export const getGetCoursesCourseIdUrl = (courseId: string,) => {


  

  return `/courses/${courseId}`
}

export const getCoursesCourseId = async (courseId: string, options?: RequestInit): Promise<getCoursesCourseIdResponse> => {
  
  const res = await fetch(getGetCoursesCourseIdUrl(courseId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCoursesCourseIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCoursesCourseIdResponse
}
  




export const getGetCoursesCourseIdQueryKey = (courseId: string,) => {
    return [
    `/courses/${courseId}`
    ] as const;
    }

    
export const getGetCoursesCourseIdQueryOptions = <TData = Awaited<ReturnType<typeof getCoursesCourseId>>, TError = ErrorResponse>(courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoursesCourseId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCoursesCourseIdQueryKey(courseId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoursesCourseId>>> = ({ signal }) => getCoursesCourseId(courseId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(courseId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCoursesCourseId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCoursesCourseIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCoursesCourseId>>>
export type GetCoursesCourseIdQueryError = ErrorResponse


export function useGetCoursesCourseId<TData = Awaited<ReturnType<typeof getCoursesCourseId>>, TError = ErrorResponse>(
 courseId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoursesCourseId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoursesCourseId>>,
          TError,
          Awaited<ReturnType<typeof getCoursesCourseId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCoursesCourseId<TData = Awaited<ReturnType<typeof getCoursesCourseId>>, TError = ErrorResponse>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoursesCourseId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoursesCourseId>>,
          TError,
          Awaited<ReturnType<typeof getCoursesCourseId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCoursesCourseId<TData = Awaited<ReturnType<typeof getCoursesCourseId>>, TError = ErrorResponse>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoursesCourseId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a course by ID
 */

export function useGetCoursesCourseId<TData = Awaited<ReturnType<typeof getCoursesCourseId>>, TError = ErrorResponse>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCoursesCourseId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCoursesCourseIdQueryOptions(courseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update a course
 */
export type patchCoursesCourseIdResponse200 = {
  data: CourseResponse
  status: 200
}

export type patchCoursesCourseIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type patchCoursesCourseIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type patchCoursesCourseIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type patchCoursesCourseIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type patchCoursesCourseIdResponseSuccess = (patchCoursesCourseIdResponse200) & {
  headers: Headers;
};
export type patchCoursesCourseIdResponseError = (patchCoursesCourseIdResponse400 | patchCoursesCourseIdResponse401 | patchCoursesCourseIdResponse404 | patchCoursesCourseIdResponse500) & {
  headers: Headers;
};

export type patchCoursesCourseIdResponse = (patchCoursesCourseIdResponseSuccess | patchCoursesCourseIdResponseError)

export const getPatchCoursesCourseIdUrl = (courseId: string,) => {


  

  return `/courses/${courseId}`
}

export const patchCoursesCourseId = async (courseId: string,
    courseUpdateRequest: CourseUpdateRequest, options?: RequestInit): Promise<patchCoursesCourseIdResponse> => {
  
  const res = await fetch(getPatchCoursesCourseIdUrl(courseId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      courseUpdateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchCoursesCourseIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchCoursesCourseIdResponse
}
  



export const getPatchCoursesCourseIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchCoursesCourseId>>, TError,{courseId: string;data: CourseUpdateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchCoursesCourseId>>, TError,{courseId: string;data: CourseUpdateRequest}, TContext> => {

const mutationKey = ['patchCoursesCourseId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchCoursesCourseId>>, {courseId: string;data: CourseUpdateRequest}> = (props) => {
          const {courseId,data} = props ?? {};

          return  patchCoursesCourseId(courseId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchCoursesCourseIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchCoursesCourseId>>>
    export type PatchCoursesCourseIdMutationBody = CourseUpdateRequest
    export type PatchCoursesCourseIdMutationError = ErrorResponse

    /**
 * @summary Update a course
 */
export const usePatchCoursesCourseId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchCoursesCourseId>>, TError,{courseId: string;data: CourseUpdateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchCoursesCourseId>>,
        TError,
        {courseId: string;data: CourseUpdateRequest},
        TContext
      > => {
      return useMutation(getPatchCoursesCourseIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a course
 */
export type deleteCoursesCourseIdResponse204 = {
  data: void
  status: 204
}

export type deleteCoursesCourseIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteCoursesCourseIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteCoursesCourseIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type deleteCoursesCourseIdResponseSuccess = (deleteCoursesCourseIdResponse204) & {
  headers: Headers;
};
export type deleteCoursesCourseIdResponseError = (deleteCoursesCourseIdResponse401 | deleteCoursesCourseIdResponse404 | deleteCoursesCourseIdResponse500) & {
  headers: Headers;
};

export type deleteCoursesCourseIdResponse = (deleteCoursesCourseIdResponseSuccess | deleteCoursesCourseIdResponseError)

export const getDeleteCoursesCourseIdUrl = (courseId: string,) => {


  

  return `/courses/${courseId}`
}

export const deleteCoursesCourseId = async (courseId: string, options?: RequestInit): Promise<deleteCoursesCourseIdResponse> => {
  
  const res = await fetch(getDeleteCoursesCourseIdUrl(courseId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteCoursesCourseIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteCoursesCourseIdResponse
}
  



export const getDeleteCoursesCourseIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCoursesCourseId>>, TError,{courseId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCoursesCourseId>>, TError,{courseId: string}, TContext> => {

const mutationKey = ['deleteCoursesCourseId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCoursesCourseId>>, {courseId: string}> = (props) => {
          const {courseId} = props ?? {};

          return  deleteCoursesCourseId(courseId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCoursesCourseIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCoursesCourseId>>>
    
    export type DeleteCoursesCourseIdMutationError = ErrorResponse

    /**
 * @summary Delete a course
 */
export const useDeleteCoursesCourseId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCoursesCourseId>>, TError,{courseId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCoursesCourseId>>,
        TError,
        {courseId: string},
        TContext
      > => {
      return useMutation(getDeleteCoursesCourseIdMutationOptions(options), queryClient);
    }
    