/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentStatus } from './assignmentStatus';

export interface AssignmentUpdateRequest {
  /**
   * @minLength 1
   * @maxLength 500
   */
  title?: string;
  /** @nullable */
  description?: string | null;
  deadline?: string;
  status?: AssignmentStatus;
}
