/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentsDetailResponse } from './assignmentsDetailResponse';

export type AssignmentsCreateResponse = AssignmentsDetailResponse;
