/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentsAssignmentStatus } from './assignmentsAssignmentStatus';

/**
 * The template for adding optional properties.
 */
export interface AssignmentsUpdateRequest {
  title?: string;
  status?: AssignmentsAssignmentStatus;
  position?: number;
  due_date?: string;
  color?: string;
  content?: string;
}
