/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */

export type AssignmentStatus = typeof AssignmentStatus[keyof typeof AssignmentStatus];


export const AssignmentStatus = {
  pending: 'pending',
  in_progress: 'in_progress',
  submitted: 'submitted',
  graded: 'graded',
  overdue: 'overdue',
} as const;
