/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentStatus } from './assignmentStatus';
import type { UserResponse } from './userResponse';

export interface AssignmentResponse {
  id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  deadline: string;
  status: AssignmentStatus;
  course_id: number;
  created_by: number;
  /** Embedded author (present when expanded) */
  author?: UserResponse;
  created_at: string;
  updated_at: string;
}
