/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentsAssignmentStatus } from './assignmentsAssignmentStatus';

export interface AssignmentsCreateRequest {
  course_id: string;
  title: string;
  status: AssignmentsAssignmentStatus;
  position: number;
  due_date: string;
  content?: string;
}
