/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

export type AuthGoogleCallbackParams = {
/**
 * The authorization code returned by Google after user authentication
 */
code: string;
/**
 * The state parameter returned by Google, used to maintain state between the request and callback
 */
state: string;
};
