/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

export interface AuthMeResponse {
  /** The unique identifier for the authenticated user */
  id: string;
  /** The email address of the authenticated user */
  email: string;
  /** The display name of the authenticated user */
  name: string;
  /** The URL of the authenticated user's avatar image */
  avatar_url: string;
}
