/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import type { ChatsChatSummary } from './chatsChatSummary';

export type ChatsChatListResponse = ChatsChatSummary[];
