/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import type { CommonErrorError } from './commonErrorError';

export type CommonErrorError404 = CommonErrorError;
