/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import type { CommonErrorErrorDetails } from './commonErrorErrorDetails';

/**
 * An error response with details about the failure.
 */
export interface CommonErrorError {
  /** A unique identifier for this error instance */
  id: string;
  /** A human-readable explanation of the error */
  reason: string;
  /** The HTTP status code associated with this error */
  status: string;
  /** An optional message providing more details about the error */
  message?: string;
  /** An optional machine-readable error code for programmatic handling */
  code: number;
  /** Optional additional details about the error, such as missing resources or validation errors */
  details?: CommonErrorErrorDetails;
}
