/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Optional additional details about the error, such as missing resources or validation errors
 */
export type CommonErrorErrorDetails = {[key: string]: string};
