/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

export interface CoursesResponse {
  readonly id: string;
  workspace_id: string;
  title: string;
  instructor: string;
  credits: number;
  readonly created_by: string;
  readonly created_at: string;
  readonly updated_at: string;
}
