/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { DayOfWeek } from './dayOfWeek';

export interface CourseUpdateRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  /** @nullable */
  lecturer_name?: string | null;
  day?: DayOfWeek;
  start_time?: string;
  /** Must be after start_time */
  end_time?: string;
}
