/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The template for adding optional properties.
 */
export interface CoursesUpdateRequest {
  title?: string;
  instructor?: string;
  credits?: number;
}
