/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

export interface CoursesCreateRequest {
  workspace_id: string;
  /** The title of the course */
  title: string;
  /** The instructor of the course */
  instructor: string;
  /** The number of credits for the course */
  credits?: number;
  /** The color associated with the course (hex color code) */
  color?: string;
  /** The position of the course for ordering purposes */
  position: number;
}
