/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from './userResponse';

export interface CourseNoteResponse {
  id: number;
  title: string;
  /** @nullable */
  content?: string | null;
  /**
   * Presigned URL to download the binary content blob. Null when no blob is stored.

   * @nullable
   */
  content_blob_url?: string | null;
  course_id: number;
  created_by: number;
  /** Embedded author (present when expanded) */
  author?: UserResponse;
  created_at: string;
  updated_at: string;
}
