/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { DayOfWeek } from './dayOfWeek';
import type { WorkspaceResponse } from './workspaceResponse';

export interface CourseResponse {
  id: number;
  name: string;
  /** @nullable */
  lecturer_name?: string | null;
  day: DayOfWeek;
  start_time: string;
  end_time: string;
  workspace_id: number;
  /** Embedded workspace (present when expanded) */
  workspace?: WorkspaceResponse;
}
