/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetails } from './errorDetails';

export interface Error {
  /** Error instance ID. */
  id: string;
  /** Human-readable reason. */
  reason: string;
  /** Status string (e.g., 'error'). */
  status: string;
  /** Error type. */
  message?: string;
  /** Application-specific error code. */
  code: number;
  /** Additional details about the error. */
  details?: ErrorDetails;
}
