/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */

export interface File {
  /** Unique identifier of the file. */
  file_id: string;
  /** The URL where the file can be uploaded. */
  url: string;
}
