/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { File } from './file';

/**
 * Presigned URL for file download
 */
export type FileGetResponseResponse = File;
