/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */

export interface FileUpload {
  file_name: string;
  /**
     * @minimum 1
     * @maximum 5242880
     */
  size_bytes: number;
  mime_type: string;
}
