/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */

export interface FileUpload {
  /**
     * Size of the file in megabytes (MB). Maximum allowed size is 5 MB.
     * @maximum 5
     */
  size: number;
  /** The MIME type of the uploaded file. */
  mime_type: string;
}
