/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */

export interface File {
  file_id: string;
  file_name: string;
  size_bytes?: number;
  mime_type: string;
  url: string;
  created_at?: string;
}
