/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */

export type GetAssignmentsSort = typeof GetAssignmentsSort[keyof typeof GetAssignmentsSort];


export const GetAssignmentsSort = {
  id: 'id',
  title: 'title',
  deadline: 'deadline',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const;
