/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentStatus } from './assignmentStatus';
import type { GetAssignmentsOrder } from './getAssignmentsOrder';
import type { GetAssignmentsSort } from './getAssignmentsSort';

export type GetAssignmentsParams = {
/**
 * Page number (1-based)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
sort?: GetAssignmentsSort;
order?: GetAssignmentsOrder;
status?: AssignmentStatus;
created_by?: number;
deadline_before?: string;
deadline_after?: string;
};
