/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { DayOfWeek } from './dayOfWeek';
import type { GetCoursesOrder } from './getCoursesOrder';
import type { GetCoursesSort } from './getCoursesSort';

export type GetCoursesParams = {
/**
 * Page number (1-based)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
workspace_id?: number;
day?: DayOfWeek;
sort?: GetCoursesSort;
order?: GetCoursesOrder;
};
