/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { GetNotesOrder } from './getNotesOrder';
import type { GetNotesSort } from './getNotesSort';

export type GetNotesParams = {
/**
 * Page number (1-based)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
sort?: GetNotesSort;
order?: GetNotesOrder;
/**
 * Filter by title (partial match)
 */
title?: string;
/**
 * Filter by creator user ID
 */
created_by?: number;
created_after?: string;
created_before?: string;
updated_after?: string;
};
