/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */

export type GetUsersSort = typeof GetUsersSort[keyof typeof GetUsersSort];


export const GetUsersSort = {
  id: 'id',
  username: 'username',
  email: 'email',
  created_at: 'created_at',
} as const;
