/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersOrder } from './getUsersOrder';
import type { GetUsersSort } from './getUsersSort';

export type GetUsersParams = {
/**
 * Page number (1-based)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
sort?: GetUsersSort;
order?: GetUsersOrder;
/**
 * Filter by username (partial match)
 */
username?: string;
/**
 * Filter by email (partial match)
 */
email?: string;
};
