/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */

export type GetWorkspacesWorkspaceIdCoursesSort = typeof GetWorkspacesWorkspaceIdCoursesSort[keyof typeof GetWorkspacesWorkspaceIdCoursesSort];


export const GetWorkspacesWorkspaceIdCoursesSort = {
  id: 'id',
  name: 'name',
  day: 'day',
  start_time: 'start_time',
} as const;
