/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { DayOfWeek } from './dayOfWeek';
import type { GetWorkspacesWorkspaceIdCoursesOrder } from './getWorkspacesWorkspaceIdCoursesOrder';
import type { GetWorkspacesWorkspaceIdCoursesSort } from './getWorkspacesWorkspaceIdCoursesSort';

export type GetWorkspacesWorkspaceIdCoursesParams = {
/**
 * Page number (1-based)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
sort?: GetWorkspacesWorkspaceIdCoursesSort;
order?: GetWorkspacesWorkspaceIdCoursesOrder;
/**
 * Filter by day of week
 */
day?: DayOfWeek;
/**
 * Filter by course name (partial match)
 */
name?: string;
/**
 * Filter by lecturer name (partial match)
 */
lecturer_name?: string;
};
