/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { GetWorkspacesOrder } from './getWorkspacesOrder';
import type { GetWorkspacesSort } from './getWorkspacesSort';

export type GetWorkspacesParams = {
/**
 * Page number (1-based)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 * @maximum 100
 */
limit?: number;
sort?: GetWorkspacesSort;
order?: GetWorkspacesOrder;
/**
 * Filter by workspace name (partial match)
 */
name?: string;
/**
 * Filter by owner user ID
 */
owner_id?: number;
};
