/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

export * from './assignmentsAssignmentStatus';
export * from './assignmentsCreateRequest';
export * from './assignmentsCreateResponse';
export * from './assignmentsDetailResponse';
export * from './assignmentsListResponse';
export * from './assignmentsResponse';
export * from './assignmentsUpdateRequest';
export * from './assignmentsUpdateResponse';
export * from './authGoogleCallbackParams';
export * from './authMeResponse';
export * from './commonErrorError';
export * from './commonErrorError400';
export * from './commonErrorError401';
export * from './commonErrorError404';
export * from './commonErrorError500';
export * from './commonErrorErrorDetails';
export * from './coursesCreateRequest';
export * from './coursesCreateResponse';
export * from './coursesListResponse';
export * from './coursesResponse';
export * from './coursesUpdateRequest';
export * from './filesCreateRequest';
export * from './filesCreateResponse';
export * from './filesResponse';
export * from './notesCreateRequest';
export * from './notesCreateResponse';
export * from './notesDetailResponse';
export * from './notesListResponse';
export * from './notesResponse';
export * from './notesUpdateRequest';
export * from './notesUpdateResponse';
export * from './workspacesCreateRequest';
export * from './workspacesCreateResponse';
export * from './workspacesListResponse';
export * from './workspacesResponse';
export * from './workspacesUpdateRequest';
