/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

<<<<<<< HEAD
export * from './authMeResponseResponse';
export * from './cursorParamParameter';
export * from './error';
export * from './errorDetails';
export * from './errorResponseResponse';
export * from './file';
export * from './fileGetResponseResponse';
export * from './fileUpload';
export * from './fileUploadResponseResponse';
export * from './handleGoogleOAuthCallbackParams';
export * from './limitParamParameter';
export * from './listPagesParams';
export * from './listPagesType';
export * from './listSessionsParams';
export * from './listWorkspacesParams';
export * from './pageAllProperties';
export * from './pageBase';
export * from './pageBaseCreate';
export * from './pageBaseCreateType';
export * from './pageBaseType';
export * from './pageBaseUpdate';
export * from './pageCreate';
export * from './pageDetail';
export * from './pageDetailResponseResponse';
export * from './pageListResponseResponse';
export * from './pagePropertiesAssignment';
export * from './pagePropertiesAssignmentStatus';
export * from './pagePropertiesAssignmentType';
export * from './pagePropertiesCourse';
export * from './pagePropertiesCourseType';
export * from './pagePropertiesFolder';
export * from './pagePropertiesFolderType';
export * from './pagePropertiesNote';
export * from './pagePropertiesNoteType';
export * from './pageSummary';
export * from './pageSummaryType';
export * from './pageUpdate';
export * from './pagination';
export * from './parentIdParamParameter';
export * from './session';
export * from './sessionDetailResponseResponse';
export * from './sessionListResponseResponse';
export * from './user';
export * from './workspace';
export * from './workspaceCreate';
export * from './workspaceCreateResponseResponse';
export * from './workspaceDetailResponseResponse';
export * from './workspaceIdParamParameter';
export * from './workspaceListResponseResponse';
export * from './workspaceUpdate';
export * from './workspaceUpdateResponseResponse';
=======
export * from './assignmentsAssignmentStatus';
export * from './assignmentsCreateRequest';
export * from './assignmentsCreateResponse';
export * from './assignmentsDetailResponse';
export * from './assignmentsListResponse';
export * from './assignmentsResponse';
export * from './assignmentsUpdateRequest';
export * from './assignmentsUpdateResponse';
export * from './authGoogleCallbackParams';
export * from './authMeResponse';
export * from './commonErrorError';
export * from './commonErrorError400';
export * from './commonErrorError401';
export * from './commonErrorError404';
export * from './commonErrorError500';
export * from './commonErrorErrorDetails';
export * from './coursesCreateRequest';
export * from './coursesCreateResponse';
export * from './coursesListResponse';
export * from './coursesResponse';
export * from './coursesUpdateRequest';
export * from './filesCreateRequest';
export * from './filesCreateResponse';
export * from './filesResponse';
export * from './notesCreateRequest';
export * from './notesCreateResponse';
export * from './notesDetailResponse';
export * from './notesListResponse';
export * from './notesResponse';
export * from './notesUpdateRequest';
export * from './notesUpdateResponse';
export * from './workspacesCreateRequest';
export * from './workspacesCreateResponse';
export * from './workspacesListResponse';
export * from './workspacesResponse';
export * from './workspacesUpdateRequest';
>>>>>>> main
