/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */

export * from './assignmentCreateRequest';
export * from './assignmentListResponse';
export * from './assignmentResponse';
export * from './assignmentStatus';
export * from './assignmentUpdateRequest';
export * from './badRequest';
export * from './conflict';
export * from './courseCreateRequest';
export * from './courseListResponse';
export * from './courseNoteCreateRequest';
export * from './courseNoteListResponse';
export * from './courseNoteResponse';
export * from './courseNoteUpdateRequest';
export * from './courseResponse';
export * from './courseUpdateRequest';
export * from './dayOfWeek';
export * from './errorResponse';
export * from './errorResponseDetails';
export * from './getAssignmentsOrder';
export * from './getAssignmentsParams';
export * from './getAssignmentsSort';
export * from './getCoursesOrder';
export * from './getCoursesParams';
export * from './getCoursesSort';
export * from './getNotesOrder';
export * from './getNotesParams';
export * from './getNotesSort';
export * from './getUsersOrder';
export * from './getUsersParams';
export * from './getUsersSort';
export * from './getWorkspacesOrder';
export * from './getWorkspacesParams';
export * from './getWorkspacesSort';
export * from './getWorkspacesWorkspaceIdCoursesOrder';
export * from './getWorkspacesWorkspaceIdCoursesParams';
export * from './getWorkspacesWorkspaceIdCoursesSort';
export * from './internalError';
export * from './loginRequest';
export * from './notFound';
export * from './paginationMeta';
export * from './unauthorized';
export * from './userListResponse';
export * from './userRegisterRequest';
export * from './userResponse';
export * from './userUpdateRequest';
export * from './workspaceCreateRequest';
export * from './workspaceListResponse';
export * from './workspaceResponse';
export * from './workspaceUpdateRequest';