/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { CursorParamParameter } from './cursorParamParameter';
import type { LimitParamParameter } from './limitParamParameter';

export type ListSessionsParams = {
/**
 * Cursor for pagination (last seen item ID)
 */
cursor?: CursorParamParameter;
/**
 * Number of items to return per page
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParamParameter;
};
