/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { CursorParamParameter } from './cursorParamParameter';
import type { LimitParamParameter } from './limitParamParameter';
import type { ListPagesType } from './listPagesType';
import type { ParentIdParamParameter } from './parentIdParamParameter';
import type { WorkspaceIdParamParameter } from './workspaceIdParamParameter';

export type ListPagesParams = {
/**
 * Cursor for pagination (last seen item ID)
 */
cursor?: CursorParamParameter;
/**
 * Number of items to return per page
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParamParameter;
/**
 * Filter by workspace ID
 */
workspace_id?: WorkspaceIdParamParameter;
/**
 * Filter by parent page ID
 */
parent_id?: ParentIdParamParameter;
/**
 * Filter by page type
 */
type?: ListPagesType;
};
