/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

export interface NotesResponse {
  readonly id: string;
  course_id: string;
  title: string;
  readonly created_by: string;
  readonly created_at: string;
  readonly updated_at: string;
}
