/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

export interface NotesCreateRequest {
  course_id: string;
  title: string;
  content?: string;
}
