/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { PagePropertiesCourseType } from './pagePropertiesCourseType';

export interface PagePropertiesCourse {
  subject?: string;
  instructor?: string;
  semester?: string;
  credits?: number;
  start_date?: string;
  end_date?: string;
  type: PagePropertiesCourseType;
}
