/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { PageBaseCreateType } from './pageBaseCreateType';

export interface PageBaseCreate {
  workspace_id: string;
  /** Folders can be nested under another folder. Courses can only be nested under folders. Assignments can only be nested under courses. Notes can be nested under folders, courses, or other notes. Only Assignments cannot be top-level pages. */
  parent_id?: string;
  /** For folders, it's the folder name. For courses, it's the course name. For assignments, it's the assignment name. For notes, it's the note title. */
  title: string;
  /** Icon representing the page, can be an emoji or a URL to an image. */
  icon?: string;
  /** The type of the page, which determines its properties and behavior. */
  type: PageBaseCreateType;
}
