/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { PageSummary } from './pageSummary';
import type { Pagination } from './pagination';

export type PageListResponseResponse = {
  data?: PageSummary[];
  pagination?: Pagination;
};
