/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { PageSummaryType } from './pageSummaryType';

export interface PageSummary {
  id?: string;
  title?: string;
  icon?: string;
  type?: PageSummaryType;
  parent_id?: string;
  workspace_id?: string;
  /** Number of child pages (for folders and courses) */
  children_count?: number;
  updated_at?: string;
}
