/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { PageDetail } from './pageDetail';

/**
 * Page details
 */
export type PageDetailResponseResponse = PageDetail;
