/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of the page, which determines its properties and behavior.
 */
export type PageBaseType = typeof PageBaseType[keyof typeof PageBaseType];


export const PageBaseType = {
  course: 'course',
  assignment: 'assignment',
  folder: 'folder',
  note: 'note',
} as const;
