/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { PagePropertiesAssignment } from './pagePropertiesAssignment';
import type { PagePropertiesCourse } from './pagePropertiesCourse';
import type { PagePropertiesFolder } from './pagePropertiesFolder';
import type { PagePropertiesNote } from './pagePropertiesNote';

export type PageAllProperties = PagePropertiesCourse | PagePropertiesAssignment | PagePropertiesFolder | PagePropertiesNote;
