/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import type { PagePropertiesFolderType } from './pagePropertiesFolderType';

export interface PagePropertiesFolder {
  color?: string;
  sort_by?: string;
  type: PagePropertiesFolderType;
}
