/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */

/**
 * User session
 */
export interface Session {
  /** User ID. */
  user_id: string;
  /** Session token (identifier). */
  id: string;
  expires_at: string;
  ip_address?: string;
  user_agent?: string;
  created_at: string;
}
