/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkspacesResponse } from './workspacesResponse';

export type WorkspacesCreateResponse = WorkspacesResponse;
