/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from './userResponse';

export interface WorkspaceResponse {
  id: number;
  name: string;
  /** ID of the owning user */
  owner_id: number;
  /** Embedded owner (present when expanded) */
  owner?: UserResponse;
  created_at: string;
}
