/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */

export interface WorkspacesResponse {
  id: string;
  name: string;
  owner_id: string;
  created_at: string;
}
