/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */

export interface Workspace {
  /** Unique identifier. */
  id: string;
  /** Name of the workspace. */
  name: string;
  /** ID of the user who owns the workspace authenticated session. */
  owner_id: string;
  created_at: string;
}
