/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import type { PaginationMeta } from './paginationMeta';
import type { WorkspaceResponse } from './workspaceResponse';

export interface WorkspaceListResponse {
  data: WorkspaceResponse[];
  meta: PaginationMeta;
}
