/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseResponse,
  ListPagesParams,
  PageCreate,
  PageDetailResponseResponse,
  PageListResponseResponse,
  PageUpdate
} from '../model';





/**
 * List all pages for the current user, with optional filtering by workspace, parent page, and type
 * @summary List pages
 */
export type listPagesResponse200 = {
  data: PageListResponseResponse
  status: 200
}

export type listPagesResponse400 = {
  data: ErrorResponseResponse
  status: 400
}

export type listPagesResponse500 = {
  data: ErrorResponseResponse
  status: 500
}

export type listPagesResponseSuccess = (listPagesResponse200) & {
  headers: Headers;
};
export type listPagesResponseError = (listPagesResponse400 | listPagesResponse500) & {
  headers: Headers;
};

export type listPagesResponse = (listPagesResponseSuccess | listPagesResponseError)

export const getListPagesUrl = (params: ListPagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pages?${stringifiedParams}` : `/pages`
}

export const listPages = async (params: ListPagesParams, options?: RequestInit): Promise<listPagesResponse> => {
  
  const res = await fetch(getListPagesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listPagesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listPagesResponse
}
  




export const getListPagesQueryKey = (params?: ListPagesParams,) => {
    return [
    `/pages`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListPagesQueryOptions = <TData = Awaited<ReturnType<typeof listPages>>, TError = ErrorResponseResponse>(params: ListPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPages>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPagesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPages>>> = ({ signal }) => listPages(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPagesQueryResult = NonNullable<Awaited<ReturnType<typeof listPages>>>
export type ListPagesQueryError = ErrorResponseResponse


export function useListPages<TData = Awaited<ReturnType<typeof listPages>>, TError = ErrorResponseResponse>(
 params: ListPagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPages>>,
          TError,
          Awaited<ReturnType<typeof listPages>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPages<TData = Awaited<ReturnType<typeof listPages>>, TError = ErrorResponseResponse>(
 params: ListPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPages>>,
          TError,
          Awaited<ReturnType<typeof listPages>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPages<TData = Awaited<ReturnType<typeof listPages>>, TError = ErrorResponseResponse>(
 params: ListPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPages>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List pages
 */

export function useListPages<TData = Awaited<ReturnType<typeof listPages>>, TError = ErrorResponseResponse>(
 params: ListPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPages>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPagesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new page (course, assignment, folder, or note)
 * @summary Create a page
 */
export type createPageResponse201 = {
  data: PageDetailResponseResponse
  status: 201
}

export type createPageResponse400 = {
  data: ErrorResponseResponse
  status: 400
}

export type createPageResponse500 = {
  data: ErrorResponseResponse
  status: 500
}

export type createPageResponseSuccess = (createPageResponse201) & {
  headers: Headers;
};
export type createPageResponseError = (createPageResponse400 | createPageResponse500) & {
  headers: Headers;
};

export type createPageResponse = (createPageResponseSuccess | createPageResponseError)

export const getCreatePageUrl = () => {


  

  return `/pages`
}

export const createPage = async (pageCreate: PageCreate, options?: RequestInit): Promise<createPageResponse> => {
  
  const res = await fetch(getCreatePageUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pageCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createPageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createPageResponse
}
  



export const getCreatePageMutationOptions = <TError = ErrorResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPage>>, TError,{data: PageCreate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createPage>>, TError,{data: PageCreate}, TContext> => {

const mutationKey = ['createPage'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPage>>, {data: PageCreate}> = (props) => {
          const {data} = props ?? {};

          return  createPage(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePageMutationResult = NonNullable<Awaited<ReturnType<typeof createPage>>>
    export type CreatePageMutationBody = PageCreate
    export type CreatePageMutationError = ErrorResponseResponse

    /**
 * @summary Create a page
 */
export const useCreatePage = <TError = ErrorResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPage>>, TError,{data: PageCreate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPage>>,
        TError,
        {data: PageCreate},
        TContext
      > => {
      return useMutation(getCreatePageMutationOptions(options), queryClient);
    }
    /**
 * Get details of a specific page
 * @summary Get page details
 */
export type getPageResponse200 = {
  data: PageDetailResponseResponse
  status: 200
}

export type getPageResponse404 = {
  data: ErrorResponseResponse
  status: 404
}

export type getPageResponse500 = {
  data: ErrorResponseResponse
  status: 500
}

export type getPageResponseSuccess = (getPageResponse200) & {
  headers: Headers;
};
export type getPageResponseError = (getPageResponse404 | getPageResponse500) & {
  headers: Headers;
};

export type getPageResponse = (getPageResponseSuccess | getPageResponseError)

export const getGetPageUrl = (id: string,) => {


  

  return `/pages/${id}`
}

export const getPage = async (id: string, options?: RequestInit): Promise<getPageResponse> => {
  
  const res = await fetch(getGetPageUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getPageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPageResponse
}
  




export const getGetPageQueryKey = (id: string,) => {
    return [
    `/pages/${id}`
    ] as const;
    }

    
export const getGetPageQueryOptions = <TData = Awaited<ReturnType<typeof getPage>>, TError = ErrorResponseResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPageQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPage>>> = ({ signal }) => getPage(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPageQueryResult = NonNullable<Awaited<ReturnType<typeof getPage>>>
export type GetPageQueryError = ErrorResponseResponse


export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = ErrorResponseResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPage>>,
          TError,
          Awaited<ReturnType<typeof getPage>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = ErrorResponseResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPage>>,
          TError,
          Awaited<ReturnType<typeof getPage>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = ErrorResponseResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get page details
 */

export function useGetPage<TData = Awaited<ReturnType<typeof getPage>>, TError = ErrorResponseResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPage>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPageQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update an existing page (course, assignment, folder, or note)
 * @summary Update page
 */
export type updatePageResponse200 = {
  data: PageDetailResponseResponse
  status: 200
}

export type updatePageResponse400 = {
  data: ErrorResponseResponse
  status: 400
}

export type updatePageResponse404 = {
  data: ErrorResponseResponse
  status: 404
}

export type updatePageResponse500 = {
  data: ErrorResponseResponse
  status: 500
}

export type updatePageResponseSuccess = (updatePageResponse200) & {
  headers: Headers;
};
export type updatePageResponseError = (updatePageResponse400 | updatePageResponse404 | updatePageResponse500) & {
  headers: Headers;
};

export type updatePageResponse = (updatePageResponseSuccess | updatePageResponseError)

export const getUpdatePageUrl = (id: string,) => {


  

  return `/pages/${id}`
}

export const updatePage = async (id: string,
    pageUpdate: PageUpdate, options?: RequestInit): Promise<updatePageResponse> => {
  
  const res = await fetch(getUpdatePageUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pageUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updatePageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updatePageResponse
}
  



export const getUpdatePageMutationOptions = <TError = ErrorResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePage>>, TError,{id: string;data: PageUpdate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updatePage>>, TError,{id: string;data: PageUpdate}, TContext> => {

const mutationKey = ['updatePage'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePage>>, {id: string;data: PageUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePage(id,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePageMutationResult = NonNullable<Awaited<ReturnType<typeof updatePage>>>
    export type UpdatePageMutationBody = PageUpdate
    export type UpdatePageMutationError = ErrorResponseResponse

    /**
 * @summary Update page
 */
export const useUpdatePage = <TError = ErrorResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePage>>, TError,{id: string;data: PageUpdate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePage>>,
        TError,
        {id: string;data: PageUpdate},
        TContext
      > => {
      return useMutation(getUpdatePageMutationOptions(options), queryClient);
    }
    /**
 * Delete a page (course, assignment, folder, or note)
 * @summary Delete page
 */
export type deletePageResponse204 = {
  data: void
  status: 204
}

export type deletePageResponseSuccess = (deletePageResponse204) & {
  headers: Headers;
};
;

export type deletePageResponse = (deletePageResponseSuccess)

export const getDeletePageUrl = (id: string,) => {


  

  return `/pages/${id}`
}

export const deletePage = async (id: string, options?: RequestInit): Promise<deletePageResponse> => {
  
  const res = await fetch(getDeletePageUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deletePageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deletePageResponse
}
  



export const getDeletePageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePage>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deletePage>>, TError,{id: string}, TContext> => {

const mutationKey = ['deletePage'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePage>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deletePage(id,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePageMutationResult = NonNullable<Awaited<ReturnType<typeof deletePage>>>
    
    export type DeletePageMutationError = unknown

    /**
 * @summary Delete page
 */
export const useDeletePage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePage>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePage>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeletePageMutationOptions(options), queryClient);
    }
    