/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * List all pages for the current user, with optional filtering by workspace, parent page, and type
 * @summary List pages
 */
export const listPagesQueryLimitDefault = 20;
export const listPagesQueryLimitMax = 100;

export const listPagesQueryTypeDefault = `folder`;

export const ListPagesQueryParams = zod.object({
  "cursor": zod.string().optional().describe('Cursor for pagination (last seen item ID)'),
  "limit": zod.number().min(1).max(listPagesQueryLimitMax).default(listPagesQueryLimitDefault).describe('Number of items to return per page'),
  "workspace_id": zod.string().optional().describe('Filter by workspace ID'),
  "parent_id": zod.string().optional().describe('Filter by parent page ID'),
  "type": zod.enum(['course', 'assignment', 'folder', 'note']).default(listPagesQueryTypeDefault).describe('Filter by page type')
})

export const listPagesResponseDataItemTwoPropertiesTwoStatusDefault = `todo`;

export const ListPagesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional().describe('Unique identifier of the page.'),
  "workspace_id": zod.string().optional().describe('ID of the workspace this page belongs to.'),
  "parent_id": zod.string().optional().describe('ID of the parent page, null if it\'s a top-level page.'),
  "title": zod.string().optional().describe('Title of the page.'),
  "icon": zod.string().optional().describe('Icon representing the page, can be an emoji or a URL to an image.'),
  "created_by": zod.string().optional().describe('ID of the user who created the page. authenticated session.'),
  "created_at": zod.string().datetime({}).optional().describe('Timestamp when the page was created.'),
  "updated_at": zod.string().datetime({}).optional().describe('Timestamp when the page was last updated.')
}).and(zod.object({
  "properties": zod.union([zod.object({
  "subject": zod.string().optional(),
  "instructor": zod.string().optional(),
  "semester": zod.string().optional(),
  "credits": zod.number().optional(),
  "start_date": zod.string().datetime({}).optional(),
  "end_date": zod.string().datetime({}).optional()
}),zod.object({
  "due_date": zod.string().datetime({}).optional(),
  "status": zod.enum(['todo', 'in_progress', 'done']).default(listPagesResponseDataItemTwoPropertiesTwoStatusDefault)
}),zod.object({
  "color": zod.string().optional(),
  "sort_by": zod.string().optional()
}),zod.object({
  "tags": zod.array(zod.string()).optional(),
  "cover_image": zod.string().url().optional()
})]).optional()
}))).optional(),
  "pagination": zod.object({
  "next_cursor": zod.string().optional(),
  "limit": zod.number().optional(),
  "has_more": zod.boolean().optional()
}).optional()
})

/**
 * Create a new page (course, assignment, folder, or note)
 * @summary Create a page
 */
export const createPageBodyTwoPropertiesTwoStatusDefault = `todo`;

export const CreatePageBody = zod.object({
  "workspace_id": zod.string(),
  "parent_id": zod.string().optional().describe('Folders can be nested under another folder. Courses can only be nested under folders. Assignments can only be nested under courses. Notes can be nested under folders, courses, or other notes. Only Assignments cannot be top-level pages.'),
  "title": zod.string().describe('For folders, it\'s the folder name. For courses, it\'s the course name. For assignments, it\'s the assignment name. For notes, it\'s the note title.'),
  "icon": zod.string().optional().describe('Icon representing the page, can be an emoji or a URL to an image.'),
  "type": zod.enum(['course', 'assignment', 'folder', 'note']).describe('The type of the page, which determines its properties and behavior.')
}).and(zod.object({
  "properties": zod.union([zod.object({
  "subject": zod.string().optional(),
  "instructor": zod.string().optional(),
  "semester": zod.string().optional(),
  "credits": zod.number().optional(),
  "start_date": zod.string().datetime({}).optional(),
  "end_date": zod.string().datetime({}).optional()
}),zod.object({
  "due_date": zod.string().datetime({}).optional(),
  "status": zod.enum(['todo', 'in_progress', 'done']).default(createPageBodyTwoPropertiesTwoStatusDefault)
}),zod.object({
  "color": zod.string().optional(),
  "sort_by": zod.string().optional()
}),zod.object({
  "tags": zod.array(zod.string()).optional(),
  "cover_image": zod.string().url().optional()
})]).optional()
}))

/**
 * Get details of a specific page
 * @summary Get page details
 */
export const GetPageParams = zod.object({
  "id": zod.string().describe('Unique identifier of the resource.')
})

export const getPageResponseTwoPropertiesTwoStatusDefault = `todo`;

export const GetPageResponse = zod.object({
  "id": zod.string().optional().describe('Unique identifier of the page.'),
  "workspace_id": zod.string().optional().describe('ID of the workspace this page belongs to.'),
  "parent_id": zod.string().optional().describe('ID of the parent page, null if it\'s a top-level page.'),
  "title": zod.string().optional().describe('Title of the page.'),
  "icon": zod.string().optional().describe('Icon representing the page, can be an emoji or a URL to an image.'),
  "created_by": zod.string().optional().describe('ID of the user who created the page. authenticated session.'),
  "created_at": zod.string().datetime({}).optional().describe('Timestamp when the page was created.'),
  "updated_at": zod.string().datetime({}).optional().describe('Timestamp when the page was last updated.')
}).and(zod.object({
  "properties": zod.union([zod.object({
  "subject": zod.string().optional(),
  "instructor": zod.string().optional(),
  "semester": zod.string().optional(),
  "credits": zod.number().optional(),
  "start_date": zod.string().datetime({}).optional(),
  "end_date": zod.string().datetime({}).optional()
}),zod.object({
  "due_date": zod.string().datetime({}).optional(),
  "status": zod.enum(['todo', 'in_progress', 'done']).default(getPageResponseTwoPropertiesTwoStatusDefault)
}),zod.object({
  "color": zod.string().optional(),
  "sort_by": zod.string().optional()
}),zod.object({
  "tags": zod.array(zod.string()).optional(),
  "cover_image": zod.string().url().optional()
})]).optional()
}))

/**
 * Update an existing page (course, assignment, folder, or note)
 * @summary Update page
 */
export const UpdatePageParams = zod.object({
  "id": zod.string().describe('Unique identifier of the resource.')
})

export const updatePageBodyTwoPropertiesTwoStatusDefault = `todo`;

export const UpdatePageBody = zod.object({
  "parent_id": zod.string().optional(),
  "title": zod.string().optional(),
  "icon": zod.string().optional()
}).and(zod.object({
  "properties": zod.union([zod.object({
  "subject": zod.string().optional(),
  "instructor": zod.string().optional(),
  "semester": zod.string().optional(),
  "credits": zod.number().optional(),
  "start_date": zod.string().datetime({}).optional(),
  "end_date": zod.string().datetime({}).optional()
}),zod.object({
  "due_date": zod.string().datetime({}).optional(),
  "status": zod.enum(['todo', 'in_progress', 'done']).default(updatePageBodyTwoPropertiesTwoStatusDefault)
}),zod.object({
  "color": zod.string().optional(),
  "sort_by": zod.string().optional()
}),zod.object({
  "tags": zod.array(zod.string()).optional(),
  "cover_image": zod.string().url().optional()
})]).optional()
}))

export const updatePageResponseTwoPropertiesTwoStatusDefault = `todo`;

export const UpdatePageResponse = zod.object({
  "id": zod.string().optional().describe('Unique identifier of the page.'),
  "workspace_id": zod.string().optional().describe('ID of the workspace this page belongs to.'),
  "parent_id": zod.string().optional().describe('ID of the parent page, null if it\'s a top-level page.'),
  "title": zod.string().optional().describe('Title of the page.'),
  "icon": zod.string().optional().describe('Icon representing the page, can be an emoji or a URL to an image.'),
  "created_by": zod.string().optional().describe('ID of the user who created the page. authenticated session.'),
  "created_at": zod.string().datetime({}).optional().describe('Timestamp when the page was created.'),
  "updated_at": zod.string().datetime({}).optional().describe('Timestamp when the page was last updated.')
}).and(zod.object({
  "properties": zod.union([zod.object({
  "subject": zod.string().optional(),
  "instructor": zod.string().optional(),
  "semester": zod.string().optional(),
  "credits": zod.number().optional(),
  "start_date": zod.string().datetime({}).optional(),
  "end_date": zod.string().datetime({}).optional()
}),zod.object({
  "due_date": zod.string().datetime({}).optional(),
  "status": zod.enum(['todo', 'in_progress', 'done']).default(updatePageResponseTwoPropertiesTwoStatusDefault)
}),zod.object({
  "color": zod.string().optional(),
  "sort_by": zod.string().optional()
}),zod.object({
  "tags": zod.array(zod.string()).optional(),
  "cover_image": zod.string().url().optional()
})]).optional()
}))

/**
 * Delete a page (course, assignment, folder, or note)
 * @summary Delete page
 */
export const DeletePageParams = zod.object({
  "id": zod.string().describe('Unique identifier of the resource.')
})

