/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseResponse,
  HandleGoogleOAuthCallbackParams
} from '../model';





/**
 * Initiates OAuth flow by redirecting to Google authorization endpoint
 * @summary Redirect to Google OAuth
 */
export type redirectToGoogleOAuthResponse302 = {
  data: void
  status: 302
}

;
export type redirectToGoogleOAuthResponseError = (redirectToGoogleOAuthResponse302) & {
  headers: Headers;
};

export type redirectToGoogleOAuthResponse = (redirectToGoogleOAuthResponseError)

export const getRedirectToGoogleOAuthUrl = () => {


  

  return `/auth/oauth/google`
}

export const redirectToGoogleOAuth = async ( options?: RequestInit): Promise<redirectToGoogleOAuthResponse> => {
  
  const res = await fetch(getRedirectToGoogleOAuthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: redirectToGoogleOAuthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as redirectToGoogleOAuthResponse
}
  




export const getRedirectToGoogleOAuthQueryKey = () => {
    return [
    `/auth/oauth/google`
    ] as const;
    }

    
export const getRedirectToGoogleOAuthQueryOptions = <TData = Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRedirectToGoogleOAuthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof redirectToGoogleOAuth>>> = ({ signal }) => redirectToGoogleOAuth({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RedirectToGoogleOAuthQueryResult = NonNullable<Awaited<ReturnType<typeof redirectToGoogleOAuth>>>
export type RedirectToGoogleOAuthQueryError = void


export function useRedirectToGoogleOAuth<TData = Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof redirectToGoogleOAuth>>,
          TError,
          Awaited<ReturnType<typeof redirectToGoogleOAuth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRedirectToGoogleOAuth<TData = Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof redirectToGoogleOAuth>>,
          TError,
          Awaited<ReturnType<typeof redirectToGoogleOAuth>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRedirectToGoogleOAuth<TData = Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Redirect to Google OAuth
 */

export function useRedirectToGoogleOAuth<TData = Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof redirectToGoogleOAuth>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRedirectToGoogleOAuthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Handles the callback from Google OAuth, exchanges code for session token, and redirects to frontend with session token
 * @summary Handle Google OAuth callback
 */
export type handleGoogleOAuthCallbackResponse307 = {
  data: void
  status: 307
}

export type handleGoogleOAuthCallbackResponse400 = {
  data: ErrorResponseResponse
  status: 400
}

;
export type handleGoogleOAuthCallbackResponseError = (handleGoogleOAuthCallbackResponse307 | handleGoogleOAuthCallbackResponse400) & {
  headers: Headers;
};

export type handleGoogleOAuthCallbackResponse = (handleGoogleOAuthCallbackResponseError)

export const getHandleGoogleOAuthCallbackUrl = (params: HandleGoogleOAuthCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/oauth/callback/google?${stringifiedParams}` : `/auth/oauth/callback/google`
}

export const handleGoogleOAuthCallback = async (params: HandleGoogleOAuthCallbackParams, options?: RequestInit): Promise<handleGoogleOAuthCallbackResponse> => {
  
  const res = await fetch(getHandleGoogleOAuthCallbackUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: handleGoogleOAuthCallbackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as handleGoogleOAuthCallbackResponse
}
  




export const getHandleGoogleOAuthCallbackQueryKey = (params?: HandleGoogleOAuthCallbackParams,) => {
    return [
    `/auth/oauth/callback/google`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getHandleGoogleOAuthCallbackQueryOptions = <TData = Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError = void | ErrorResponseResponse>(params: HandleGoogleOAuthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHandleGoogleOAuthCallbackQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof handleGoogleOAuthCallback>>> = ({ signal }) => handleGoogleOAuthCallback(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HandleGoogleOAuthCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof handleGoogleOAuthCallback>>>
export type HandleGoogleOAuthCallbackQueryError = void | ErrorResponseResponse


export function useHandleGoogleOAuthCallback<TData = Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError = void | ErrorResponseResponse>(
 params: HandleGoogleOAuthCallbackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleGoogleOAuthCallback>>,
          TError,
          Awaited<ReturnType<typeof handleGoogleOAuthCallback>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleGoogleOAuthCallback<TData = Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError = void | ErrorResponseResponse>(
 params: HandleGoogleOAuthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof handleGoogleOAuthCallback>>,
          TError,
          Awaited<ReturnType<typeof handleGoogleOAuthCallback>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHandleGoogleOAuthCallback<TData = Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError = void | ErrorResponseResponse>(
 params: HandleGoogleOAuthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Handle Google OAuth callback
 */

export function useHandleGoogleOAuthCallback<TData = Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError = void | ErrorResponseResponse>(
 params: HandleGoogleOAuthCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof handleGoogleOAuthCallback>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHandleGoogleOAuthCallbackQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




