/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthGoogleCallbackParams,
  AuthMeResponse,
  CommonErrorError401
} from '../model';





/**
 * Initiate the Google OAuth2 authentication flow by redirecting the user to Google's authorization endpoint.
 */
export type authGoogleRedirectResponse302 = {
  data: void
  status: 302
}

;
export type authGoogleRedirectResponseError = (authGoogleRedirectResponse302) & {
  headers: Headers;
};

export type authGoogleRedirectResponse = (authGoogleRedirectResponseError)

export const getAuthGoogleRedirectUrl = () => {




  return `/api/api/auth/google`
}

export const authGoogleRedirect = async ( options?: RequestInit): Promise<authGoogleRedirectResponse> => {

  const res = await fetch(getAuthGoogleRedirectUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authGoogleRedirectResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authGoogleRedirectResponse
}





export const getAuthGoogleRedirectQueryKey = () => {
    return [
    `/api/api/auth/google`
    ] as const;
    }


export const getAuthGoogleRedirectQueryOptions = <TData = Awaited<ReturnType<typeof authGoogleRedirect>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGoogleRedirect>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthGoogleRedirectQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authGoogleRedirect>>> = ({ signal }) => authGoogleRedirect({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authGoogleRedirect>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthGoogleRedirectQueryResult = NonNullable<Awaited<ReturnType<typeof authGoogleRedirect>>>
export type AuthGoogleRedirectQueryError = void


export function useAuthGoogleRedirect<TData = Awaited<ReturnType<typeof authGoogleRedirect>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGoogleRedirect>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGoogleRedirect>>,
          TError,
          Awaited<ReturnType<typeof authGoogleRedirect>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthGoogleRedirect<TData = Awaited<ReturnType<typeof authGoogleRedirect>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGoogleRedirect>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGoogleRedirect>>,
          TError,
          Awaited<ReturnType<typeof authGoogleRedirect>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthGoogleRedirect<TData = Awaited<ReturnType<typeof authGoogleRedirect>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGoogleRedirect>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthGoogleRedirect<TData = Awaited<ReturnType<typeof authGoogleRedirect>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGoogleRedirect>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthGoogleRedirectQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Callback endpoint for Google OAuth2 authentication flow. Receives the authorization code and state parameters from Google after user authentication.
 */
export type authGoogleCallbackResponse302 = {
  data: void
  status: 302
}

;
export type authGoogleCallbackResponseError = (authGoogleCallbackResponse302) & {
  headers: Headers;
};

export type authGoogleCallbackResponse = (authGoogleCallbackResponseError)

export const getAuthGoogleCallbackUrl = (params: AuthGoogleCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/api/auth/google/callback?${stringifiedParams}` : `/api/api/auth/google/callback`
}

export const authGoogleCallback = async (params: AuthGoogleCallbackParams, options?: RequestInit): Promise<authGoogleCallbackResponse> => {

  const res = await fetch(getAuthGoogleCallbackUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authGoogleCallbackResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authGoogleCallbackResponse
}





export const getAuthGoogleCallbackQueryKey = (params?: AuthGoogleCallbackParams,) => {
    return [
    `/api/api/auth/google/callback`, ...(params ? [params] : [])
    ] as const;
    }


export const getAuthGoogleCallbackQueryOptions = <TData = Awaited<ReturnType<typeof authGoogleCallback>>, TError = void>(params: AuthGoogleCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGoogleCallback>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthGoogleCallbackQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authGoogleCallback>>> = ({ signal }) => authGoogleCallback(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authGoogleCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthGoogleCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof authGoogleCallback>>>
export type AuthGoogleCallbackQueryError = void


export function useAuthGoogleCallback<TData = Awaited<ReturnType<typeof authGoogleCallback>>, TError = void>(
 params: AuthGoogleCallbackParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGoogleCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof authGoogleCallback>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthGoogleCallback<TData = Awaited<ReturnType<typeof authGoogleCallback>>, TError = void>(
 params: AuthGoogleCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGoogleCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof authGoogleCallback>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthGoogleCallback<TData = Awaited<ReturnType<typeof authGoogleCallback>>, TError = void>(
 params: AuthGoogleCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGoogleCallback>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthGoogleCallback<TData = Awaited<ReturnType<typeof authGoogleCallback>>, TError = void>(
 params: AuthGoogleCallbackParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGoogleCallback>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthGoogleCallbackQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Log out the authenticated user by clearing their session or authentication tokens, and redirecting them to root
 */
export type authLogoutResponse302 = {
  data: void
  status: 302
}

;
export type authLogoutResponseError = (authLogoutResponse302) & {
  headers: Headers;
};

export type authLogoutResponse = (authLogoutResponseError)

export const getAuthLogoutUrl = () => {




  return `/api/api/auth/logout`
}

export const authLogout = async ( options?: RequestInit): Promise<authLogoutResponse> => {

  const res = await fetch(getAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authLogoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authLogoutResponse
}




export const getAuthLogoutMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext> => {

const mutationKey = ['authLogout'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authLogout>>, void> = () => {


          return  authLogout(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authLogout>>>

    export type AuthLogoutMutationError = void

    export const useAuthLogout = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authLogout>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthLogoutMutationOptions(options), queryClient);
    }
    /**
 * Get the authenticated user's information, including their unique identifier, email address, display name, and avatar URL.
 */
export type authGetMeResponse200 = {
  data: AuthMeResponse
  status: 200
}

export type authGetMeResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type authGetMeResponseSuccess = (authGetMeResponse200) & {
  headers: Headers;
};
export type authGetMeResponseError = (authGetMeResponse401) & {
  headers: Headers;
};

export type authGetMeResponse = (authGetMeResponseSuccess | authGetMeResponseError)

export const getAuthGetMeUrl = () => {




  return `/api/api/auth/me`
}

export const authGetMe = async ( options?: RequestInit): Promise<authGetMeResponse> => {

  const res = await fetch(getAuthGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authGetMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authGetMeResponse
}





export const getAuthGetMeQueryKey = () => {
    return [
    `/api/api/auth/me`
    ] as const;
    }


export const getAuthGetMeQueryOptions = <TData = Awaited<ReturnType<typeof authGetMe>>, TError = CommonErrorError401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authGetMe>>> = ({ signal }) => authGetMe({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof authGetMe>>>
export type AuthGetMeQueryError = CommonErrorError401


export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = CommonErrorError401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGetMe>>,
          TError,
          Awaited<ReturnType<typeof authGetMe>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = CommonErrorError401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGetMe>>,
          TError,
          Awaited<ReturnType<typeof authGetMe>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = CommonErrorError401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = CommonErrorError401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




