/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Callback endpoint for Google OAuth2 authentication flow. Receives the authorization code and state parameters from Google after user authentication.
 */
export const AuthGoogleCallbackQueryParams = zod.object({
  "code": zod.string().describe('The authorization code returned by Google after user authentication'),
  "state": zod.string().describe('The state parameter returned by Google, used to maintain state between the request and callback')
})

/**
 * Get the authenticated user's information, including their unique identifier, email address, display name, and avatar URL.
 */
export const AuthGetMeResponse = zod.object({
  "id": zod.string().describe('The unique identifier for the authenticated user'),
  "email": zod.string().describe('The email address of the authenticated user'),
  "name": zod.string().describe('The display name of the authenticated user'),
  "avatar_url": zod.string().describe('The URL of the authenticated user\'s avatar image')
})

