/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Register a new user
 */
export const postAuthRegisterBodyUsernameMin = 3;
export const postAuthRegisterBodyUsernameMax = 50;

export const postAuthRegisterBodyPasswordMin = 8;



export const PostAuthRegisterBody = zod.object({
  "username": zod.string().min(postAuthRegisterBodyUsernameMin).max(postAuthRegisterBodyUsernameMax),
  "email": zod.string().email(),
  "password": zod.string().min(postAuthRegisterBodyPasswordMin)
})

/**
 * @summary Log in and receive a session cookie
 */
export const PostAuthLoginBody = zod.object({
  "email": zod.string().email(),
  "password": zod.string()
})

export const PostAuthLoginResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
})

/**
 * @summary Return the currently authenticated user
 */
export const GetAuthMeResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
})

