/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Workspace Management API
 * API specification for managing users, workspaces, and pages.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Handles the callback from Google OAuth, exchanges code for session token, and redirects to frontend with session token
 * @summary Handle Google OAuth callback
 */
export const HandleGoogleOAuthCallbackQueryParams = zod.object({
  "code": zod.string().describe('Authorization code returned by Google'),
  "state": zod.string().describe('State parameter for CSRF protection')
})

