/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CourseNoteCreateRequest,
  CourseNoteListResponse,
  CourseNoteResponse,
  CourseNoteUpdateRequest,
  ErrorResponse,
  GetNotesParams
} from '../model';





/**
 * @summary List notes for a course
 */
export type getNotesResponse200 = {
  data: CourseNoteListResponse
  status: 200
}

export type getNotesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getNotesResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getNotesResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getNotesResponseSuccess = (getNotesResponse200) & {
  headers: Headers;
};
export type getNotesResponseError = (getNotesResponse401 | getNotesResponse404 | getNotesResponse500) & {
  headers: Headers;
};

export type getNotesResponse = (getNotesResponseSuccess | getNotesResponseError)

export const getGetNotesUrl = (params?: GetNotesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/notes?${stringifiedParams}` : `/notes`
}

export const getNotes = async (params?: GetNotesParams, options?: RequestInit): Promise<getNotesResponse> => {
  
  const res = await fetch(getGetNotesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getNotesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getNotesResponse
}
  




export const getGetNotesQueryKey = (params?: GetNotesParams,) => {
    return [
    `/notes`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetNotesQueryOptions = <TData = Awaited<ReturnType<typeof getNotes>>, TError = ErrorResponse>(params?: GetNotesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotes>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotes>>> = ({ signal }) => getNotes(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNotesQueryResult = NonNullable<Awaited<ReturnType<typeof getNotes>>>
export type GetNotesQueryError = ErrorResponse


export function useGetNotes<TData = Awaited<ReturnType<typeof getNotes>>, TError = ErrorResponse>(
 params: undefined |  GetNotesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotes>>,
          TError,
          Awaited<ReturnType<typeof getNotes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotes<TData = Awaited<ReturnType<typeof getNotes>>, TError = ErrorResponse>(
 params?: GetNotesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotes>>,
          TError,
          Awaited<ReturnType<typeof getNotes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotes<TData = Awaited<ReturnType<typeof getNotes>>, TError = ErrorResponse>(
 params?: GetNotesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List notes for a course
 */

export function useGetNotes<TData = Awaited<ReturnType<typeof getNotes>>, TError = ErrorResponse>(
 params?: GetNotesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNotesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a note for a course
 */
export type postNotesResponse201 = {
  data: CourseNoteResponse
  status: 201
}

export type postNotesResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postNotesResponse401 = {
  data: ErrorResponse
  status: 401
}

export type postNotesResponse404 = {
  data: ErrorResponse
  status: 404
}

export type postNotesResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postNotesResponseSuccess = (postNotesResponse201) & {
  headers: Headers;
};
export type postNotesResponseError = (postNotesResponse400 | postNotesResponse401 | postNotesResponse404 | postNotesResponse500) & {
  headers: Headers;
};

export type postNotesResponse = (postNotesResponseSuccess | postNotesResponseError)

export const getPostNotesUrl = () => {


  

  return `/notes`
}

export const postNotes = async (courseNoteCreateRequest: CourseNoteCreateRequest, options?: RequestInit): Promise<postNotesResponse> => {
  
  const res = await fetch(getPostNotesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      courseNoteCreateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postNotesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postNotesResponse
}
  



export const getPostNotesMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postNotes>>, TError,{data: CourseNoteCreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postNotes>>, TError,{data: CourseNoteCreateRequest}, TContext> => {

const mutationKey = ['postNotes'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postNotes>>, {data: CourseNoteCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postNotes(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostNotesMutationResult = NonNullable<Awaited<ReturnType<typeof postNotes>>>
    export type PostNotesMutationBody = CourseNoteCreateRequest
    export type PostNotesMutationError = ErrorResponse

    /**
 * @summary Create a note for a course
 */
export const usePostNotes = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postNotes>>, TError,{data: CourseNoteCreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postNotes>>,
        TError,
        {data: CourseNoteCreateRequest},
        TContext
      > => {
      return useMutation(getPostNotesMutationOptions(options), queryClient);
    }
    /**
 * @summary Get a course note by ID
 */
export type getNotesNoteIdResponse200 = {
  data: CourseNoteResponse
  status: 200
}

export type getNotesNoteIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getNotesNoteIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getNotesNoteIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getNotesNoteIdResponseSuccess = (getNotesNoteIdResponse200) & {
  headers: Headers;
};
export type getNotesNoteIdResponseError = (getNotesNoteIdResponse401 | getNotesNoteIdResponse404 | getNotesNoteIdResponse500) & {
  headers: Headers;
};

export type getNotesNoteIdResponse = (getNotesNoteIdResponseSuccess | getNotesNoteIdResponseError)

export const getGetNotesNoteIdUrl = (noteId: string,) => {


  

  return `/notes/${noteId}`
}

export const getNotesNoteId = async (noteId: string, options?: RequestInit): Promise<getNotesNoteIdResponse> => {
  
  const res = await fetch(getGetNotesNoteIdUrl(noteId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getNotesNoteIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getNotesNoteIdResponse
}
  




export const getGetNotesNoteIdQueryKey = (noteId: string,) => {
    return [
    `/notes/${noteId}`
    ] as const;
    }

    
export const getGetNotesNoteIdQueryOptions = <TData = Awaited<ReturnType<typeof getNotesNoteId>>, TError = ErrorResponse>(noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesNoteId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotesNoteIdQueryKey(noteId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotesNoteId>>> = ({ signal }) => getNotesNoteId(noteId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(noteId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotesNoteId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNotesNoteIdQueryResult = NonNullable<Awaited<ReturnType<typeof getNotesNoteId>>>
export type GetNotesNoteIdQueryError = ErrorResponse


export function useGetNotesNoteId<TData = Awaited<ReturnType<typeof getNotesNoteId>>, TError = ErrorResponse>(
 noteId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesNoteId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotesNoteId>>,
          TError,
          Awaited<ReturnType<typeof getNotesNoteId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotesNoteId<TData = Awaited<ReturnType<typeof getNotesNoteId>>, TError = ErrorResponse>(
 noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesNoteId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotesNoteId>>,
          TError,
          Awaited<ReturnType<typeof getNotesNoteId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotesNoteId<TData = Awaited<ReturnType<typeof getNotesNoteId>>, TError = ErrorResponse>(
 noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesNoteId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a course note by ID
 */

export function useGetNotesNoteId<TData = Awaited<ReturnType<typeof getNotesNoteId>>, TError = ErrorResponse>(
 noteId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesNoteId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNotesNoteIdQueryOptions(noteId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update a course note
 */
export type patchNotesNoteIdResponse200 = {
  data: CourseNoteResponse
  status: 200
}

export type patchNotesNoteIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type patchNotesNoteIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type patchNotesNoteIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type patchNotesNoteIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type patchNotesNoteIdResponseSuccess = (patchNotesNoteIdResponse200) & {
  headers: Headers;
};
export type patchNotesNoteIdResponseError = (patchNotesNoteIdResponse400 | patchNotesNoteIdResponse401 | patchNotesNoteIdResponse404 | patchNotesNoteIdResponse500) & {
  headers: Headers;
};

export type patchNotesNoteIdResponse = (patchNotesNoteIdResponseSuccess | patchNotesNoteIdResponseError)

export const getPatchNotesNoteIdUrl = (noteId: string,) => {


  

  return `/notes/${noteId}`
}

export const patchNotesNoteId = async (noteId: string,
    courseNoteUpdateRequest: CourseNoteUpdateRequest, options?: RequestInit): Promise<patchNotesNoteIdResponse> => {
  
  const res = await fetch(getPatchNotesNoteIdUrl(noteId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      courseNoteUpdateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchNotesNoteIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchNotesNoteIdResponse
}
  



export const getPatchNotesNoteIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchNotesNoteId>>, TError,{noteId: string;data: CourseNoteUpdateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchNotesNoteId>>, TError,{noteId: string;data: CourseNoteUpdateRequest}, TContext> => {

const mutationKey = ['patchNotesNoteId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchNotesNoteId>>, {noteId: string;data: CourseNoteUpdateRequest}> = (props) => {
          const {noteId,data} = props ?? {};

          return  patchNotesNoteId(noteId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchNotesNoteIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchNotesNoteId>>>
    export type PatchNotesNoteIdMutationBody = CourseNoteUpdateRequest
    export type PatchNotesNoteIdMutationError = ErrorResponse

    /**
 * @summary Update a course note
 */
export const usePatchNotesNoteId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchNotesNoteId>>, TError,{noteId: string;data: CourseNoteUpdateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchNotesNoteId>>,
        TError,
        {noteId: string;data: CourseNoteUpdateRequest},
        TContext
      > => {
      return useMutation(getPatchNotesNoteIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a course note
 */
export type deleteNotesNoteIdResponse204 = {
  data: void
  status: 204
}

export type deleteNotesNoteIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteNotesNoteIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteNotesNoteIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type deleteNotesNoteIdResponseSuccess = (deleteNotesNoteIdResponse204) & {
  headers: Headers;
};
export type deleteNotesNoteIdResponseError = (deleteNotesNoteIdResponse401 | deleteNotesNoteIdResponse404 | deleteNotesNoteIdResponse500) & {
  headers: Headers;
};

export type deleteNotesNoteIdResponse = (deleteNotesNoteIdResponseSuccess | deleteNotesNoteIdResponseError)

export const getDeleteNotesNoteIdUrl = (noteId: string,) => {


  

  return `/notes/${noteId}`
}

export const deleteNotesNoteId = async (noteId: string, options?: RequestInit): Promise<deleteNotesNoteIdResponse> => {
  
  const res = await fetch(getDeleteNotesNoteIdUrl(noteId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteNotesNoteIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteNotesNoteIdResponse
}
  



export const getDeleteNotesNoteIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotesNoteId>>, TError,{noteId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteNotesNoteId>>, TError,{noteId: string}, TContext> => {

const mutationKey = ['deleteNotesNoteId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNotesNoteId>>, {noteId: string}> = (props) => {
          const {noteId} = props ?? {};

          return  deleteNotesNoteId(noteId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteNotesNoteIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNotesNoteId>>>
    
    export type DeleteNotesNoteIdMutationError = ErrorResponse

    /**
 * @summary Delete a course note
 */
export const useDeleteNotesNoteId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotesNoteId>>, TError,{noteId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteNotesNoteId>>,
        TError,
        {noteId: string},
        TContext
      > => {
      return useMutation(getDeleteNotesNoteIdMutationOptions(options), queryClient);
    }
    