/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List notes for a course
 */
export const getNotesQueryPageDefault = 1;

export const getNotesQueryLimitDefault = 20;
export const getNotesQueryLimitMax = 100;

export const getNotesQuerySortDefault = `created_at`;
export const getNotesQueryOrderDefault = `desc`;

export const GetNotesQueryParams = zod.object({
  "page": zod.number().min(1).default(getNotesQueryPageDefault).describe('Page number (1-based)'),
  "limit": zod.number().min(1).max(getNotesQueryLimitMax).default(getNotesQueryLimitDefault).describe('Number of items per page'),
  "sort": zod.enum(['id', 'title', 'created_at', 'updated_at']).default(getNotesQuerySortDefault),
  "order": zod.enum(['asc', 'desc']).default(getNotesQueryOrderDefault),
  "title": zod.string().optional().describe('Filter by title (partial match)'),
  "created_by": zod.number().optional().describe('Filter by creator user ID'),
  "created_after": zod.string().datetime({}).optional(),
  "created_before": zod.string().datetime({}).optional(),
  "updated_after": zod.string().datetime({}).optional()
})

export const GetNotesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "content": zod.string().nullish(),
  "content_blob_url": zod.string().url().nullish().describe('Presigned URL to download the binary content blob. Null when no blob is stored.\n'),
  "course_id": zod.number(),
  "created_by": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded author (present when expanded)'),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "meta": zod.object({
  "page": zod.number(),
  "limit": zod.number(),
  "total": zod.number(),
  "total_pages": zod.number()
})
})

/**
 * @summary Create a note for a course
 */
export const postNotesBodyTitleMax = 500;



export const PostNotesBody = zod.object({
  "title": zod.string().min(1).max(postNotesBodyTitleMax),
  "content": zod.string().nullish()
})

/**
 * @summary Get a course note by ID
 */
export const GetNotesNoteIdParams = zod.object({
  "noteId": zod.string()
})

export const GetNotesNoteIdResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "content": zod.string().nullish(),
  "content_blob_url": zod.string().url().nullish().describe('Presigned URL to download the binary content blob. Null when no blob is stored.\n'),
  "course_id": zod.number(),
  "created_by": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded author (present when expanded)'),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary Update a course note
 */
export const PatchNotesNoteIdParams = zod.object({
  "noteId": zod.string()
})

export const patchNotesNoteIdBodyTitleMax = 500;



export const PatchNotesNoteIdBody = zod.object({
  "title": zod.string().min(1).max(patchNotesNoteIdBodyTitleMax).optional(),
  "content": zod.string().nullish()
})

export const PatchNotesNoteIdResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "content": zod.string().nullish(),
  "content_blob_url": zod.string().url().nullish().describe('Presigned URL to download the binary content blob. Null when no blob is stored.\n'),
  "course_id": zod.number(),
  "created_by": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded author (present when expanded)'),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary Delete a course note
 */
export const DeleteNotesNoteIdParams = zod.object({
  "noteId": zod.string()
})

