/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * My Catatan Kuliah
 * My Catatan Kuliah API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignmentsCreateRequest,
  AssignmentsCreateResponse,
  AssignmentsDetailResponse,
  AssignmentsListResponse,
  AssignmentsUpdateRequest,
  AssignmentsUpdateResponse,
  CommonErrorError400,
  CommonErrorError401,
  CommonErrorError404,
  CommonErrorError500
} from '../model';





export type assignmentsServiceCreateAssignmentResponse201 = {
  data: AssignmentsCreateResponse
  status: 201
}

export type assignmentsServiceCreateAssignmentResponse400 = {
  data: CommonErrorError400
  status: 400
}

export type assignmentsServiceCreateAssignmentResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type assignmentsServiceCreateAssignmentResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type assignmentsServiceCreateAssignmentResponseSuccess = (assignmentsServiceCreateAssignmentResponse201) & {
  headers: Headers;
};
export type assignmentsServiceCreateAssignmentResponseError = (assignmentsServiceCreateAssignmentResponse400 | assignmentsServiceCreateAssignmentResponse401 | assignmentsServiceCreateAssignmentResponse500) & {
  headers: Headers;
};

export type assignmentsServiceCreateAssignmentResponse = (assignmentsServiceCreateAssignmentResponseSuccess | assignmentsServiceCreateAssignmentResponseError)

export const getAssignmentsServiceCreateAssignmentUrl = () => {




  return `/api/assignments`
}

/**
 * Create a new assignment with the specified details.
 */
export const assignmentsServiceCreateAssignment = async (assignmentsCreateRequest: AssignmentsCreateRequest, options?: RequestInit): Promise<assignmentsServiceCreateAssignmentResponse> => {

  const res = await fetch(getAssignmentsServiceCreateAssignmentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignmentsCreateRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: assignmentsServiceCreateAssignmentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as assignmentsServiceCreateAssignmentResponse
}




export const getAssignmentsServiceCreateAssignmentMutationOptions = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignmentsServiceCreateAssignment>>, TError,{data: AssignmentsCreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof assignmentsServiceCreateAssignment>>, TError,{data: AssignmentsCreateRequest}, TContext> => {

const mutationKey = ['assignmentsServiceCreateAssignment'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignmentsServiceCreateAssignment>>, {data: AssignmentsCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  assignmentsServiceCreateAssignment(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AssignmentsServiceCreateAssignmentMutationResult = NonNullable<Awaited<ReturnType<typeof assignmentsServiceCreateAssignment>>>
    export type AssignmentsServiceCreateAssignmentMutationBody = AssignmentsCreateRequest
    export type AssignmentsServiceCreateAssignmentMutationError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500

    export const useAssignmentsServiceCreateAssignment = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignmentsServiceCreateAssignment>>, TError,{data: AssignmentsCreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignmentsServiceCreateAssignment>>,
        TError,
        {data: AssignmentsCreateRequest},
        TContext
      > => {
      return useMutation(getAssignmentsServiceCreateAssignmentMutationOptions(options), queryClient);
    }
    export type assignmentsServiceListAssignmentsResponse200 = {
  data: AssignmentsListResponse
  status: 200
}

export type assignmentsServiceListAssignmentsResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type assignmentsServiceListAssignmentsResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type assignmentsServiceListAssignmentsResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type assignmentsServiceListAssignmentsResponseSuccess = (assignmentsServiceListAssignmentsResponse200) & {
  headers: Headers;
};
export type assignmentsServiceListAssignmentsResponseError = (assignmentsServiceListAssignmentsResponse401 | assignmentsServiceListAssignmentsResponse404 | assignmentsServiceListAssignmentsResponse500) & {
  headers: Headers;
};

export type assignmentsServiceListAssignmentsResponse = (assignmentsServiceListAssignmentsResponseSuccess | assignmentsServiceListAssignmentsResponseError)

export const getAssignmentsServiceListAssignmentsUrl = (courseId: string,) => {




  return `/api/assignments/l/${courseId}`
}

/**
 * List all assignments accessible to the authenticated user.
 */
export const assignmentsServiceListAssignments = async (courseId: string, options?: RequestInit): Promise<assignmentsServiceListAssignmentsResponse> => {

  const res = await fetch(getAssignmentsServiceListAssignmentsUrl(courseId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: assignmentsServiceListAssignmentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as assignmentsServiceListAssignmentsResponse
}





export const getAssignmentsServiceListAssignmentsQueryKey = (courseId: string,) => {
    return [
    `/api/assignments/l/${courseId}`
    ] as const;
    }


export const getAssignmentsServiceListAssignmentsQueryOptions = <TData = Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssignmentsServiceListAssignmentsQueryKey(courseId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof assignmentsServiceListAssignments>>> = ({ signal }) => assignmentsServiceListAssignments(courseId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(courseId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssignmentsServiceListAssignmentsQueryResult = NonNullable<Awaited<ReturnType<typeof assignmentsServiceListAssignments>>>
export type AssignmentsServiceListAssignmentsQueryError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500


export function useAssignmentsServiceListAssignments<TData = Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 courseId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assignmentsServiceListAssignments>>,
          TError,
          Awaited<ReturnType<typeof assignmentsServiceListAssignments>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssignmentsServiceListAssignments<TData = Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assignmentsServiceListAssignments>>,
          TError,
          Awaited<ReturnType<typeof assignmentsServiceListAssignments>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssignmentsServiceListAssignments<TData = Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssignmentsServiceListAssignments<TData = Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 courseId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceListAssignments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssignmentsServiceListAssignmentsQueryOptions(courseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type assignmentsServiceGetAssignmentResponse200 = {
  data: AssignmentsDetailResponse
  status: 200
}

export type assignmentsServiceGetAssignmentResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type assignmentsServiceGetAssignmentResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type assignmentsServiceGetAssignmentResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type assignmentsServiceGetAssignmentResponseSuccess = (assignmentsServiceGetAssignmentResponse200) & {
  headers: Headers;
};
export type assignmentsServiceGetAssignmentResponseError = (assignmentsServiceGetAssignmentResponse401 | assignmentsServiceGetAssignmentResponse404 | assignmentsServiceGetAssignmentResponse500) & {
  headers: Headers;
};

export type assignmentsServiceGetAssignmentResponse = (assignmentsServiceGetAssignmentResponseSuccess | assignmentsServiceGetAssignmentResponseError)

export const getAssignmentsServiceGetAssignmentUrl = (assignmentId: string,) => {




  return `/api/assignments/${assignmentId}`
}

/**
 * Get details of a specific assignment by its ID.
 */
export const assignmentsServiceGetAssignment = async (assignmentId: string, options?: RequestInit): Promise<assignmentsServiceGetAssignmentResponse> => {

  const res = await fetch(getAssignmentsServiceGetAssignmentUrl(assignmentId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: assignmentsServiceGetAssignmentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as assignmentsServiceGetAssignmentResponse
}





export const getAssignmentsServiceGetAssignmentQueryKey = (assignmentId: string,) => {
    return [
    `/api/assignments/${assignmentId}`
    ] as const;
    }


export const getAssignmentsServiceGetAssignmentQueryOptions = <TData = Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(assignmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssignmentsServiceGetAssignmentQueryKey(assignmentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>> = ({ signal }) => assignmentsServiceGetAssignment(assignmentId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(assignmentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssignmentsServiceGetAssignmentQueryResult = NonNullable<Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>>
export type AssignmentsServiceGetAssignmentQueryError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500


export function useAssignmentsServiceGetAssignment<TData = Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 assignmentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>,
          TError,
          Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssignmentsServiceGetAssignment<TData = Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 assignmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>,
          TError,
          Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssignmentsServiceGetAssignment<TData = Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 assignmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssignmentsServiceGetAssignment<TData = Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500>(
 assignmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assignmentsServiceGetAssignment>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssignmentsServiceGetAssignmentQueryOptions(assignmentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type assignmentsServiceDeleteAssignmentResponse204 = {
  data: void
  status: 204
}

export type assignmentsServiceDeleteAssignmentResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type assignmentsServiceDeleteAssignmentResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type assignmentsServiceDeleteAssignmentResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type assignmentsServiceDeleteAssignmentResponseSuccess = (assignmentsServiceDeleteAssignmentResponse204) & {
  headers: Headers;
};
export type assignmentsServiceDeleteAssignmentResponseError = (assignmentsServiceDeleteAssignmentResponse401 | assignmentsServiceDeleteAssignmentResponse404 | assignmentsServiceDeleteAssignmentResponse500) & {
  headers: Headers;
};

export type assignmentsServiceDeleteAssignmentResponse = (assignmentsServiceDeleteAssignmentResponseSuccess | assignmentsServiceDeleteAssignmentResponseError)

export const getAssignmentsServiceDeleteAssignmentUrl = (assignmentId: string,) => {




  return `/api/assignments/${assignmentId}`
}

/**
 * Delete a specific assignment by its ID.
 */
export const assignmentsServiceDeleteAssignment = async (assignmentId: string, options?: RequestInit): Promise<assignmentsServiceDeleteAssignmentResponse> => {

  const res = await fetch(getAssignmentsServiceDeleteAssignmentUrl(assignmentId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: assignmentsServiceDeleteAssignmentResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as assignmentsServiceDeleteAssignmentResponse
}




export const getAssignmentsServiceDeleteAssignmentMutationOptions = <TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignmentsServiceDeleteAssignment>>, TError,{assignmentId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof assignmentsServiceDeleteAssignment>>, TError,{assignmentId: string}, TContext> => {

const mutationKey = ['assignmentsServiceDeleteAssignment'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignmentsServiceDeleteAssignment>>, {assignmentId: string}> = (props) => {
          const {assignmentId} = props ?? {};

          return  assignmentsServiceDeleteAssignment(assignmentId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AssignmentsServiceDeleteAssignmentMutationResult = NonNullable<Awaited<ReturnType<typeof assignmentsServiceDeleteAssignment>>>

    export type AssignmentsServiceDeleteAssignmentMutationError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500

    export const useAssignmentsServiceDeleteAssignment = <TError = CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignmentsServiceDeleteAssignment>>, TError,{assignmentId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignmentsServiceDeleteAssignment>>,
        TError,
        {assignmentId: string},
        TContext
      > => {
      return useMutation(getAssignmentsServiceDeleteAssignmentMutationOptions(options), queryClient);
    }
    export type assignmentsServiceUpdateAssignmentResponse200 = {
  data: AssignmentsUpdateResponse
  status: 200
}

export type assignmentsServiceUpdateAssignmentResponse400 = {
  data: CommonErrorError400
  status: 400
}

export type assignmentsServiceUpdateAssignmentResponse401 = {
  data: CommonErrorError401
  status: 401
}

export type assignmentsServiceUpdateAssignmentResponse404 = {
  data: CommonErrorError404
  status: 404
}

export type assignmentsServiceUpdateAssignmentResponse500 = {
  data: CommonErrorError500
  status: 500
}

export type assignmentsServiceUpdateAssignmentResponseSuccess = (assignmentsServiceUpdateAssignmentResponse200) & {
  headers: Headers;
};
export type assignmentsServiceUpdateAssignmentResponseError = (assignmentsServiceUpdateAssignmentResponse400 | assignmentsServiceUpdateAssignmentResponse401 | assignmentsServiceUpdateAssignmentResponse404 | assignmentsServiceUpdateAssignmentResponse500) & {
  headers: Headers;
};

export type assignmentsServiceUpdateAssignmentResponse = (assignmentsServiceUpdateAssignmentResponseSuccess | assignmentsServiceUpdateAssignmentResponseError)

export const getAssignmentsServiceUpdateAssignmentUrl = (assignmentId: string,) => {




  return `/api/assignments/${assignmentId}`
}

/**
 * Update details of a specific assignment by its ID.
 */
export const assignmentsServiceUpdateAssignment = async (assignmentId: string,
    assignmentsUpdateRequest: AssignmentsUpdateRequest, options?: RequestInit): Promise<assignmentsServiceUpdateAssignmentResponse> => {

  const res = await fetch(getAssignmentsServiceUpdateAssignmentUrl(assignmentId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignmentsUpdateRequest,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: assignmentsServiceUpdateAssignmentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as assignmentsServiceUpdateAssignmentResponse
}




export const getAssignmentsServiceUpdateAssignmentMutationOptions = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignmentsServiceUpdateAssignment>>, TError,{assignmentId: string;data: AssignmentsUpdateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof assignmentsServiceUpdateAssignment>>, TError,{assignmentId: string;data: AssignmentsUpdateRequest}, TContext> => {

const mutationKey = ['assignmentsServiceUpdateAssignment'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignmentsServiceUpdateAssignment>>, {assignmentId: string;data: AssignmentsUpdateRequest}> = (props) => {
          const {assignmentId,data} = props ?? {};

          return  assignmentsServiceUpdateAssignment(assignmentId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AssignmentsServiceUpdateAssignmentMutationResult = NonNullable<Awaited<ReturnType<typeof assignmentsServiceUpdateAssignment>>>
    export type AssignmentsServiceUpdateAssignmentMutationBody = AssignmentsUpdateRequest
    export type AssignmentsServiceUpdateAssignmentMutationError = CommonErrorError400 | CommonErrorError401 | CommonErrorError404 | CommonErrorError500

    export const useAssignmentsServiceUpdateAssignment = <TError = CommonErrorError400 | CommonErrorError401 | CommonErrorError404 | CommonErrorError500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignmentsServiceUpdateAssignment>>, TError,{assignmentId: string;data: AssignmentsUpdateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignmentsServiceUpdateAssignment>>,
        TError,
        {assignmentId: string;data: AssignmentsUpdateRequest},
        TContext
      > => {
      return useMutation(getAssignmentsServiceUpdateAssignmentMutationOptions(options), queryClient);
    }
