/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignmentCreateRequest,
  AssignmentListResponse,
  AssignmentResponse,
  AssignmentUpdateRequest,
  ErrorResponse,
  GetAssignmentsParams
} from '../model';





/**
 * @summary List assignments for a course
 */
export type getAssignmentsResponse200 = {
  data: AssignmentListResponse
  status: 200
}

export type getAssignmentsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getAssignmentsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAssignmentsResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAssignmentsResponseSuccess = (getAssignmentsResponse200) & {
  headers: Headers;
};
export type getAssignmentsResponseError = (getAssignmentsResponse401 | getAssignmentsResponse404 | getAssignmentsResponse500) & {
  headers: Headers;
};

export type getAssignmentsResponse = (getAssignmentsResponseSuccess | getAssignmentsResponseError)

export const getGetAssignmentsUrl = (params?: GetAssignmentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/assignments?${stringifiedParams}` : `/assignments`
}

export const getAssignments = async (params?: GetAssignmentsParams, options?: RequestInit): Promise<getAssignmentsResponse> => {
  
  const res = await fetch(getGetAssignmentsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAssignmentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAssignmentsResponse
}
  




export const getGetAssignmentsQueryKey = (params?: GetAssignmentsParams,) => {
    return [
    `/assignments`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAssignmentsQueryOptions = <TData = Awaited<ReturnType<typeof getAssignments>>, TError = ErrorResponse>(params?: GetAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignments>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAssignmentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssignments>>> = ({ signal }) => getAssignments(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAssignments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAssignmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getAssignments>>>
export type GetAssignmentsQueryError = ErrorResponse


export function useGetAssignments<TData = Awaited<ReturnType<typeof getAssignments>>, TError = ErrorResponse>(
 params: undefined |  GetAssignmentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssignments>>,
          TError,
          Awaited<ReturnType<typeof getAssignments>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssignments<TData = Awaited<ReturnType<typeof getAssignments>>, TError = ErrorResponse>(
 params?: GetAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssignments>>,
          TError,
          Awaited<ReturnType<typeof getAssignments>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssignments<TData = Awaited<ReturnType<typeof getAssignments>>, TError = ErrorResponse>(
 params?: GetAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List assignments for a course
 */

export function useGetAssignments<TData = Awaited<ReturnType<typeof getAssignments>>, TError = ErrorResponse>(
 params?: GetAssignmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignments>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAssignmentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create an assignment for a course
 */
export type postAssignmentsResponse201 = {
  data: AssignmentResponse
  status: 201
}

export type postAssignmentsResponse400 = {
  data: ErrorResponse
  status: 400
}

export type postAssignmentsResponse401 = {
  data: ErrorResponse
  status: 401
}

export type postAssignmentsResponse404 = {
  data: ErrorResponse
  status: 404
}

export type postAssignmentsResponse500 = {
  data: ErrorResponse
  status: 500
}

export type postAssignmentsResponseSuccess = (postAssignmentsResponse201) & {
  headers: Headers;
};
export type postAssignmentsResponseError = (postAssignmentsResponse400 | postAssignmentsResponse401 | postAssignmentsResponse404 | postAssignmentsResponse500) & {
  headers: Headers;
};

export type postAssignmentsResponse = (postAssignmentsResponseSuccess | postAssignmentsResponseError)

export const getPostAssignmentsUrl = () => {


  

  return `/assignments`
}

export const postAssignments = async (assignmentCreateRequest: AssignmentCreateRequest, options?: RequestInit): Promise<postAssignmentsResponse> => {
  
  const res = await fetch(getPostAssignmentsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignmentCreateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postAssignmentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postAssignmentsResponse
}
  



export const getPostAssignmentsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAssignments>>, TError,{data: AssignmentCreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postAssignments>>, TError,{data: AssignmentCreateRequest}, TContext> => {

const mutationKey = ['postAssignments'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAssignments>>, {data: AssignmentCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAssignments(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostAssignmentsMutationResult = NonNullable<Awaited<ReturnType<typeof postAssignments>>>
    export type PostAssignmentsMutationBody = AssignmentCreateRequest
    export type PostAssignmentsMutationError = ErrorResponse

    /**
 * @summary Create an assignment for a course
 */
export const usePostAssignments = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAssignments>>, TError,{data: AssignmentCreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAssignments>>,
        TError,
        {data: AssignmentCreateRequest},
        TContext
      > => {
      return useMutation(getPostAssignmentsMutationOptions(options), queryClient);
    }
    /**
 * @summary Get an assignment by ID
 */
export type getAssignmentsAssignmentIdResponse200 = {
  data: AssignmentResponse
  status: 200
}

export type getAssignmentsAssignmentIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getAssignmentsAssignmentIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAssignmentsAssignmentIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type getAssignmentsAssignmentIdResponseSuccess = (getAssignmentsAssignmentIdResponse200) & {
  headers: Headers;
};
export type getAssignmentsAssignmentIdResponseError = (getAssignmentsAssignmentIdResponse401 | getAssignmentsAssignmentIdResponse404 | getAssignmentsAssignmentIdResponse500) & {
  headers: Headers;
};

export type getAssignmentsAssignmentIdResponse = (getAssignmentsAssignmentIdResponseSuccess | getAssignmentsAssignmentIdResponseError)

export const getGetAssignmentsAssignmentIdUrl = (assignmentId: string,) => {


  

  return `/assignments/${assignmentId}`
}

export const getAssignmentsAssignmentId = async (assignmentId: string, options?: RequestInit): Promise<getAssignmentsAssignmentIdResponse> => {
  
  const res = await fetch(getGetAssignmentsAssignmentIdUrl(assignmentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAssignmentsAssignmentIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAssignmentsAssignmentIdResponse
}
  




export const getGetAssignmentsAssignmentIdQueryKey = (assignmentId: string,) => {
    return [
    `/assignments/${assignmentId}`
    ] as const;
    }

    
export const getGetAssignmentsAssignmentIdQueryOptions = <TData = Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError = ErrorResponse>(assignmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAssignmentsAssignmentIdQueryKey(assignmentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssignmentsAssignmentId>>> = ({ signal }) => getAssignmentsAssignmentId(assignmentId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(assignmentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAssignmentsAssignmentIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAssignmentsAssignmentId>>>
export type GetAssignmentsAssignmentIdQueryError = ErrorResponse


export function useGetAssignmentsAssignmentId<TData = Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError = ErrorResponse>(
 assignmentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssignmentsAssignmentId>>,
          TError,
          Awaited<ReturnType<typeof getAssignmentsAssignmentId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssignmentsAssignmentId<TData = Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError = ErrorResponse>(
 assignmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssignmentsAssignmentId>>,
          TError,
          Awaited<ReturnType<typeof getAssignmentsAssignmentId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssignmentsAssignmentId<TData = Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError = ErrorResponse>(
 assignmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get an assignment by ID
 */

export function useGetAssignmentsAssignmentId<TData = Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError = ErrorResponse>(
 assignmentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignmentsAssignmentId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAssignmentsAssignmentIdQueryOptions(assignmentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update an assignment
 */
export type patchAssignmentsAssignmentIdResponse200 = {
  data: AssignmentResponse
  status: 200
}

export type patchAssignmentsAssignmentIdResponse400 = {
  data: ErrorResponse
  status: 400
}

export type patchAssignmentsAssignmentIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type patchAssignmentsAssignmentIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type patchAssignmentsAssignmentIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type patchAssignmentsAssignmentIdResponseSuccess = (patchAssignmentsAssignmentIdResponse200) & {
  headers: Headers;
};
export type patchAssignmentsAssignmentIdResponseError = (patchAssignmentsAssignmentIdResponse400 | patchAssignmentsAssignmentIdResponse401 | patchAssignmentsAssignmentIdResponse404 | patchAssignmentsAssignmentIdResponse500) & {
  headers: Headers;
};

export type patchAssignmentsAssignmentIdResponse = (patchAssignmentsAssignmentIdResponseSuccess | patchAssignmentsAssignmentIdResponseError)

export const getPatchAssignmentsAssignmentIdUrl = (assignmentId: string,) => {


  

  return `/assignments/${assignmentId}`
}

export const patchAssignmentsAssignmentId = async (assignmentId: string,
    assignmentUpdateRequest: AssignmentUpdateRequest, options?: RequestInit): Promise<patchAssignmentsAssignmentIdResponse> => {
  
  const res = await fetch(getPatchAssignmentsAssignmentIdUrl(assignmentId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignmentUpdateRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: patchAssignmentsAssignmentIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchAssignmentsAssignmentIdResponse
}
  



export const getPatchAssignmentsAssignmentIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAssignmentsAssignmentId>>, TError,{assignmentId: string;data: AssignmentUpdateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchAssignmentsAssignmentId>>, TError,{assignmentId: string;data: AssignmentUpdateRequest}, TContext> => {

const mutationKey = ['patchAssignmentsAssignmentId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAssignmentsAssignmentId>>, {assignmentId: string;data: AssignmentUpdateRequest}> = (props) => {
          const {assignmentId,data} = props ?? {};

          return  patchAssignmentsAssignmentId(assignmentId,data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchAssignmentsAssignmentIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAssignmentsAssignmentId>>>
    export type PatchAssignmentsAssignmentIdMutationBody = AssignmentUpdateRequest
    export type PatchAssignmentsAssignmentIdMutationError = ErrorResponse

    /**
 * @summary Update an assignment
 */
export const usePatchAssignmentsAssignmentId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAssignmentsAssignmentId>>, TError,{assignmentId: string;data: AssignmentUpdateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAssignmentsAssignmentId>>,
        TError,
        {assignmentId: string;data: AssignmentUpdateRequest},
        TContext
      > => {
      return useMutation(getPatchAssignmentsAssignmentIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete an assignment
 */
export type deleteAssignmentsAssignmentIdResponse204 = {
  data: void
  status: 204
}

export type deleteAssignmentsAssignmentIdResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteAssignmentsAssignmentIdResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteAssignmentsAssignmentIdResponse500 = {
  data: ErrorResponse
  status: 500
}

export type deleteAssignmentsAssignmentIdResponseSuccess = (deleteAssignmentsAssignmentIdResponse204) & {
  headers: Headers;
};
export type deleteAssignmentsAssignmentIdResponseError = (deleteAssignmentsAssignmentIdResponse401 | deleteAssignmentsAssignmentIdResponse404 | deleteAssignmentsAssignmentIdResponse500) & {
  headers: Headers;
};

export type deleteAssignmentsAssignmentIdResponse = (deleteAssignmentsAssignmentIdResponseSuccess | deleteAssignmentsAssignmentIdResponseError)

export const getDeleteAssignmentsAssignmentIdUrl = (assignmentId: string,) => {


  

  return `/assignments/${assignmentId}`
}

export const deleteAssignmentsAssignmentId = async (assignmentId: string, options?: RequestInit): Promise<deleteAssignmentsAssignmentIdResponse> => {
  
  const res = await fetch(getDeleteAssignmentsAssignmentIdUrl(assignmentId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteAssignmentsAssignmentIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteAssignmentsAssignmentIdResponse
}
  



export const getDeleteAssignmentsAssignmentIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssignmentsAssignmentId>>, TError,{assignmentId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAssignmentsAssignmentId>>, TError,{assignmentId: string}, TContext> => {

const mutationKey = ['deleteAssignmentsAssignmentId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAssignmentsAssignmentId>>, {assignmentId: string}> = (props) => {
          const {assignmentId} = props ?? {};

          return  deleteAssignmentsAssignmentId(assignmentId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAssignmentsAssignmentIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAssignmentsAssignmentId>>>
    
    export type DeleteAssignmentsAssignmentIdMutationError = ErrorResponse

    /**
 * @summary Delete an assignment
 */
export const useDeleteAssignmentsAssignmentId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssignmentsAssignmentId>>, TError,{assignmentId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAssignmentsAssignmentId>>,
        TError,
        {assignmentId: string},
        TContext
      > => {
      return useMutation(getDeleteAssignmentsAssignmentIdMutationOptions(options), queryClient);
    }
    