/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Course Management API
 * REST API for managing users, workspaces, courses, course notes, and assignments. Authentication is handled via cookie-based sessions.

 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List assignments for a course
 */
export const getAssignmentsQueryPageDefault = 1;

export const getAssignmentsQueryLimitDefault = 20;
export const getAssignmentsQueryLimitMax = 100;

export const getAssignmentsQuerySortDefault = `deadline`;
export const getAssignmentsQueryOrderDefault = `asc`;

export const GetAssignmentsQueryParams = zod.object({
  "page": zod.number().min(1).default(getAssignmentsQueryPageDefault).describe('Page number (1-based)'),
  "limit": zod.number().min(1).max(getAssignmentsQueryLimitMax).default(getAssignmentsQueryLimitDefault).describe('Number of items per page'),
  "sort": zod.enum(['id', 'title', 'deadline', 'status', 'created_at', 'updated_at']).default(getAssignmentsQuerySortDefault),
  "order": zod.enum(['asc', 'desc']).default(getAssignmentsQueryOrderDefault),
  "status": zod.enum(['pending', 'in_progress', 'submitted', 'graded', 'overdue']).optional(),
  "created_by": zod.number().optional(),
  "deadline_before": zod.string().datetime({}).optional(),
  "deadline_after": zod.string().datetime({}).optional()
})

export const GetAssignmentsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "deadline": zod.string().datetime({}),
  "status": zod.enum(['pending', 'in_progress', 'submitted', 'graded', 'overdue']),
  "course_id": zod.number(),
  "created_by": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded author (present when expanded)'),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})),
  "meta": zod.object({
  "page": zod.number(),
  "limit": zod.number(),
  "total": zod.number(),
  "total_pages": zod.number()
})
})

/**
 * @summary Create an assignment for a course
 */
export const postAssignmentsBodyTitleMax = 500;

export const postAssignmentsBodyStatusDefault = `pending`;

export const PostAssignmentsBody = zod.object({
  "title": zod.string().min(1).max(postAssignmentsBodyTitleMax),
  "description": zod.string().nullish(),
  "deadline": zod.string().datetime({}),
  "status": zod.enum(['pending', 'in_progress', 'submitted', 'graded', 'overdue']).default(postAssignmentsBodyStatusDefault)
})

/**
 * @summary Get an assignment by ID
 */
export const GetAssignmentsAssignmentIdParams = zod.object({
  "assignmentId": zod.string()
})

export const GetAssignmentsAssignmentIdResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "deadline": zod.string().datetime({}),
  "status": zod.enum(['pending', 'in_progress', 'submitted', 'graded', 'overdue']),
  "course_id": zod.number(),
  "created_by": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded author (present when expanded)'),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary Update an assignment
 */
export const PatchAssignmentsAssignmentIdParams = zod.object({
  "assignmentId": zod.string()
})

export const patchAssignmentsAssignmentIdBodyTitleMax = 500;



export const PatchAssignmentsAssignmentIdBody = zod.object({
  "title": zod.string().min(1).max(patchAssignmentsAssignmentIdBodyTitleMax).optional(),
  "description": zod.string().nullish(),
  "deadline": zod.string().datetime({}).optional(),
  "status": zod.enum(['pending', 'in_progress', 'submitted', 'graded', 'overdue']).optional()
})

export const PatchAssignmentsAssignmentIdResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string().nullish(),
  "deadline": zod.string().datetime({}),
  "status": zod.enum(['pending', 'in_progress', 'submitted', 'graded', 'overdue']),
  "course_id": zod.number(),
  "created_by": zod.number(),
  "author": zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string().email(),
  "created_at": zod.string().datetime({})
}).optional().describe('Embedded author (present when expanded)'),
  "created_at": zod.string().datetime({}),
  "updated_at": zod.string().datetime({})
})

/**
 * @summary Delete an assignment
 */
export const DeleteAssignmentsAssignmentIdParams = zod.object({
  "assignmentId": zod.string()
})

