/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiptapRouteImport } from './routes/tiptap'
import { Route as StudyRouteImport } from './routes/study'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as PostsRouteRouteImport } from './routes/posts.route'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as LayoutWorkspaceIdRouteImport } from './routes/_layout.$workspaceId'
import { Route as LayoutWorkspaceIdIndexRouteImport } from './routes/_layout.$workspaceId/index'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'
import { Route as LayoutCCourseIdRouteImport } from './routes/_layout.c.$courseId'
import { Route as LayoutCCourseIdIndexRouteImport } from './routes/_layout.c.$courseId/index'
import { Route as LayoutCCourseIdARouteImport } from './routes/_layout.c.$courseId/a'
import { Route as LayoutWorkspaceIdCChatIdRouteImport } from './routes/_layout.$workspaceId/c.$chatId'
import { Route as LayoutCCourseIdNNotesIdRouteImport } from './routes/_layout.c.$courseId/n.$notesId'
import { Route as LayoutCCourseIdAAssignmentIdRouteImport } from './routes/_layout.c.$courseId/a.$assignmentId'

const TiptapRoute = TiptapRouteImport.update({
  id: '/tiptap',
  path: '/tiptap',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const LayoutWorkspaceIdRoute = LayoutWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkspaceIdIndexRoute = LayoutWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutWorkspaceIdRoute,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const LayoutCCourseIdRoute = LayoutCCourseIdRouteImport.update({
  id: '/c/$courseId',
  path: '/c/$courseId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCCourseIdIndexRoute = LayoutCCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCCourseIdRoute,
} as any)
const LayoutCCourseIdARoute = LayoutCCourseIdARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => LayoutCCourseIdRoute,
} as any)
const LayoutWorkspaceIdCChatIdRoute =
  LayoutWorkspaceIdCChatIdRouteImport.update({
    id: '/c/$chatId',
    path: '/c/$chatId',
    getParentRoute: () => LayoutWorkspaceIdRoute,
  } as any)
const LayoutCCourseIdNNotesIdRoute = LayoutCCourseIdNNotesIdRouteImport.update({
  id: '/n/$notesId',
  path: '/n/$notesId',
  getParentRoute: () => LayoutCCourseIdRoute,
} as any)
const LayoutCCourseIdAAssignmentIdRoute =
  LayoutCCourseIdAAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => LayoutCCourseIdARoute,
  } as any)

export interface FileRoutesByFullPath {
  '/posts': typeof PostsRouteRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/study': typeof StudyRoute
  '/tiptap': typeof TiptapRoute
  '/$workspaceId': typeof LayoutWorkspaceIdRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/': typeof PostsIndexRoute
  '/c/$courseId': typeof LayoutCCourseIdRouteWithChildren
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/$workspaceId/': typeof LayoutWorkspaceIdIndexRoute
  '/$workspaceId/c/$chatId': typeof LayoutWorkspaceIdCChatIdRoute
  '/c/$courseId/a': typeof LayoutCCourseIdARouteWithChildren
  '/c/$courseId/': typeof LayoutCCourseIdIndexRoute
  '/c/$courseId/a/$assignmentId': typeof LayoutCCourseIdAAssignmentIdRoute
  '/c/$courseId/n/$notesId': typeof LayoutCCourseIdNNotesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/study': typeof StudyRoute
  '/tiptap': typeof TiptapRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts': typeof PostsIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/$workspaceId': typeof LayoutWorkspaceIdIndexRoute
  '/$workspaceId/c/$chatId': typeof LayoutWorkspaceIdCChatIdRoute
  '/c/$courseId/a': typeof LayoutCCourseIdARouteWithChildren
  '/c/$courseId': typeof LayoutCCourseIdIndexRoute
  '/c/$courseId/a/$assignmentId': typeof LayoutCCourseIdAAssignmentIdRoute
  '/c/$courseId/n/$notesId': typeof LayoutCCourseIdNNotesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/posts': typeof PostsRouteRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/study': typeof StudyRoute
  '/tiptap': typeof TiptapRoute
  '/_layout/$workspaceId': typeof LayoutWorkspaceIdRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/_layout/c/$courseId': typeof LayoutCCourseIdRouteWithChildren
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/_layout/$workspaceId/': typeof LayoutWorkspaceIdIndexRoute
  '/_layout/$workspaceId/c/$chatId': typeof LayoutWorkspaceIdCChatIdRoute
  '/_layout/c/$courseId/a': typeof LayoutCCourseIdARouteWithChildren
  '/_layout/c/$courseId/': typeof LayoutCCourseIdIndexRoute
  '/_layout/c/$courseId/a/$assignmentId': typeof LayoutCCourseIdAAssignmentIdRoute
  '/_layout/c/$courseId/n/$notesId': typeof LayoutCCourseIdNNotesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/posts'
    | '/'
    | '/login'
    | '/study'
    | '/tiptap'
    | '/$workspaceId'
    | '/posts/$postId'
    | '/posts/'
    | '/c/$courseId'
    | '/route-a'
    | '/route-b'
    | '/$workspaceId/'
    | '/$workspaceId/c/$chatId'
    | '/c/$courseId/a'
    | '/c/$courseId/'
    | '/c/$courseId/a/$assignmentId'
    | '/c/$courseId/n/$notesId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/study'
    | '/tiptap'
    | '/posts/$postId'
    | '/posts'
    | '/route-a'
    | '/route-b'
    | '/$workspaceId'
    | '/$workspaceId/c/$chatId'
    | '/c/$courseId/a'
    | '/c/$courseId'
    | '/c/$courseId/a/$assignmentId'
    | '/c/$courseId/n/$notesId'
  id:
    | '__root__'
    | '/posts'
    | '/_layout'
    | '/_pathlessLayout'
    | '/login'
    | '/study'
    | '/tiptap'
    | '/_layout/$workspaceId'
    | '/_pathlessLayout/_nested-layout'
    | '/posts/$postId'
    | '/_layout/'
    | '/posts/'
    | '/_layout/c/$courseId'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/_layout/$workspaceId/'
    | '/_layout/$workspaceId/c/$chatId'
    | '/_layout/c/$courseId/a'
    | '/_layout/c/$courseId/'
    | '/_layout/c/$courseId/a/$assignmentId'
    | '/_layout/c/$courseId/n/$notesId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudyRoute: typeof StudyRoute
  TiptapRoute: typeof TiptapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tiptap': {
      id: '/tiptap'
      path: '/tiptap'
      fullPath: '/tiptap'
      preLoaderRoute: typeof TiptapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_layout/$workspaceId': {
      id: '/_layout/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof LayoutWorkspaceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$workspaceId/': {
      id: '/_layout/$workspaceId/'
      path: '/'
      fullPath: '/$workspaceId/'
      preLoaderRoute: typeof LayoutWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutWorkspaceIdRoute
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_layout/c/$courseId': {
      id: '/_layout/c/$courseId'
      path: '/c/$courseId'
      fullPath: '/c/$courseId'
      preLoaderRoute: typeof LayoutCCourseIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/c/$courseId/': {
      id: '/_layout/c/$courseId/'
      path: '/'
      fullPath: '/c/$courseId/'
      preLoaderRoute: typeof LayoutCCourseIdIndexRouteImport
      parentRoute: typeof LayoutCCourseIdRoute
    }
    '/_layout/c/$courseId/a': {
      id: '/_layout/c/$courseId/a'
      path: '/a'
      fullPath: '/c/$courseId/a'
      preLoaderRoute: typeof LayoutCCourseIdARouteImport
      parentRoute: typeof LayoutCCourseIdRoute
    }
    '/_layout/$workspaceId/c/$chatId': {
      id: '/_layout/$workspaceId/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/$workspaceId/c/$chatId'
      preLoaderRoute: typeof LayoutWorkspaceIdCChatIdRouteImport
      parentRoute: typeof LayoutWorkspaceIdRoute
    }
    '/_layout/c/$courseId/n/$notesId': {
      id: '/_layout/c/$courseId/n/$notesId'
      path: '/n/$notesId'
      fullPath: '/c/$courseId/n/$notesId'
      preLoaderRoute: typeof LayoutCCourseIdNNotesIdRouteImport
      parentRoute: typeof LayoutCCourseIdRoute
    }
    '/_layout/c/$courseId/a/$assignmentId': {
      id: '/_layout/c/$courseId/a/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/c/$courseId/a/$assignmentId'
      preLoaderRoute: typeof LayoutCCourseIdAAssignmentIdRouteImport
      parentRoute: typeof LayoutCCourseIdARoute
    }
  }
}

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface LayoutWorkspaceIdRouteChildren {
  LayoutWorkspaceIdIndexRoute: typeof LayoutWorkspaceIdIndexRoute
  LayoutWorkspaceIdCChatIdRoute: typeof LayoutWorkspaceIdCChatIdRoute
}

const LayoutWorkspaceIdRouteChildren: LayoutWorkspaceIdRouteChildren = {
  LayoutWorkspaceIdIndexRoute: LayoutWorkspaceIdIndexRoute,
  LayoutWorkspaceIdCChatIdRoute: LayoutWorkspaceIdCChatIdRoute,
}

const LayoutWorkspaceIdRouteWithChildren =
  LayoutWorkspaceIdRoute._addFileChildren(LayoutWorkspaceIdRouteChildren)

interface LayoutCCourseIdARouteChildren {
  LayoutCCourseIdAAssignmentIdRoute: typeof LayoutCCourseIdAAssignmentIdRoute
}

const LayoutCCourseIdARouteChildren: LayoutCCourseIdARouteChildren = {
  LayoutCCourseIdAAssignmentIdRoute: LayoutCCourseIdAAssignmentIdRoute,
}

const LayoutCCourseIdARouteWithChildren =
  LayoutCCourseIdARoute._addFileChildren(LayoutCCourseIdARouteChildren)

interface LayoutCCourseIdRouteChildren {
  LayoutCCourseIdARoute: typeof LayoutCCourseIdARouteWithChildren
  LayoutCCourseIdIndexRoute: typeof LayoutCCourseIdIndexRoute
  LayoutCCourseIdNNotesIdRoute: typeof LayoutCCourseIdNNotesIdRoute
}

const LayoutCCourseIdRouteChildren: LayoutCCourseIdRouteChildren = {
  LayoutCCourseIdARoute: LayoutCCourseIdARouteWithChildren,
  LayoutCCourseIdIndexRoute: LayoutCCourseIdIndexRoute,
  LayoutCCourseIdNNotesIdRoute: LayoutCCourseIdNNotesIdRoute,
}

const LayoutCCourseIdRouteWithChildren = LayoutCCourseIdRoute._addFileChildren(
  LayoutCCourseIdRouteChildren,
)

interface LayoutRouteChildren {
  LayoutWorkspaceIdRoute: typeof LayoutWorkspaceIdRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCCourseIdRoute: typeof LayoutCCourseIdRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutWorkspaceIdRoute: LayoutWorkspaceIdRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCCourseIdRoute: LayoutCCourseIdRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PostsRouteRoute: PostsRouteRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  StudyRoute: StudyRoute,
  TiptapRoute: TiptapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
