name: CI - Golang

on:
  push:
    paths:
      - "apps/backend/**"
  pull_request:
    paths:
      - "apps/backend/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.3
